import { readFile, readdir } from "node:fs/promises";
import path from "node:path";

const sourceRoots = ["ui/src", "apps/web"];
const sourceExtensions = new Set([".cjs", ".js", ".jsx", ".mjs", ".ts", ".tsx"]);
const skippedDirectories = new Set([
  ".next",
  "build",
  "coverage",
  "dist",
  "generated",
  "node_modules",
  "test",
  "tests",
  "__generated__",
  "__tests__",
]);
const styleDirectoryPattern = /(?:^|\/)(?:style|styles|theme|themes)(?:\/|$)/i;
const styleFilePattern = /(?:^|\/)(?:styles?|[^/]+[-.]styles?|[^/]+styles?)\.(?:cjs|js|jsx|mjs|ts|tsx)$/i;
const themeFilePattern = /(?:^|\/)(?:theme[^/]*|[^/]+-theme)\.(?:cjs|js|jsx|mjs|ts|tsx)$/i;
const generatedFilePattern = /^(?:generated(?:[-.][^/]+)?|.*[._-](?:generated|gen))\.(?:cjs|js|jsx|mjs|ts|tsx)$/i;
const testFilePattern = /(?:^|[.-])(?:test|spec)\.(?:cjs|js|jsx|mjs|ts|tsx)$/i;
const generatedHeaderPattern =
  /^\s*(?:(?:\/\/|\/\*|\*|<!--)\s*)?(?:@generated\b|<auto-generated\b|(?:this\s+)?file\s+(?:is|was)\s+(?:auto[- ]?)?generated\b|generated\s+(?:by|file)\b|do\s+not\s+edit\b.*\bgenerated\b)/imu;
const colorFunctionPattern = /\b(?:rgba|rgb|oklch)\s*\(/giu;
const hexColorPattern = /(?<![\w-])#(?:[\da-f]{3}|[\da-f]{4}|[\da-f]{6}|[\da-f]{8})(?![\w-])/giu;
const pixelValuePattern = /(?<![\w.])[-+]?(?:\d+(?:\.\d*)?|\.\d+)px\b/giu;
const styleCallPattern = /\b(?:cn|cx|clsx|classNames|classnames|twMerge|cva|tv|tailwindVariants|keyframes|createGlobalStyle)\s*\(/giu;
const designVariablePattern = /(?:^|_)(?:accent|background|bg|border|color|colour|css|destructive|dimension|fill|font|foreground|gap|height|margin|muted|offset|padding|position|primary|radius|ring|secondary|shadow|size|spacing|stroke|style|surface|transform|width)(?:_|$)/u;
const namedColorVariablePattern = /^(?:black|blue|cyan|gray|green|grey|magenta|orange|pink|purple|red|teal|white|yellow)$/iu;

function blankRange(characters, start, end) {
  for (let index = start; index < end; index += 1) {
    if (characters[index] !== "\n" && characters[index] !== "\r") characters[index] = " ";
  }
}

function skipQuoted(source, start) {
  const quote = source[start];
  let index = start + 1;
  while (index < source.length) {
    if (source[index] === "\\") index += 2;
    else if (source[index] === quote) return index + 1;
    else index += 1;
  }
  return source.length;
}

function maskComments(source) {
  const characters = source.split("");
  let index = 0;
  while (index < source.length) {
    if (source[index] === "'" || source[index] === '"' || source[index] === "`") {
      index = skipQuoted(source, index);
      continue;
    }
    if (source[index] === "/" && source[index + 1] === "/") {
      let end = index + 2;
      while (end < source.length && source[end] !== "\n" && source[end] !== "\r") end += 1;
      blankRange(characters, index, end);
      index = end;
      continue;
    }
    if (source[index] === "/" && source[index + 1] === "*") {
      const close = source.indexOf("*/", index + 2);
      const end = close === -1 ? source.length : close + 2;
      blankRange(characters, index, end);
      index = end;
      continue;
    }
    index += 1;
  }
  return characters.join("");
}

function findStringSpans(source) {
  const spans = [];
  for (let index = 0; index < source.length; ) {
    if (source[index] === "'" || source[index] === '"' || source[index] === "`") {
      const end = skipQuoted(source, index);
      spans.push({ start: index, contentStart: index + 1, contentEnd: Math.max(index + 1, end - 1), end });
      index = end;
    } else index += 1;
  }
  return spans;
}

function maskStrings(source, spans) {
  const characters = source.split("");
  for (const span of spans) blankRange(characters, span.start, span.end);
  return characters.join("");
}

function stringSpanAt(spans, index) {
  let low = 0;
  let high = spans.length - 1;
  while (low <= high) {
    const middle = (low + high) >> 1;
    const span = spans[middle];
    if (index < span.start) high = middle - 1;
    else if (index >= span.end) low = middle + 1;
    else return span;
  }
  return null;
}

function readFunctionValue(source, start) {
  const open = source.indexOf("(", start);
  if (open === -1) return null;
  let depth = 0;
  for (let index = open; index < source.length; index += 1) {
    if (source[index] === "(") depth += 1;
    else if (source[index] === ")") {
      depth -= 1;
      if (depth === 0) return source.slice(start, index + 1);
    }
  }
  return null;
}

function hasNumericColorComponent(value) {
  const argumentsText = value
    .slice(value.indexOf("(") + 1, -1)
    .replace(/\bvar\(\s*--[^)]*\)/giu, " ");
  return /(?:^|[\s,/])[-+]?(?:\d+(?:\.\d*)?|\.\d+)(?:%|deg|rad|turn)?(?=$|[\s,/%])/iu.test(
    argumentsText,
  );
}

function braceIsOpen(source, opening, end) {
  let depth = 0;
  for (let index = opening; index < end; index += 1) {
    if (source[index] === "{") depth += 1;
    else if (source[index] === "}") depth -= 1;
    if (depth === 0) return false;
  }
  return depth > 0;
}

function isInsideStyleObject(code, position) {
  const patterns = [
    { pattern: /\bstyle\s*(?:=|:)\s*\{/giu, requireStyleName: false },
    { pattern: /\b(?:const|let|var)\s+([\w$]+)\s*=\s*\{/giu, requireStyleName: true },
  ];
  for (const { pattern, requireStyleName } of patterns) {
    for (const match of code.matchAll(pattern)) {
      if (match.index >= position) break;
      if (requireStyleName) {
        const name = match[1].replace(/[A-Z]/gu, (letter) => `_${letter.toLowerCase()}`).toLowerCase();
        if (!/(?:^|_)(?:style|styles|css|appearance)(?:_|$)/u.test(name)) continue;
      }
      const opening = match.index + match[0].lastIndexOf("{");
      if (braceIsOpen(code, opening, position)) return true;
    }
  }
  return false;
}

function styledIdentifiers(code) {
  const identifiers = new Set();
  const attributePattern = /\b(?:className|class|style)\s*=\s*\{([^}]*)/giu;
  const identifierPattern = /\b[A-Za-z_$][\w$]*\b/gu;
  const keywords = new Set(["class", "className", "false", "style", "true"]);
  for (const match of code.matchAll(attributePattern)) {
    for (const identifier of match[1].matchAll(identifierPattern)) {
      if (!keywords.has(identifier[0])) identifiers.add(identifier[0]);
    }
  }
  return identifiers;
}

function isInsideTailwindValue(view, span, index) {
  if (!span) return false;
  const tokenStart = Math.max(
    view.lastIndexOf(" ", index - 1),
    view.lastIndexOf("\t", index - 1),
    view.lastIndexOf("\n", index - 1),
    view.lastIndexOf("\r", index - 1),
    span.contentStart - 1,
  ) + 1;
  const opening = view.lastIndexOf("[", index);
  const closing = view.lastIndexOf("]", index);
  if (opening < tokenStart || opening <= closing) return false;
  const prefix = view.slice(tokenStart, opening);
  return /(?:^|:)(?:[\w-]+-|\[--[\w-]+:)\s*$/u.test(prefix);
}

function isInsideStyleCall(code, position) {
  for (const match of code.matchAll(styleCallPattern)) {
    if (match.index >= position) break;
    const opening = match.index + match[0].lastIndexOf("(");
    let depth = 0;
    for (let index = opening; index < position; index += 1) {
      if (code[index] === "(") depth += 1;
      else if (code[index] === ")") depth -= 1;
      if (depth === 0) break;
    }
    if (depth > 0) return true;
  }
  return false;
}

function declaredVariable(code, position) {
  const prefix = code.slice(0, position);
  const match = /\b(?:const|let|var)\s+([\w$]+)(?:\s*:\s*[^=;]+)?\s*=\s*$/u.exec(prefix);
  return match?.[1] ?? null;
}

function normalizedName(name) {
  return name.replace(/[A-Z]/gu, (letter) => `_${letter.toLowerCase()}`).toLowerCase();
}

function isDesignVariable(name, kind) {
  const normalized = normalizedName(name);
  if (designVariablePattern.test(normalized)) return true;
  if (kind === "color" && namedColorVariablePattern.test(name)) return true;
  return false;
}

function hasStyleAttribute(code, position) {
  const prefix = code.slice(0, position);
  return /\b(?:style|fill|stroke|strokeWidth|color|width|height)\s*=\s*\{?\s*$/iu.test(prefix);
}

function hasClassAttribute(code, position) {
  const prefix = code.slice(0, position);
  return /\b(?:className|class)\s*=\s*\{?\s*$/iu.test(prefix);
}

function isClassVariable(name) {
  return /(?:class|classes|className)$/iu.test(name);
}

function hasCssDeclaration(text, index) {
  const boundary = Math.max(text.lastIndexOf(";", index), text.lastIndexOf("{", index), text.lastIndexOf("}", index));
  const segment = text.slice(boundary + 1, index);
  return /^\s*(?:--)?[A-Za-z][\w-]*\s*:\s*[^;{}]*$/u.test(segment);
}

function isCssString(code, span) {
  if (span && code[span.start] === "`") {
    const prefix = code.slice(0, span.start);
    if (/\b(?:css|keyframes|createGlobalStyle|styled(?:\.[\w$]+)?)\s*$/iu.test(prefix)) return true;
  }
  const variable = declaredVariable(code, span?.start ?? 0);
  return Boolean(variable && /(?:^|_)(?:css|style|styles)(?:_|$)/u.test(normalizedName(variable)));
}

function isDesignContext({ code, view, span, index, kind, identifiers }) {
  const position = span?.start ?? index;
  if (
    isInsideTailwindValue(view, span, index) ||
    hasClassAttribute(code, position) ||
    isInsideStyleCall(code, position)
  ) {
    return true;
  }
  const variable = declaredVariable(code, position);
  if (variable && (isClassVariable(variable) || identifiers.has(variable))) return true;
  if (hasStyleAttribute(code, position) || isInsideStyleObject(code, position)) return true;
  if (variable && isDesignVariable(variable, kind)) return true;
  if (span && isCssString(code, span) && hasCssDeclaration(view.slice(span.contentStart, index), index - span.contentStart)) {
    return true;
  }
  return false;
}

function lineForOffset(lineStarts, offset) {
  let low = 0;
  let high = lineStarts.length;
  while (low < high) {
    const middle = (low + high) >> 1;
    if (lineStarts[middle] <= offset) low = middle + 1;
    else high = middle;
  }
  return low;
}

function sourceLine(source, lineStarts, line) {
  const start = lineStarts[line - 1];
  const end = line < lineStarts.length ? lineStarts[line] - 1 : source.length;
  return source.slice(start, end).replace(/\r$/u, "");
}

function findCandidates(view) {
  const candidates = [];
  for (const match of view.matchAll(hexColorPattern)) {
    candidates.push({ index: match.index, value: match[0], kind: "color" });
  }
  for (const match of view.matchAll(pixelValuePattern)) {
    candidates.push({ index: match.index, value: match[0], kind: "pixel" });
  }
  for (const match of view.matchAll(colorFunctionPattern)) {
    const value = readFunctionValue(view, match.index);
    if (value && hasNumericColorComponent(value)) {
      candidates.push({ index: match.index, value, kind: "color" });
    }
  }
  return candidates.sort((left, right) => left.index - right.index);
}

function shouldSkipFile(relativePath, entryName) {
  const normalized = relativePath.replace(/\\/gu, "/");
  return (
    entryName.endsWith(".d.ts") ||
    styleDirectoryPattern.test(normalized) ||
    styleFilePattern.test(normalized) ||
    themeFilePattern.test(normalized) ||
    generatedFilePattern.test(entryName) ||
    testFilePattern.test(entryName) ||
    /(?:^|\/)__(?:tests|generated)__(?:\/|$)/iu.test(normalized)
  );
}

async function listSourceFiles(directory, root, files = []) {
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    if (entry.isDirectory() && skippedDirectories.has(entry.name)) continue;
    const target = path.join(directory, entry.name);
    if (entry.isDirectory()) {
      await listSourceFiles(target, root, files);
      continue;
    }
    if (!entry.isFile() || !sourceExtensions.has(path.extname(entry.name).toLowerCase())) continue;
    const relativePath = path.relative(root, target).split(path.sep).join("/");
    if (!shouldSkipFile(relativePath, entry.name)) files.push({ path: target, relativePath, name: entry.name });
  }
  return files;
}

export async function collectDesignValueOccurrences(root) {
  const occurrences = [];
  for (const sourceRoot of sourceRoots) {
    const directory = path.join(root, sourceRoot);
    let files;
    try {
      files = await listSourceFiles(directory, root);
    } catch (error) {
      if (error.code === "ENOENT") continue;
      throw error;
    }
    for (const file of files) {
      const source = await readFile(file.path, "utf8");
      if (generatedHeaderPattern.test(source.slice(0, 600))) continue;
      const view = maskComments(source);
      const spans = findStringSpans(view);
      const code = maskStrings(view, spans);
      const identifiers = styledIdentifiers(code);
      const lineStarts = [0];
      for (let index = 0; index < source.length; index += 1) {
        if (source[index] === "\n") lineStarts.push(index + 1);
      }
      for (const candidate of findCandidates(view)) {
        const span = stringSpanAt(spans, candidate.index);
        if (!isDesignContext({ code, view, span, index: candidate.index, kind: candidate.kind, identifiers })) continue;
        const line = lineForOffset(lineStarts, candidate.index);
        occurrences.push({
          file: file.relativePath,
          line,
          source: sourceLine(source, lineStarts, line),
          value: candidate.value,
        });
      }
    }
  }
  return occurrences.sort(
    (left, right) => left.file.localeCompare(right.file) || left.line - right.line || left.value.localeCompare(right.value),
  );
}

function occurrenceKey(occurrence) {
  // Exact line text prevents edits or nearby additions from inheriting a legacy exception.
  return JSON.stringify([occurrence.file, occurrence.line, occurrence.source, occurrence.value]);
}

async function loadBaseline(root) {
  const file = path.join(root, "tooling", "boundaries", "design-values.baseline.json");
  const parsed = JSON.parse(await readFile(file, "utf8"));
  if (!Array.isArray(parsed.entries)) throw new Error(`${file} must contain an entries array`);
  const counts = new Map();
  for (const entry of parsed.entries) {
    if (
      !entry ||
      typeof entry.file !== "string" ||
      !Number.isInteger(entry.line) ||
      typeof entry.source !== "string" ||
      typeof entry.value !== "string"
    ) {
      throw new Error(`${file} contains a malformed exact exception`);
    }
    const key = occurrenceKey(entry);
    counts.set(key, (counts.get(key) ?? 0) + 1);
  }
  return counts;
}

export async function validateDesignValues(root) {
  let baseline;
  try {
    baseline = await loadBaseline(root);
  } catch (error) {
    return [`tooling/boundaries/design-values.baseline.json could not be read: ${error.message}`];
  }
  const errors = [];
  for (const occurrence of await collectDesignValueOccurrences(root)) {
    const key = occurrenceKey(occurrence);
    const remaining = baseline.get(key) ?? 0;
    if (remaining > 0) baseline.set(key, remaining - 1);
    else errors.push(`${occurrence.file}:${occurrence.line} contains hard-coded design value ${JSON.stringify(occurrence.value)}`);
  }
  return errors;
}
