import "server-only";

export const SearchService = Object.freeze({
  key: "search",
  boundary: "@vortex/search",
});

export {
  buildSearchDocument,
  searchableFieldConfigurationFor,
  searchDocumentStoreCommand,
  searchDocumentLimits,
  searchDocumentSchemaVersion,
  searchPriorityWeights,
  type BuildSearchDocumentResult,
  type SearchableFieldConfiguration,
  type SearchableFieldConfigurationEntry,
  type SearchableFieldPolicy,
  type SearchDocument,
  type SearchDocumentDeletion,
  type SearchDocumentEntry,
  type SearchDocumentRefusalCode,
  type SearchDocumentStoreCommand,
  type SearchDocumentStoreOutcome,
  type SearchRecordSnapshot,
} from "./document-store";

export {
  consumeSearchEvents,
  createSearchEventConsumer,
  planSearchRebuildPage,
  searchEventConsumerErrorCodes,
  searchEventConsumerKey,
  searchEventConsumerLimits,
  searchIndexFreshness,
  searchIndexFreshnessTargetMs,
  searchIndexStaleCeilingMs,
  SearchEventConsumerError,
  type ConsumeSearchEventsInput,
  type ConsumeSearchEventsResult,
  type PlanSearchRebuildInput,
  type SearchDeliveryFailureCode,
  type SearchEventConsumer,
  type SearchEventConsumerErrorCode,
  type SearchEventConsumerOutcome,
  type SearchEventDelivery,
  type SearchIndexFreshness,
  type SearchIndexFreshnessInput,
  type SearchIndexFreshnessState,
  type SearchIndexOccurrenceDependencies,
  type SearchIndexOccurrenceOutcome,
  type SearchIndexOccurrenceResult,
  type SearchIndexRecordType,
  type SearchOccurrenceSkipReason,
  type SearchRebuildCandidate,
  type SearchRebuildCheckpoint,
  type SearchRebuildDependencies,
  type SearchRebuildPageResult,
  type SearchRebuildRefusal,
  type SearchRebuildStored,
} from "./event-consumer";
