import "server-only";

export {
  createAuthenticatedPageCapabilityService,
  type AuthenticatedPageCapabilityDependencies,
  type FixedAuthenticatedPageCapability,
  type FixedAuthenticatedPageCapabilityAdapter,
} from "./authenticated-page-capability";
export {
  projectPageCapability,
  type PageCapabilityState,
  type PlacementCapabilityState,
  type ProjectedPageCapability,
} from "./page-capability-projection";
export {
  discardAndReprojectPageContent,
  isRefusedPageContentRevision,
  pageContentRevisionRelation,
  projectPageContent,
  readPageContentRevisions,
  type PageContentDiscardOutcome,
  type PageContentProjection,
  type PageContentReprojection,
  type PageContentRevisionRelation,
  type PageContentRevisions,
} from "./page-content-discard";
export {
  createStoredPageCapabilityService,
  type StoredPageCapabilityDependencies,
  type StoredPageCapabilitySelection,
  type StoredPageReadModelValue,
} from "./stored-page-capability";
export {
  collectNavigationPermissionKeys,
  createAuthenticatedNavigationProjectionService,
  createStoredNavigationProjectionService,
  projectNavigation,
  type AuthenticatedNavigationProjectionDependencies,
  type FixedAuthenticatedNavigationProjection,
  type FixedAuthenticatedNavigationProjectionAdapter,
  type NavigationPermissionBinding,
  type NavigationPermissionDecisions,
  type ProjectedNavigation,
  type ProjectedNavigationItem,
  type StoredNavigationProjectionDependencies,
} from "./navigation-projection";
export {
  createProtectedReadModelResolver,
  type ProtectedReadModelReaders,
  type ProtectedReadModelRequestContext,
  type ProtectedReadModelResolution,
} from "./protected-read-model-resolution";
export {
  projectRecordDetailData,
  projectRecordsTableData,
  type ComponentDataProjectionInput,
  type ProjectedCellValue,
  type ProjectedComponentData,
  type ProjectedRecordDetailValues,
  type ProjectedTableRow,
  type ProjectedTableValues,
} from "./component-data-projection";
export {
  buildRecordsTableQueryCommand,
  createRecordsTableQueryResolver,
  type RecordsTableQueryRequest,
  type RecordsTableQueryResolution,
  type RecordsTableQueryRunner,
} from "./records-table-query";
export {
  abandonPrivateFormDraftCommandSchema,
  createPrivateFormDraftCommandSchema,
  PrivateFormDraftError,
  privateFormDraftErrorCodes,
  privateFormDraftFieldValidationSchema,
  privateFormDraftInputKeySchema,
  privateFormDraftLimits,
  privateFormDraftProjectionSchema,
  privateFormDraftRetentionDays,
  privateFormDraftSchema,
  privateFormDraftScopeSchema,
  privateFormDraftValidationSchema,
  projectPrivateFormDraft,
  readPrivateFormDraftCommandSchema,
  restrictPrivateFormDraftInput,
  updatePrivateFormDraftCommandSchema,
  type AbandonPrivateFormDraftCommand,
  type CreatePrivateFormDraftCommand,
  type PrivateFormDraft,
  type PrivateFormDraftAbandonResult,
  type PrivateFormDraftCreateResult,
  type PrivateFormDraftErrorCode,
  type PrivateFormDraftFieldValidation,
  type PrivateFormDraftProjection,
  type PrivateFormDraftReadResult,
  type PrivateFormDraftScope,
  type PrivateFormDraftUpdateResult,
  type ReadPrivateFormDraftCommand,
  type UpdatePrivateFormDraftCommand,
} from "./form-drafts";
export {
  abandonPrivateFormDraft,
  createPrivateFormDraft,
  createPrivateFormDraftService,
  expirePrivateFormDrafts,
  readPrivateFormDraft,
  updatePrivateFormDraft,
  type PrivateFormDraftAuthority,
  type PrivateFormDraftAuthorityAdapter,
  type PrivateFormDraftServiceDependencies,
} from "./form-drafts-repository";
export {
  createPrivateFormContinuationAdapter,
  type PrivateFormContinuationAdapter,
  type PrivateFormContinuationDependencies,
  type PrivateFormContinuationDraft,
  type PrivateFormContinuationDraftDisposition,
  type PrivateFormContinuationDraftPort,
  type PrivateFormContinuationInput,
  type PrivateFormContinuationResult,
} from "./form-continuation";
export {
  buildConnectionAdministrationCommand,
  connectionAdministrationInputKeys,
  connectionAdministrationInputKeysAreCommandProperties,
  connectionAdministrationPageFlow,
  connectionAdministrationPageFlowIsExact,
  connectionAdministrationRecoveryStates,
  connectionAdministrationWriteOnlyFieldKeys,
  NO_COMMAND_ATTEMPTED,
  projectConnectionAdministrationForm,
  projectConnectionAdministrationPage,
  projectConnectionAdministrationRecovery,
  projectConnectionInstanceStatus,
  type ConnectionAdministrationApplicationChange,
  type ConnectionAdministrationCommandInput,
  type ConnectionAdministrationCommandReadiness,
  type ConnectionAdministrationFormDefinition,
  type ConnectionAdministrationFormField,
  type ConnectionAdministrationHealthCheckOutcome,
  type ConnectionAdministrationInputKey,
  type ConnectionAdministrationPageFlowStep,
  type ConnectionAdministrationPageResolution,
  type ConnectionAdministrationPageSource,
  type ConnectionAdministrationPageView,
  type ConnectionAdministrationRecoveryProjection,
  type ConnectionAdministrationRecoveryState,
  type ConnectionAdministrationStepKey,
  type ConnectionAdministrationTypeView,
  type ConnectionAdministrationValueType,
  type ConnectionInstanceStatusView,
} from "./connection-administration";

export const PageService = Object.freeze({
  key: "page",
  boundary: "@vortex/page",
});
