import { moduleSourceDocumentSchema, type ModuleSourceDocument } from "@vortex/contracts";

const editableRecordFields = [
  "subject_display_name",
  "change_kind",
  "requested_display_name",
  "requested_parent_reference",
  "reason",
] as const;

const allRecordFields = [...editableRecordFields, "state"];

// The tenant, organisation and tenant-administrator system record types are
// read-only projections of protected Identity facts. They declare only safe,
// projected fields; they have no ordinary write path, and their changes go
// through the tenant governance service's protected operations, never through
// the record. Row visibility stays inside each registered reader: the
// organisation needs the fixed platform.tenant.hierarchy.read capability on the
// caller's own tenant, the tenant projection lists exactly the active tenants
// the caller's effective structural administrator assignment already lists, and
// tenant administrators need the fixed
// platform.tenant.administrators.read capability. Grant, revocation and
// correlation evidence is never projected.
const tenantAllFields = [
  "organization_id",
  "revision",
  "short_name",
  "display_name",
  "state",
  "state_changed_at",
  "created_at",
];
const organizationAllFields = [
  "organization_id",
  "revision",
  "tenant_id",
  "parent_organization_id",
  "short_name",
  "display_name",
  "state",
  "state_changed_at",
  "created_at",
];
const tenantAdministratorAllFields = [
  "organization_id",
  "revision",
  "tenant_id",
  "identity_id",
  "capability_keys",
  "starts_at",
  "expires_at",
  "state",
];
// The seven structural tenant capabilities the projection can return, in the
// canonical order the private tenant writer accepts.
const tenantStructuralCapabilityOptions = [
  { value: "platform.tenant.administrators.manage", label: "Manage tenant administrators" },
  { value: "platform.tenant.administrators.read", label: "Read tenant administrators" },
  { value: "platform.tenant.hierarchy.read", label: "Read tenant hierarchy" },
  { value: "platform.tenant.organizations.create", label: "Create organisations" },
  { value: "platform.tenant.organizations.lifecycle", label: "Change organisation lifecycle" },
  { value: "platform.tenant.organizations.rename", label: "Rename organisations" },
  { value: "platform.tenant.organizations.reparent", label: "Move organisations" },
] as const;
const tenantStateOptions = [
  { value: "active", label: "Active" },
  { value: "suspended", label: "Suspended" },
  { value: "archived", label: "Archived" },
  { value: "removal_pending", label: "Removal pending" },
] as const;

/**
 * Ordinary, application-contained records that capture an organisation lifecycle
 * request and its outcome, beside the read-only tenant, organisation and
 * tenant-administrator system records. The lifecycle request describes intent
 * only: it confers no organisation data access and no tenant authority. The
 * system record types are read-only projections of protected Identity facts, so
 * the ordinary query path reads them and their changes still go through the
 * tenant governance service's protected operations. Protected tenant reads and
 * operations stay with the tenant governance service and its read models.
 */
export const tenantAdministrationModule: ModuleSourceDocument = moduleSourceDocumentSchema.parse({
  source_contract_version: "3.0.0",
  root_alias: "mod_tenant_administration",
  key: "vortex.tenant_administration",
  kind: "module",
  body: {
    name: "Tenant Administration",
    description:
      "Tenant structure and organisation lifecycle requests for a tenant administrator.",
    dependencies: [],
    record_types: [
      {
        id: "rt_organization_lifecycle_request",
        key: "organization_lifecycle_request",
        name: "Organisation lifecycle request",
        plural_name: "Organisation lifecycle requests",
        title_field: "subject_display_name",
        storage_contract_id: "srt_tenant_admin_lifecycle",
        storage_scope: "application_contained",
        ownership_mode: "none",
        standard_actions: ["create", "read", "update", "soft_delete", "restore", "export"],
        custom_actions: ["act_submit_organization_lifecycle_request"],
        fields: [
          {
            id: "fld_lifecycle_subject",
            key: "subject_display_name",
            label: "Organisation",
            required: true,
            unique: false,
            filterable: true,
            sortable: true,
            search_priority: "first",
            personal_data: "none",
            public_display: "refused",
            type: "text",
            settings: { max_length: 120 },
          },
          {
            id: "fld_lifecycle_change_kind",
            key: "change_kind",
            label: "Requested change",
            required: true,
            unique: false,
            filterable: true,
            sortable: false,
            personal_data: "none",
            public_display: "refused",
            type: "choice",
            settings: {
              options: [
                { value: "create", label: "Create organisation" },
                { value: "rename", label: "Rename organisation" },
                { value: "reparent", label: "Move organisation" },
                { value: "suspend", label: "Suspend organisation" },
                { value: "reactivate", label: "Reactivate organisation" },
                { value: "archive", label: "Archive organisation" },
              ],
            },
          },
          {
            id: "fld_lifecycle_display_name",
            key: "requested_display_name",
            label: "Requested display name",
            required: false,
            unique: false,
            filterable: false,
            sortable: false,
            personal_data: "none",
            public_display: "refused",
            type: "text",
            settings: { max_length: 120 },
          },
          {
            id: "fld_lifecycle_parent_reference",
            key: "requested_parent_reference",
            label: "Requested parent organisation",
            required: false,
            unique: false,
            filterable: false,
            sortable: false,
            personal_data: "none",
            public_display: "refused",
            type: "text",
            settings: { max_length: 120 },
          },
          {
            id: "fld_lifecycle_reason",
            key: "reason",
            label: "Reason",
            required: true,
            unique: false,
            filterable: false,
            sortable: false,
            search_priority: "normal",
            personal_data: "personal",
            public_display: "refused",
            type: "long_text",
            settings: { max_length: 1_000 },
          },
          {
            id: "fld_lifecycle_state",
            key: "state",
            label: "State",
            required: true,
            unique: false,
            filterable: true,
            sortable: true,
            personal_data: "none",
            public_display: "refused",
            type: "choice",
            settings: {
              options: [
                { value: "draft", label: "Draft" },
                { value: "submitted", label: "Submitted" },
              ],
            },
            default: "draft",
          },
        ],
        relationships: [],
      },
      {
        id: "rt_tenant",
        key: "tenant",
        name: "Tenant",
        plural_name: "Tenants",
        title_field: "display_name",
        storage_contract_id: "srt_tenant_admin_tenant",
        storage_scope: "organisation_shared",
        ownership_mode: "none",
        standard_actions: ["read"],
        custom_actions: [],
        system_projection: {
          protected_view: "tenants",
          organization_field: "organization_id",
          revision_field: "revision",
          filterable_fields: ["state"],
          sortable_fields: [
            "short_name",
            "display_name",
            "state",
            "state_changed_at",
            "created_at",
          ],
        },
        fields: [
          {
            id: "fld_tenant_organization_id",
            key: "organization_id",
            label: "Organisation",
            required: true,
            unique: false,
            filterable: false,
            sortable: false,
            personal_data: "none",
            public_display: "refused",
            type: "text",
            settings: { max_length: 36 },
          },
          {
            id: "fld_tenant_revision",
            key: "revision",
            label: "Revision",
            required: true,
            unique: false,
            filterable: false,
            sortable: false,
            personal_data: "none",
            public_display: "refused",
            type: "whole_number",
            settings: {},
          },
          {
            id: "fld_tenant_short_name",
            key: "short_name",
            label: "Short name",
            required: false,
            unique: false,
            filterable: false,
            sortable: true,
            search_priority: "first",
            personal_data: "none",
            public_display: "refused",
            type: "text",
            settings: { max_length: 40 },
          },
          {
            id: "fld_tenant_display_name",
            key: "display_name",
            label: "Display name",
            required: false,
            unique: false,
            filterable: false,
            sortable: true,
            search_priority: "normal",
            personal_data: "none",
            public_display: "refused",
            type: "text",
            settings: { max_length: 120 },
          },
          {
            id: "fld_tenant_state",
            key: "state",
            label: "State",
            required: false,
            unique: false,
            filterable: true,
            sortable: true,
            personal_data: "none",
            public_display: "refused",
            type: "choice",
            settings: { options: [...tenantStateOptions] },
          },
          {
            id: "fld_tenant_state_changed_at",
            key: "state_changed_at",
            label: "State changed at",
            required: false,
            unique: false,
            filterable: false,
            sortable: true,
            personal_data: "none",
            public_display: "refused",
            type: "date_time",
            settings: { display_time_zone: "organisation" },
          },
          {
            id: "fld_tenant_created_at",
            key: "created_at",
            label: "Created at",
            required: false,
            unique: false,
            filterable: false,
            sortable: true,
            personal_data: "none",
            public_display: "refused",
            type: "date_time",
            settings: { display_time_zone: "organisation" },
          },
        ],
        relationships: [],
      },
      {
        id: "rt_tenant_admin_organization",
        key: "organization",
        name: "Organisation",
        plural_name: "Organisations",
        title_field: "display_name",
        storage_contract_id: "srt_tenant_admin_organization",
        storage_scope: "organisation_shared",
        ownership_mode: "none",
        standard_actions: ["read"],
        custom_actions: [],
        system_projection: {
          protected_view: "tenant_structure",
          organization_field: "organization_id",
          revision_field: "revision",
          filterable_fields: ["state"],
          sortable_fields: [
            "short_name",
            "display_name",
            "state",
            "state_changed_at",
            "created_at",
          ],
        },
        fields: [
          {
            id: "fld_organization_organization_id",
            key: "organization_id",
            label: "Organisation",
            required: true,
            unique: false,
            filterable: false,
            sortable: false,
            personal_data: "none",
            public_display: "refused",
            type: "text",
            settings: { max_length: 36 },
          },
          {
            id: "fld_organization_revision",
            key: "revision",
            label: "Revision",
            required: true,
            unique: false,
            filterable: false,
            sortable: false,
            personal_data: "none",
            public_display: "refused",
            type: "whole_number",
            settings: {},
          },
          {
            id: "fld_organization_tenant_id",
            key: "tenant_id",
            label: "Tenant",
            required: false,
            unique: false,
            filterable: false,
            sortable: false,
            personal_data: "none",
            public_display: "refused",
            type: "text",
            settings: { max_length: 36 },
          },
          {
            id: "fld_organization_parent_id",
            key: "parent_organization_id",
            label: "Parent organisation",
            required: false,
            unique: false,
            filterable: false,
            sortable: false,
            personal_data: "none",
            public_display: "refused",
            type: "text",
            settings: { max_length: 36 },
          },
          {
            id: "fld_organization_short_name",
            key: "short_name",
            label: "Short name",
            required: false,
            unique: false,
            filterable: false,
            sortable: true,
            search_priority: "first",
            personal_data: "none",
            public_display: "refused",
            type: "text",
            settings: { max_length: 63 },
          },
          {
            id: "fld_organization_display_name",
            key: "display_name",
            label: "Display name",
            required: false,
            unique: false,
            filterable: false,
            sortable: true,
            search_priority: "normal",
            personal_data: "none",
            public_display: "refused",
            type: "text",
            settings: { max_length: 120 },
          },
          {
            id: "fld_organization_state",
            key: "state",
            label: "State",
            required: false,
            unique: false,
            filterable: true,
            sortable: true,
            personal_data: "none",
            public_display: "refused",
            type: "choice",
            settings: { options: [...tenantStateOptions] },
          },
          {
            id: "fld_organization_state_changed_at",
            key: "state_changed_at",
            label: "State changed at",
            required: false,
            unique: false,
            filterable: false,
            sortable: true,
            personal_data: "none",
            public_display: "refused",
            type: "date_time",
            settings: { display_time_zone: "organisation" },
          },
          {
            id: "fld_organization_created_at",
            key: "created_at",
            label: "Created at",
            required: false,
            unique: false,
            filterable: false,
            sortable: true,
            personal_data: "none",
            public_display: "refused",
            type: "date_time",
            settings: { display_time_zone: "organisation" },
          },
        ],
        relationships: [],
      },
      {
        id: "rt_tenant_administrator",
        key: "tenant_administrator",
        name: "Tenant administrator",
        plural_name: "Tenant administrators",
        title_field: "identity_id",
        storage_contract_id: "srt_tenant_admin_administrator",
        storage_scope: "organisation_shared",
        ownership_mode: "none",
        standard_actions: ["read"],
        custom_actions: [],
        system_projection: {
          protected_view: "tenant_administrators",
          organization_field: "organization_id",
          revision_field: "revision",
          filterable_fields: ["state"],
          sortable_fields: ["starts_at", "expires_at", "state"],
        },
        fields: [
          {
            id: "fld_tenant_administrator_organization_id",
            key: "organization_id",
            label: "Organisation",
            required: true,
            unique: false,
            filterable: false,
            sortable: false,
            personal_data: "none",
            public_display: "refused",
            type: "text",
            settings: { max_length: 36 },
          },
          {
            id: "fld_tenant_administrator_revision",
            key: "revision",
            label: "Revision",
            required: true,
            unique: false,
            filterable: false,
            sortable: false,
            personal_data: "none",
            public_display: "refused",
            type: "whole_number",
            settings: {},
          },
          {
            id: "fld_tenant_administrator_tenant_id",
            key: "tenant_id",
            label: "Tenant",
            required: false,
            unique: false,
            filterable: false,
            sortable: false,
            personal_data: "none",
            public_display: "refused",
            type: "text",
            settings: { max_length: 36 },
          },
          {
            id: "fld_tenant_administrator_identity_id",
            key: "identity_id",
            label: "Identity",
            required: false,
            unique: false,
            filterable: false,
            sortable: false,
            search_priority: "first",
            personal_data: "personal",
            public_display: "refused",
            type: "text",
            settings: { max_length: 36 },
          },
          {
            id: "fld_tenant_administrator_capability_keys",
            key: "capability_keys",
            label: "Capabilities",
            required: false,
            unique: false,
            filterable: false,
            sortable: false,
            personal_data: "none",
            public_display: "refused",
            type: "several_choices",
            settings: { options: [...tenantStructuralCapabilityOptions] },
          },
          {
            id: "fld_tenant_administrator_starts_at",
            key: "starts_at",
            label: "Starts at",
            required: false,
            unique: false,
            filterable: false,
            sortable: true,
            personal_data: "none",
            public_display: "refused",
            type: "date_time",
            settings: { display_time_zone: "organisation" },
          },
          {
            id: "fld_tenant_administrator_expires_at",
            key: "expires_at",
            label: "Expires at",
            required: false,
            unique: false,
            filterable: false,
            sortable: true,
            personal_data: "none",
            public_display: "refused",
            type: "date_time",
            settings: { display_time_zone: "organisation" },
          },
          {
            id: "fld_tenant_administrator_state",
            key: "state",
            label: "State",
            required: false,
            unique: false,
            filterable: true,
            sortable: true,
            personal_data: "none",
            public_display: "refused",
            type: "choice",
            settings: {
              options: [
                { value: "scheduled", label: "Scheduled" },
                { value: "active", label: "Active" },
                { value: "expired", label: "Expired" },
                { value: "revoked", label: "Revoked" },
              ],
            },
          },
        ],
        relationships: [],
      },
    ],
    permissions: [
      {
        id: "perm_lifecycle_create",
        key: "vortex.tenant_administration.organization_lifecycle_request.create",
        label: "Create organisation lifecycle request",
        description: "Allows the standard create operation for lifecycle requests.",
        record_type: "organization_lifecycle_request",
        action_kind: "create",
        administrative: false,
        record_scope: { routes: [{ kind: "all_records" }] },
        field_policy: {
          readable_fields: allRecordFields,
          changeable_fields: [...editableRecordFields],
        },
      },
      {
        id: "perm_lifecycle_read",
        key: "vortex.tenant_administration.organization_lifecycle_request.read",
        label: "Read organisation lifecycle request",
        description: "Allows the standard read operation for lifecycle requests.",
        record_type: "organization_lifecycle_request",
        action_kind: "read",
        administrative: false,
        record_scope: { routes: [{ kind: "all_records" }] },
        field_policy: { readable_fields: allRecordFields, changeable_fields: [] },
      },
      {
        id: "perm_lifecycle_update",
        key: "vortex.tenant_administration.organization_lifecycle_request.update",
        label: "Update organisation lifecycle request",
        description: "Allows the standard update operation for lifecycle requests.",
        record_type: "organization_lifecycle_request",
        action_kind: "update",
        administrative: false,
        record_scope: { routes: [{ kind: "all_records" }] },
        field_policy: {
          readable_fields: allRecordFields,
          changeable_fields: [...editableRecordFields],
        },
      },
      {
        id: "perm_lifecycle_soft_delete",
        key: "vortex.tenant_administration.organization_lifecycle_request.soft_delete",
        label: "Remove organisation lifecycle request",
        description: "Allows the standard soft-delete operation for lifecycle requests.",
        record_type: "organization_lifecycle_request",
        action_kind: "delete",
        administrative: false,
        record_scope: { routes: [{ kind: "all_records" }] },
        field_policy: { readable_fields: [], changeable_fields: [] },
      },
      {
        id: "perm_lifecycle_restore",
        key: "vortex.tenant_administration.organization_lifecycle_request.restore",
        label: "Restore organisation lifecycle request",
        description: "Allows the standard restore operation for lifecycle requests.",
        record_type: "organization_lifecycle_request",
        action_kind: "restore",
        administrative: false,
        record_scope: { routes: [{ kind: "all_records" }] },
        field_policy: { readable_fields: [], changeable_fields: [] },
      },
      {
        id: "perm_lifecycle_export",
        key: "vortex.tenant_administration.organization_lifecycle_request.export",
        label: "Export organisation lifecycle request",
        description: "Allows the standard export operation for lifecycle requests.",
        record_type: "organization_lifecycle_request",
        action_kind: "export",
        administrative: false,
        record_scope: { routes: [{ kind: "all_records" }] },
        field_policy: { readable_fields: allRecordFields, changeable_fields: [] },
      },
      {
        id: "perm_lifecycle_submit",
        key: "vortex.tenant_administration.organization_lifecycle_request.submit",
        label: "Submit organisation lifecycle request",
        description: "Allows recording a lifecycle request reason and submitting it for review.",
        record_type: "organization_lifecycle_request",
        action_kind: "named",
        named_action: "submit",
        administrative: false,
        record_scope: { routes: [{ kind: "all_records" }] },
        field_policy: { readable_fields: ["reason", "state"], changeable_fields: ["reason", "state"] },
      },
      {
        id: "perm_tenant_read",
        key: "vortex.tenant_administration.tenant.read",
        label: "Read tenants",
        description: "Allows reading the protected tenant projection as a system record.",
        record_type: "tenant",
        action_kind: "read",
        administrative: false,
        record_scope: { routes: [{ kind: "all_records" }] },
        field_policy: { readable_fields: tenantAllFields, changeable_fields: [] },
      },
      {
        id: "perm_organization_read",
        key: "vortex.tenant_administration.organization.read",
        label: "Read organisations",
        description:
          "Allows reading the protected organisation projection as a system record.",
        record_type: "organization",
        action_kind: "read",
        administrative: false,
        record_scope: { routes: [{ kind: "all_records" }] },
        field_policy: { readable_fields: organizationAllFields, changeable_fields: [] },
      },
      {
        id: "perm_tenant_administrator_read",
        key: "vortex.tenant_administration.tenant_administrator.read",
        label: "Read tenant administrators",
        description:
          "Allows reading the protected tenant-administrator projection as a system record.",
        record_type: "tenant_administrator",
        action_kind: "read",
        administrative: false,
        record_scope: { routes: [{ kind: "all_records" }] },
        field_policy: {
          readable_fields: tenantAdministratorAllFields,
          changeable_fields: [],
        },
      },
    ],
    actions: [
      {
        id: "act_submit_organization_lifecycle_request",
        key: "vortex.tenant_administration.organization_lifecycle_request.submit",
        label: "Submit organisation lifecycle request",
        record_type: "organization_lifecycle_request",
        permission: "vortex.tenant_administration.organization_lifecycle_request.submit",
        shareable: false,
        precondition: { field: "state", operator: "equals", value: "draft" },
        inputs: [
          {
            key: "reason",
            label: "Reason",
            required: true,
            type: "text",
            validation: { maximum_length: 1_000 },
          },
        ],
        tasks: [
          {
            id: "set_reason",
            type: "record.set_fields",
            properties: { values: { reason: "{{ inputs.reason }}" } },
          },
          {
            id: "set_state",
            type: "record.set_fields",
            properties: { values: { state: { kind: "literal", literal: { type: "json", value: "submitted" } } } },
          },
        ],
      },
    ],
    events: [],
    flows: [],
    extension_points: [],
    sharing_conditions: [],
    queries: [],
  },
});
