import "server-only";

export const FileService = Object.freeze({
  key: "file",
  boundary: "@vortex/file",
});

export * from "./file-metadata";
export * from "./storage-policy";
export * from "./content-safety";
export * from "./attachment-authority";
export * from "./storage-credentials";
export {
  createFileRemovalEligibilityService,
  matchesProtectedLegalHold,
  type FileHoldEvaluationScope,
  type FileRemovalAuthorityResolution,
  type FileRemovalEligibilityDecision,
  type FileRemovalEligibilityRequest,
  type FileRemovalEligibilityService,
  type FileRemovalRefusalReason,
  type ResolveCurrentFileRemovalAuthority,
} from "./removal-eligibility";
export {
  createFileRemovalCoordinator,
  type FilePreviewDeleter,
  type FileRemovalCoordinator,
  type FileRemovalCoordinatorDependencies,
  type FileRemovalRepository,
  type FileRemovalResult,
  type FileStorageDeleter,
} from "./object-removal";
export {
  runUploadCapabilityAdmission,
  type UploadCapabilityAdmissionRequest,
  type UploadCapabilityAdmissionResult,
  type UploadCapabilityReservationPorts,
} from "./upload-capability-admission";
export {
  PENDING_UPLOAD_WINDOW_SECONDS,
  activateUploadedFile,
  completeFileUpload,
  createFileUploadCoordinator,
  createUploadStorageAuthorityResolver,
  renewPendingUpload,
  reservePendingUpload,
  type ClaimedUploadGrant,
  type FileUploadActivationInput,
  type FileUploadActivationResult,
  type FileUploadAdmissionInput,
  type FileUploadAdmissionResult,
  type FileUploadCompletionInput,
  type FileUploadCompletionResult,
  type FileUploadCoordinator,
  type FileUploadCoordinatorDependencies,
  type FileUploadRenewalInput,
  type FileUploadRenewalResult,
  type FileUploadRepository,
  type IsolatedFileScanner,
  type PendingUploadReservation,
  type PendingUploadState,
  type UploadAttachmentSettings,
  type UploadedObjectInspector,
  type UploadedObjectLocation,
} from "./upload";
export {
  MAXIMUM_ABANDONED_UPLOAD_BATCH,
  buildContentDisposition,
  cleanupAbandonedUploads,
  composeStorageAuthorityResolvers,
  createDefaultUpstreamStorageReader,
  createFileReadCoordinator,
  createReadStorageAuthorityResolver,
  fileReadRefusalHttpStatus,
  fileReadViewerFromSessionContext,
  isExecutableOrActiveBrowserContent,
  parseRangeHeader,
  privateFileResponseHeaders,
  type AbandonedUploadCandidate,
  type AbandonedUploadCleanupDependencies,
  type AbandonedUploadCleanupOutcome,
  type AbandonedUploadCleanupRepository,
  type AbandonedUploadCleanupResult,
  type ClaimedDownloadGrant,
  type CurrentReadAuthority,
  type FilePreviewRenderer,
  type FileReadCoordinator,
  type FileReadCoordinatorDependencies,
  type FileReadPurpose,
  type FileReadRefusal,
  type FileReadRefusalReason,
  type FileReadRepository,
  type FileReadRequest,
  type FileReadResult,
  type FileReadStreamResponse,
  type FileReadViewer,
  type ParsedByteRange,
  type RangeParseResult,
  type SharedRecordFileGrant,
  type UpstreamStorageReader,
  type UpstreamStorageReadOptions,
  type UpstreamStorageReadResult,
} from "./read";
export {
  createSqlFileReadRepository,
  decideFileRead,
  locateFileApplication,
  type FileApplicationLocation,
  type FileReadDecision,
  type FileReadSqlTransaction,
} from "./read-repository";
export {
  COMPONENT_BUNDLE_BUCKET,
  COMPONENT_BUNDLE_CONTENT_ADDRESS_LENGTH,
  COMPONENT_BUNDLE_CORS_ORIGIN,
  COMPONENT_BUNDLE_FILES_PREFIX,
  COMPONENT_BUNDLE_IMMUTABLE_CACHE_CONTROL,
  COMPONENT_BUNDLE_MANIFEST_PREFIX,
  COMPONENT_BUNDLE_MAXIMUM_OPERATION_SECONDS,
  ComponentBundleStorageError,
  componentBundleAddressDigest,
  componentBundleContentAddress,
  componentBundleFileDigest,
  componentBundleFileObjectPath,
  componentBundleManifestObjectPath,
  componentBundleManifestSchema,
  componentBundleMediaType,
  componentBundleRelativePathSchema,
  computeComponentBundleDigest,
  createComponentBundleStorageCredentialMinter,
  createSupabaseComponentBundleObjectStore,
  decodeComponentBundleManifest,
  encodeComponentBundleManifest,
  isSafeComponentBundlePath,
  publishComponentBundle,
  type ComponentBundleFile,
  type ComponentBundleManifest,
  type ComponentBundleObjectStore,
  type ComponentBundleRefusalReason,
  type ComponentBundleSigningKey,
  type ComponentBundleStorageOperation,
  type ComponentBundleStorageSigningConfig,
  type MintComponentBundleStorageCredential,
  type PublishedComponentBundle,
  type SupabaseComponentBundleObjectStoreConfig,
} from "./component-bundle-storage";
export {
  COMPONENT_BUNDLE_SERVING_PREFIX,
  componentBundleRefusalHttpStatus,
  componentBundleServingPath,
  serveComponentBundle,
  type RefusedComponentBundle,
  type ServeComponentBundleResult,
  type ServedComponentBundle,
} from "./component-bundle-serving";
export {
  COMPONENT_BOOTSTRAP_QUERY_PARAMETERS,
  COMPONENT_BOOTSTRAP_SERVING_PATH,
  COMPONENT_BOOTSTRAP_SERVING_SUBPATH,
  componentBootstrapContentSecurityPolicy,
  componentBootstrapServingUrl,
  parseComponentBootstrapTarget,
  renderComponentBootstrapDocument,
  type ComponentBootstrapDocument,
  type ComponentBootstrapTarget,
} from "./component-bootstrap-serving";
