import { moduleSourceDocumentSchema, type ModuleSourceDocument } from "@vortex/contracts";

// Content fields are editable through the standard create and update actions.
// Lifecycle fields (state and its timestamps) change only through the named
// actions below, so their preconditions cannot be bypassed by a direct edit.
const noticeEditableFields = ["title", "body"] as const;
const noticeAllFields = [...noticeEditableFields, "state", "published_at"];
const privacyEditableFields = ["subject", "request_kind", "details"] as const;
const privacyAllFields = [...privacyEditableFields, "state", "received_at", "closed_at"];
// The person and invitation system record types are read-only projections of
// protected Identity facts. They declare only safe, projected fields; their
// changes go through registered protected operations, never through the record.
// Row visibility stays inside each registered reader: people need the fixed
// accounts.read decision to see every account, and otherwise a live member sees
// only active accounts with their display name and state; invitations need the
// fixed invitations.read decision.
const personAllFields = [
  "organization_id",
  "revision",
  "display_name",
  "state",
  "language",
  "time_zone",
];
const invitationAllFields = [
  "organization_id",
  "revision",
  "invited_email",
  "state",
  "invited_at",
  "expires_at",
];

/**
 * Ordinary, application-contained records for the Organisation Administration
 * application. Notices and privacy request cases are ordinary administration
 * records in the owning organisation: they describe intent and published content
 * only. Organisation accounts and invitations are protected Identity and Access
 * facts: this module declares them as read-only system projection record types
 * whose typed fields project the registered protected views, so they are read
 * through the ordinary query path and never copied into application records.
 * Each change still goes through its registered protected operation, and the raw
 * invitation secret and its stored fingerprint are never projected. Role grants
 * stay in the IAM application; this module declares no grant control.
 */
export const organisationAdministrationModule: ModuleSourceDocument =
  moduleSourceDocumentSchema.parse({
    source_contract_version: "3.0.0",
    root_alias: "mod_organisation_administration",
    key: "vortex.organisation_administration",
    kind: "module",
    body: {
      name: "Organisation Administration",
      description:
        "Ordinary organisation notices and privacy request cases for an organisation administrator.",
      dependencies: [],
      record_types: [
        {
          id: "rt_organisation_notice",
          key: "organisation_notice",
          name: "Organisation notice",
          plural_name: "Organisation notices",
          title_field: "title",
          storage_contract_id: "srt_org_admin_notice",
          storage_scope: "application_contained",
          ownership_mode: "none",
          standard_actions: ["create", "read", "update", "soft_delete", "restore", "export"],
          custom_actions: ["act_record_notice", "act_withdraw_notice"],
          fields: [
            {
              id: "fld_notice_title",
              key: "title",
              label: "Title",
              required: true,
              unique: false,
              filterable: true,
              sortable: true,
              search_priority: "first",
              personal_data: "none",
              public_display: "refused",
              type: "text",
              settings: { max_length: 120 },
            },
            {
              id: "fld_notice_body",
              key: "body",
              label: "Notice text",
              required: false,
              unique: false,
              filterable: false,
              sortable: false,
              personal_data: "none",
              public_display: "refused",
              type: "long_text",
              settings: { max_length: 2_000 },
            },
            {
              id: "fld_notice_state",
              key: "state",
              label: "State",
              required: true,
              unique: false,
              filterable: true,
              sortable: true,
              personal_data: "none",
              public_display: "refused",
              type: "choice",
              settings: {
                options: [
                  { value: "draft", label: "Draft" },
                  { value: "published", label: "Published" },
                  { value: "withdrawn", label: "Withdrawn" },
                ],
              },
              default: "draft",
            },
            {
              id: "fld_notice_published_at",
              key: "published_at",
              label: "Published at",
              required: false,
              unique: false,
              filterable: false,
              sortable: true,
              personal_data: "none",
              public_display: "refused",
              type: "date_time",
              settings: { display_time_zone: "organisation" },
            },
          ],
          relationships: [],
        },
        {
          id: "rt_privacy_request_case",
          key: "privacy_request_case",
          name: "Privacy request case",
          plural_name: "Privacy request cases",
          title_field: "subject",
          storage_contract_id: "srt_org_admin_privacy_case",
          storage_scope: "application_contained",
          ownership_mode: "none",
          standard_actions: ["create", "read", "update", "soft_delete", "restore", "export"],
          custom_actions: [
            "act_record_privacy_request",
            "act_complete_privacy_request",
            "act_refuse_privacy_request",
          ],
          fields: [
            {
              id: "fld_case_subject",
              key: "subject",
              label: "Subject",
              required: true,
              unique: false,
              filterable: true,
              sortable: true,
              search_priority: "first",
              personal_data: "none",
              public_display: "refused",
              type: "text",
              settings: { max_length: 120 },
            },
            {
              id: "fld_case_request_kind",
              key: "request_kind",
              label: "Request kind",
              required: false,
              unique: false,
              filterable: true,
              sortable: false,
              personal_data: "none",
              public_display: "refused",
              type: "choice",
              settings: {
                options: [
                  { value: "access", label: "Access to personal data" },
                  { value: "correction", label: "Correction of personal data" },
                  { value: "deletion", label: "Deletion request" },
                  { value: "objection", label: "Objection to processing" },
                ],
              },
            },
            {
              id: "fld_case_details",
              key: "details",
              label: "Request details",
              required: true,
              unique: false,
              filterable: false,
              sortable: false,
              search_priority: "normal",
              personal_data: "personal",
              public_display: "refused",
              type: "long_text",
              settings: { max_length: 2_000 },
            },
            {
              id: "fld_case_state",
              key: "state",
              label: "State",
              required: true,
              unique: false,
              filterable: true,
              sortable: true,
              personal_data: "none",
              public_display: "refused",
              type: "choice",
              settings: {
                options: [
                  { value: "received", label: "Received" },
                  { value: "completed", label: "Completed" },
                  { value: "refused", label: "Refused" },
                ],
              },
              default: "received",
            },
            {
              id: "fld_case_received_at",
              key: "received_at",
              label: "Received at",
              required: false,
              unique: false,
              filterable: false,
              sortable: true,
              personal_data: "none",
              public_display: "refused",
              type: "date_time",
              settings: { display_time_zone: "organisation" },
            },
            {
              id: "fld_case_closed_at",
              key: "closed_at",
              label: "Closed at",
              required: false,
              unique: false,
              filterable: false,
              sortable: true,
              personal_data: "none",
              public_display: "refused",
              type: "date_time",
              settings: { display_time_zone: "organisation" },
            },
          ],
          relationships: [],
        },
        {
          id: "rt_organization_account",
          key: "person",
          name: "Person",
          plural_name: "People",
          title_field: "display_name",
          storage_contract_id: "srt_org_admin_person",
          storage_scope: "organisation_shared",
          ownership_mode: "none",
          standard_actions: ["read"],
          custom_actions: ["act_suspend_person", "act_reactivate_person", "act_close_person"],
          system_projection: {
            protected_view: "organization_accounts",
            organization_field: "organization_id",
            revision_field: "revision",
            filterable_fields: ["state"],
            sortable_fields: ["display_name", "state"],
          },
          fields: [
            {
              id: "fld_person_organization_id",
              key: "organization_id",
              label: "Organisation",
              required: true,
              unique: false,
              filterable: false,
              sortable: false,
              personal_data: "none",
              public_display: "refused",
              type: "text",
              settings: { max_length: 36 },
            },
            {
              id: "fld_person_revision",
              key: "revision",
              label: "Revision",
              required: true,
              unique: false,
              filterable: false,
              sortable: false,
              personal_data: "none",
              public_display: "refused",
              type: "whole_number",
              settings: {},
            },
            {
              id: "fld_person_display_name",
              key: "display_name",
              label: "Display name",
              required: false,
              unique: false,
              filterable: false,
              sortable: true,
              search_priority: "first",
              personal_data: "personal",
              public_display: "refused",
              type: "text",
              settings: { max_length: 120 },
            },
            {
              id: "fld_person_state",
              key: "state",
              label: "State",
              required: false,
              unique: false,
              filterable: true,
              sortable: true,
              personal_data: "none",
              public_display: "refused",
              type: "choice",
              settings: {
                options: [
                  { value: "active", label: "Active" },
                  { value: "suspended", label: "Suspended" },
                  { value: "closed", label: "Closed" },
                ],
              },
            },
            {
              id: "fld_person_language",
              key: "language",
              label: "Language",
              required: false,
              unique: false,
              filterable: false,
              sortable: false,
              personal_data: "none",
              public_display: "refused",
              type: "text",
              settings: { max_length: 35 },
            },
            {
              id: "fld_person_time_zone",
              key: "time_zone",
              label: "Time zone",
              required: false,
              unique: false,
              filterable: false,
              sortable: false,
              personal_data: "none",
              public_display: "refused",
              type: "text",
              settings: { max_length: 100 },
            },
          ],
          relationships: [],
        },
        {
          id: "rt_organization_invitation",
          key: "organization_invitation",
          name: "Organisation invitation",
          plural_name: "Organisation invitations",
          title_field: "invited_email",
          storage_contract_id: "srt_org_admin_invitation",
          storage_scope: "organisation_shared",
          ownership_mode: "none",
          standard_actions: ["read"],
          custom_actions: ["act_revoke_invitation"],
          system_projection: {
            protected_view: "organization_invitations",
            organization_field: "organization_id",
            revision_field: "revision",
            filterable_fields: ["state"],
            sortable_fields: ["invited_email", "state", "expires_at"],
          },
          fields: [
            {
              id: "fld_invitation_organization_id",
              key: "organization_id",
              label: "Organisation",
              required: true,
              unique: false,
              filterable: false,
              sortable: false,
              personal_data: "none",
              public_display: "refused",
              type: "text",
              settings: { max_length: 36 },
            },
            {
              id: "fld_invitation_revision",
              key: "revision",
              label: "Revision",
              required: true,
              unique: false,
              filterable: false,
              sortable: false,
              personal_data: "none",
              public_display: "refused",
              type: "whole_number",
              settings: {},
            },
            {
              id: "fld_invitation_email",
              key: "invited_email",
              label: "Invited email",
              required: false,
              unique: false,
              filterable: false,
              sortable: true,
              search_priority: "first",
              personal_data: "personal",
              public_display: "refused",
              type: "text",
              settings: { max_length: 320 },
            },
            {
              id: "fld_invitation_state",
              key: "state",
              label: "State",
              required: false,
              unique: false,
              filterable: true,
              sortable: true,
              personal_data: "none",
              public_display: "refused",
              type: "choice",
              settings: {
                options: [
                  { value: "pending", label: "Pending" },
                  { value: "accepted", label: "Accepted" },
                  { value: "revoked", label: "Revoked" },
                  { value: "expired", label: "Expired" },
                ],
              },
            },
            {
              id: "fld_invitation_invited_at",
              key: "invited_at",
              label: "Invited at",
              required: false,
              unique: false,
              filterable: false,
              sortable: false,
              personal_data: "none",
              public_display: "refused",
              type: "date_time",
              settings: { display_time_zone: "organisation" },
            },
            {
              id: "fld_invitation_expires_at",
              key: "expires_at",
              label: "Expires at",
              required: false,
              unique: false,
              filterable: false,
              sortable: true,
              personal_data: "none",
              public_display: "refused",
              type: "date_time",
              settings: { display_time_zone: "organisation" },
            },
          ],
          relationships: [],
        },
      ],
      permissions: [
        {
          id: "perm_notice_create",
          key: "vortex.organisation_administration.organisation_notice.create",
          label: "Create organisation notice",
          description: "Allows the standard create operation for organisation notices.",
          record_type: "organisation_notice",
          action_kind: "create",
          administrative: false,
          record_scope: { routes: [{ kind: "all_records" }] },
          field_policy: {
            readable_fields: noticeAllFields,
            changeable_fields: [...noticeEditableFields],
          },
        },
        {
          id: "perm_notice_read",
          key: "vortex.organisation_administration.organisation_notice.read",
          label: "Read organisation notices",
          description: "Allows the standard read operation for organisation notices.",
          record_type: "organisation_notice",
          action_kind: "read",
          administrative: false,
          record_scope: { routes: [{ kind: "all_records" }] },
          field_policy: { readable_fields: noticeAllFields, changeable_fields: [] },
        },
        {
          id: "perm_notice_update",
          key: "vortex.organisation_administration.organisation_notice.update",
          label: "Update organisation notice",
          description: "Allows the standard update operation for organisation notices.",
          record_type: "organisation_notice",
          action_kind: "update",
          administrative: false,
          record_scope: { routes: [{ kind: "all_records" }] },
          field_policy: {
            readable_fields: noticeAllFields,
            changeable_fields: [...noticeEditableFields],
          },
        },
        {
          id: "perm_notice_soft_delete",
          key: "vortex.organisation_administration.organisation_notice.soft_delete",
          label: "Remove organisation notice",
          description: "Allows the standard soft-delete operation for organisation notices.",
          record_type: "organisation_notice",
          action_kind: "delete",
          administrative: false,
          record_scope: { routes: [{ kind: "all_records" }] },
          field_policy: { readable_fields: [], changeable_fields: [] },
        },
        {
          id: "perm_notice_restore",
          key: "vortex.organisation_administration.organisation_notice.restore",
          label: "Restore organisation notice",
          description: "Allows the standard restore operation for organisation notices.",
          record_type: "organisation_notice",
          action_kind: "restore",
          administrative: false,
          record_scope: { routes: [{ kind: "all_records" }] },
          field_policy: { readable_fields: [], changeable_fields: [] },
        },
        {
          id: "perm_notice_export",
          key: "vortex.organisation_administration.organisation_notice.export",
          label: "Export organisation notice",
          description: "Allows the standard export operation for organisation notices.",
          record_type: "organisation_notice",
          action_kind: "export",
          administrative: false,
          record_scope: { routes: [{ kind: "all_records" }] },
          field_policy: { readable_fields: noticeAllFields, changeable_fields: [] },
        },
        {
          id: "perm_notice_record",
          key: "vortex.organisation_administration.organisation_notice.record_notice",
          label: "Record organisation notice",
          description: "Allows recording a draft organisation notice's text and publishing it.",
          record_type: "organisation_notice",
          action_kind: "named",
          named_action: "record_notice",
          administrative: false,
          record_scope: { routes: [{ kind: "all_records" }] },
          field_policy: {
            readable_fields: noticeAllFields,
            changeable_fields: noticeAllFields,
          },
        },
        {
          id: "perm_notice_withdraw",
          key: "vortex.organisation_administration.organisation_notice.withdraw",
          label: "Withdraw organisation notice",
          description: "Allows withdrawing a published organisation notice.",
          record_type: "organisation_notice",
          action_kind: "named",
          named_action: "withdraw",
          administrative: false,
          record_scope: { routes: [{ kind: "all_records" }] },
          field_policy: { readable_fields: ["state"], changeable_fields: ["state"] },
        },
        {
          id: "perm_privacy_create",
          key: "vortex.organisation_administration.privacy_request_case.create",
          label: "Create privacy request case",
          description: "Allows the standard create operation for privacy request cases.",
          record_type: "privacy_request_case",
          action_kind: "create",
          administrative: false,
          record_scope: { routes: [{ kind: "all_records" }] },
          field_policy: {
            readable_fields: privacyAllFields,
            changeable_fields: [...privacyEditableFields],
          },
        },
        {
          id: "perm_privacy_read",
          key: "vortex.organisation_administration.privacy_request_case.read",
          label: "Read privacy request case",
          description: "Allows the standard read operation for privacy request cases.",
          record_type: "privacy_request_case",
          action_kind: "read",
          administrative: false,
          record_scope: { routes: [{ kind: "all_records" }] },
          field_policy: { readable_fields: privacyAllFields, changeable_fields: [] },
        },
        {
          id: "perm_privacy_update",
          key: "vortex.organisation_administration.privacy_request_case.update",
          label: "Update privacy request case",
          description: "Allows the standard update operation for privacy request cases.",
          record_type: "privacy_request_case",
          action_kind: "update",
          administrative: false,
          record_scope: { routes: [{ kind: "all_records" }] },
          field_policy: {
            readable_fields: privacyAllFields,
            changeable_fields: [...privacyEditableFields],
          },
        },
        {
          id: "perm_privacy_soft_delete",
          key: "vortex.organisation_administration.privacy_request_case.soft_delete",
          label: "Remove privacy request case",
          description: "Allows the standard soft-delete operation for privacy request cases.",
          record_type: "privacy_request_case",
          action_kind: "delete",
          administrative: false,
          record_scope: { routes: [{ kind: "all_records" }] },
          field_policy: { readable_fields: [], changeable_fields: [] },
        },
        {
          id: "perm_privacy_restore",
          key: "vortex.organisation_administration.privacy_request_case.restore",
          label: "Restore privacy request case",
          description: "Allows the standard restore operation for privacy request cases.",
          record_type: "privacy_request_case",
          action_kind: "restore",
          administrative: false,
          record_scope: { routes: [{ kind: "all_records" }] },
          field_policy: { readable_fields: [], changeable_fields: [] },
        },
        {
          id: "perm_privacy_export",
          key: "vortex.organisation_administration.privacy_request_case.export",
          label: "Export privacy request case",
          description: "Allows the standard export operation for privacy request cases.",
          record_type: "privacy_request_case",
          action_kind: "export",
          administrative: false,
          record_scope: { routes: [{ kind: "all_records" }] },
          field_policy: { readable_fields: privacyAllFields, changeable_fields: [] },
        },
        {
          id: "perm_privacy_record",
          key: "vortex.organisation_administration.privacy_request_case.record_privacy_request",
          label: "Record privacy request case",
          description: "Allows recording a privacy request case and opening it as received.",
          record_type: "privacy_request_case",
          action_kind: "named",
          named_action: "record_privacy_request",
          administrative: false,
          record_scope: { routes: [{ kind: "all_records" }] },
          field_policy: {
            readable_fields: ["subject", "details", "state", "received_at"],
            changeable_fields: ["subject", "details", "state", "received_at"],
          },
        },
        {
          id: "perm_privacy_complete",
          key: "vortex.organisation_administration.privacy_request_case.complete",
          label: "Complete privacy request case",
          description: "Allows closing a received privacy request case as completed.",
          record_type: "privacy_request_case",
          action_kind: "named",
          named_action: "complete",
          administrative: false,
          record_scope: { routes: [{ kind: "all_records" }] },
          field_policy: {
            readable_fields: ["state", "closed_at"],
            changeable_fields: ["state", "closed_at"],
          },
        },
        {
          id: "perm_privacy_refuse",
          key: "vortex.organisation_administration.privacy_request_case.refuse",
          label: "Refuse privacy request case",
          description: "Allows closing a received privacy request case as refused.",
          record_type: "privacy_request_case",
          action_kind: "named",
          named_action: "refuse",
          administrative: false,
          record_scope: { routes: [{ kind: "all_records" }] },
          field_policy: {
            readable_fields: ["state", "closed_at"],
            changeable_fields: ["state", "closed_at"],
          },
        },
        {
          id: "perm_person_read",
          key: "vortex.organisation_administration.person.read",
          label: "Read people",
          description: "Allows reading the protected organisation-account projection as a system record.",
          record_type: "person",
          action_kind: "read",
          administrative: false,
          record_scope: { routes: [{ kind: "all_records" }] },
          field_policy: { readable_fields: personAllFields, changeable_fields: [] },
        },
        {
          id: "perm_person_suspend",
          key: "vortex.organisation_administration.person.suspend",
          label: "Suspend person",
          description: "Allows suspending an organisation account through its protected operation.",
          record_type: "person",
          action_kind: "named",
          named_action: "suspend",
          administrative: false,
          record_scope: { routes: [{ kind: "all_records" }] },
          field_policy: { readable_fields: ["state"], changeable_fields: [] },
        },
        {
          id: "perm_person_reactivate",
          key: "vortex.organisation_administration.person.reactivate",
          label: "Reactivate person",
          description: "Allows reactivating an organisation account through its protected operation.",
          record_type: "person",
          action_kind: "named",
          named_action: "reactivate",
          administrative: false,
          record_scope: { routes: [{ kind: "all_records" }] },
          field_policy: { readable_fields: ["state"], changeable_fields: [] },
        },
        {
          id: "perm_person_close",
          key: "vortex.organisation_administration.person.close",
          label: "Close person",
          description: "Allows closing an organisation account through its protected operation.",
          record_type: "person",
          action_kind: "named",
          named_action: "close",
          administrative: false,
          record_scope: { routes: [{ kind: "all_records" }] },
          field_policy: { readable_fields: ["state"], changeable_fields: [] },
        },
        {
          id: "perm_invitation_read",
          key: "vortex.organisation_administration.organization_invitation.read",
          label: "Read organisation invitations",
          description: "Allows reading the protected organisation-invitation projection as a system record.",
          record_type: "organization_invitation",
          action_kind: "read",
          administrative: false,
          record_scope: { routes: [{ kind: "all_records" }] },
          field_policy: { readable_fields: invitationAllFields, changeable_fields: [] },
        },
        {
          id: "perm_invitation_revoke",
          key: "vortex.organisation_administration.organization_invitation.revoke",
          label: "Revoke organisation invitation",
          description: "Allows revoking an organisation invitation through its protected operation.",
          record_type: "organization_invitation",
          action_kind: "named",
          named_action: "revoke",
          administrative: false,
          record_scope: { routes: [{ kind: "all_records" }] },
          field_policy: { readable_fields: ["state"], changeable_fields: [] },
        },
      ],
      actions: [
        {
          id: "act_record_notice",
          key: "vortex.organisation_administration.organisation_notice.record_notice",
          label: "Record organisation notice",
          record_type: "organisation_notice",
          permission: "vortex.organisation_administration.organisation_notice.record_notice",
          shareable: false,
          precondition: { field: "state", operator: "equals", value: "draft" },
          inputs: [
            {
              key: "title",
              label: "Title",
              required: true,
              type: "text",
              validation: { maximum_length: 120 },
            },
            {
              key: "body",
              label: "Notice text",
              required: true,
              type: "text",
              validation: { maximum_length: 2_000 },
            },
          ],
          effects: [
            { kind: "set_field", field: "title", value: { source: "input", input: "title" } },
            { kind: "set_field", field: "body", value: { source: "input", input: "body" } },
            { kind: "set_field", field: "state", value: { source: "literal", value: "published" } },
            {
              kind: "set_field",
              field: "published_at",
              value: { source: "current_time" },
            },
          ],
        },
        {
          id: "act_withdraw_notice",
          key: "vortex.organisation_administration.organisation_notice.withdraw",
          label: "Withdraw organisation notice",
          record_type: "organisation_notice",
          permission: "vortex.organisation_administration.organisation_notice.withdraw",
          shareable: false,
          precondition: { field: "state", operator: "equals", value: "published" },
          inputs: [],
          effects: [
            { kind: "set_field", field: "state", value: { source: "literal", value: "withdrawn" } },
          ],
        },
        {
          id: "act_record_privacy_request",
          key: "vortex.organisation_administration.privacy_request_case.record_privacy_request",
          label: "Record privacy request case",
          record_type: "privacy_request_case",
          permission: "vortex.organisation_administration.privacy_request_case.record_privacy_request",
          shareable: false,
          precondition: { field: "received_at", operator: "is_empty" },
          inputs: [
            {
              key: "subject",
              label: "Subject",
              required: true,
              type: "text",
              validation: { maximum_length: 120 },
            },
            {
              key: "details",
              label: "Request details",
              required: true,
              type: "text",
              validation: { maximum_length: 2_000 },
            },
          ],
          effects: [
            { kind: "set_field", field: "subject", value: { source: "input", input: "subject" } },
            { kind: "set_field", field: "details", value: { source: "input", input: "details" } },
            { kind: "set_field", field: "state", value: { source: "literal", value: "received" } },
            {
              kind: "set_field",
              field: "received_at",
              value: { source: "current_time" },
            },
          ],
        },
        {
          id: "act_complete_privacy_request",
          key: "vortex.organisation_administration.privacy_request_case.complete",
          label: "Complete privacy request case",
          record_type: "privacy_request_case",
          permission: "vortex.organisation_administration.privacy_request_case.complete",
          shareable: false,
          precondition: { field: "state", operator: "equals", value: "received" },
          inputs: [],
          effects: [
            { kind: "set_field", field: "state", value: { source: "literal", value: "completed" } },
            { kind: "set_field", field: "closed_at", value: { source: "current_time" } },
          ],
        },
        {
          id: "act_refuse_privacy_request",
          key: "vortex.organisation_administration.privacy_request_case.refuse",
          label: "Refuse privacy request case",
          record_type: "privacy_request_case",
          permission: "vortex.organisation_administration.privacy_request_case.refuse",
          shareable: false,
          precondition: { field: "state", operator: "equals", value: "received" },
          inputs: [],
          effects: [
            { kind: "set_field", field: "state", value: { source: "literal", value: "refused" } },
            { kind: "set_field", field: "closed_at", value: { source: "current_time" } },
          ],
        },
        {
          id: "act_suspend_person",
          key: "vortex.organisation_administration.person.suspend",
          label: "Suspend person",
          record_type: "person",
          permission: "vortex.organisation_administration.person.suspend",
          shareable: false,
          inputs: [],
          effects: [],
          protected_operation: "suspend_organization_account",
        },
        {
          id: "act_reactivate_person",
          key: "vortex.organisation_administration.person.reactivate",
          label: "Reactivate person",
          record_type: "person",
          permission: "vortex.organisation_administration.person.reactivate",
          shareable: false,
          inputs: [],
          effects: [],
          protected_operation: "reactivate_organization_account",
        },
        {
          id: "act_close_person",
          key: "vortex.organisation_administration.person.close",
          label: "Close person",
          record_type: "person",
          permission: "vortex.organisation_administration.person.close",
          shareable: false,
          inputs: [],
          effects: [],
          protected_operation: "close_organization_account",
        },
        {
          id: "act_revoke_invitation",
          key: "vortex.organisation_administration.organization_invitation.revoke",
          label: "Revoke organisation invitation",
          record_type: "organization_invitation",
          permission: "vortex.organisation_administration.organization_invitation.revoke",
          shareable: false,
          inputs: [],
          effects: [],
          protected_operation: "revoke_organization_invitation",
        },
      ],
      events: [],
      flows: [],
      extension_points: [],
      sharing_conditions: [],
      queries: [],
    },
  });
