import {
  modulePlatformPermissionDeclarationSchema,
  moduleSourceDocumentSchema,
  organizationRuntimeSettingsDateFormatOptions,
  organizationRuntimeSettingsNumberFormatOptions,
  type ModuleSourceDocument,
} from "@vortex/contracts";

/** Platform permissions protected by Organisation Administration's system records and operations. */
export const organisationAdministrationPlatformPermissions = [
  {
    pinnedPermissionId: "687d5649-62ee-43dd-b684-b8af3a5394c1",
    key: "platform.organization.permissions.read",
    label: "View available permissions",
    description:
      "View the selected organisation's registered permission catalogue without receiving use or assignment authority.",
    actionKind: "read",
    administrative: true,
    stewardMinimum: true,
  },
  {
    pinnedPermissionId: "ca5f56d4-5382-4bf8-9a91-fbfdc77642b2",
    key: "platform.organization.roles.read",
    label: "View roles",
    description: "View the selected organisation's live roles and registered application role templates.",
    actionKind: "read",
    administrative: true,
    stewardMinimum: true,
  },
  {
    pinnedPermissionId: "87c96495-c806-4692-9bc2-250ddb10613c",
    key: "platform.organization.roles.manage",
    label: "Manage roles",
    description: "Create, change or retire roles only within the actor's explicit delegated scope.",
    actionKind: "manage",
    administrative: true,
    stewardMinimum: true,
  },
  {
    pinnedPermissionId: "290ae49f-4cab-4159-9c20-6e664f07d50b",
    key: "platform.organization.groups.read",
    label: "View groups",
    description: "View the selected organisation's Groups and membership administration data.",
    actionKind: "read",
    administrative: true,
    stewardMinimum: true,
  },
  {
    pinnedPermissionId: "6185dc64-464b-4776-97dc-c64a6f299550",
    key: "platform.organization.groups.manage",
    label: "Manage groups",
    description:
      "Manage Groups and memberships subject to delegated scope and permanent-steward safeguards.",
    actionKind: "manage",
    administrative: true,
    stewardMinimum: true,
  },
  {
    pinnedPermissionId: "9901c0dc-8bac-45c7-be0b-3642cb839bb1",
    key: "platform.organization.assignments.read",
    label: "View access assignments",
    description:
      "View the selected organisation's role and delegation assignments and their effective scope.",
    actionKind: "read",
    administrative: true,
    stewardMinimum: true,
  },
  {
    pinnedPermissionId: "156d01f3-8f80-45fb-8fc8-b31c47dbb1df",
    key: "platform.organization.assignments.manage",
    label: "Manage access assignments",
    description:
      "Grant, change or revoke use and delegation assignments only within the actor's explicit delegated scope.",
    actionKind: "manage",
    administrative: true,
    stewardMinimum: true,
  },
  {
    pinnedPermissionId: "02c772e5-2921-4300-ad90-4f5772a7fa46",
    key: "platform.organization.accounts.read",
    label: "View organisation accounts",
    description: "View the selected organisation's safe account-administration information.",
    actionKind: "read",
    administrative: true,
    stewardMinimum: true,
  },
  {
    pinnedPermissionId: "630a980c-0ff5-40b1-a329-7326a2122395",
    key: "platform.organization.accounts.manage",
    label: "Manage organisation accounts",
    description:
      "Change organisation-account lifecycle through the protected operation without changing global identity or removing the final permanent steward.",
    actionKind: "manage",
    administrative: true,
    stewardMinimum: true,
  },
  {
    pinnedPermissionId: "9300e501-6d56-41b1-b203-3361dbace9bc",
    key: "platform.organization.invitations.read",
    label: "View invitations",
    description:
      "View safe invitation administration metadata without the raw invitation secret or its stored fingerprint.",
    actionKind: "read",
    administrative: true,
    stewardMinimum: true,
  },
  {
    pinnedPermissionId: "c2e03f58-debe-478e-b1e0-a4a8b8f1b9cb",
    key: "platform.organization.invitations.manage",
    label: "Manage invitations",
    description:
      "Create or revoke invitations through the protected operation; role assignment additionally requires the actor's assignment authority.",
    actionKind: "manage",
    administrative: true,
    stewardMinimum: true,
  },
  {
    pinnedPermissionId: "6dffcb0b-ded8-4cd5-acc8-c50f7d4269a5",
    key: "platform.organization.runtime_settings.read",
    label: "View organisation display settings",
    description:
      "View the organisation's default language, time zone, currency, date and number display settings.",
    actionKind: "read",
    administrative: true,
    stewardMinimum: true,
  },
  {
    pinnedPermissionId: "c658c254-2884-414a-9012-512c0cfe4b34",
    key: "platform.organization.runtime_settings.manage",
    label: "Manage organisation display settings",
    description:
      "Change the organisation's validated default display settings through the protected revision-checked operation.",
    actionKind: "manage",
    administrative: true,
    stewardMinimum: true,
  },
  {
    pinnedPermissionId: "7ecd3304-f16c-47d4-94db-0964980091ba",
    key: "platform.organization.applications.manage",
    label: "Manage applications",
    description:
      "Install, upgrade or detach exact application bindings in the selected organisation without receiving business-record use or role-assignment authority.",
    actionKind: "manage",
    administrative: true,
  },
].map((declaration) => modulePlatformPermissionDeclarationSchema.parse(declaration));

// Content fields are editable through the standard create and update actions.
// Lifecycle fields (state and its timestamps) change only through the named
// actions below, so their preconditions cannot be bypassed by a direct edit.
const noticeEditableFields = ["title", "body"] as const;
const noticeAllFields = [...noticeEditableFields, "state", "published_at"];
const privacyEditableFields = ["subject", "request_kind", "details"] as const;
const privacyAllFields = [...privacyEditableFields, "state", "received_at", "closed_at"];
// The permission record type projects protected Access catalogue entries.
const permissionAllFields = [
  "organization_id",
  "revision",
  "key",
  "label",
  "description",
  "owner_kind",
  "action_kind",
  "named_action",
  "administrative",
];
// Organisation settings remains the writable, extendable local system record.
const settingsAllFields = [
  "organization_id",
  "revision",
  "language",
  "time_zone",
  "currency",
  "date_format",
  "number_format",
  "default_application_root_id",
];
const installedApplicationAllFields = [
  "organization_id",
  "revision",
  "key",
  "release_revision",
  "is_default",
];
const applicationRoleTemplateAllFields = [
  "organization_id",
  "revision",
  "application_root_id",
  "source_role_id",
  "key",
  "label",
  "continuity_revision",
];

/**
 * Ordinary, application-contained records for the Organisation Administration
 * application. Notices and privacy request cases are ordinary administration
 * records in the owning organisation: they describe intent and published content
 * only. Shared people, invitation, group, role and delegation projections live in
 * System Directory and are read through its ordinary module queries. Protected
 * operations remain their only write path, and raw invitation secrets and stored
 * fingerprints are never projected. The writable, extendable organisation
 * settings record, installed-application projection and registered application
 * role-template projection remain declared here.
 */
export const organisationAdministrationModule: ModuleSourceDocument =
  moduleSourceDocumentSchema.parse({
    source_contract_version: "3.0.0",
    root_alias: "mod_organisation_administration",
    key: "vortex.organisation_administration",
    kind: "module",
    body: {
      name: "Organisation Administration",
      description:
        "Ordinary organisation notices and privacy request cases for an organisation administrator.",
      dependencies: [
        {
          dependency_key: "system_directory",
          module: "vortex.system_directory",
          version: { selection: "exact", version: "1.0.0" },
        },
      ],
      record_types: [
        {
          id: "rt_organisation_notice",
          key: "organisation_notice",
          name: "Organisation notice",
          plural_name: "Organisation notices",
          title_field: "title",
          storage_contract_id: "srt_org_admin_notice",
          storage_scope: "application_contained",
          ownership_mode: "none",
          standard_actions: ["create", "read", "update", "soft_delete", "restore", "export"],
          custom_actions: ["act_record_notice", "act_withdraw_notice"],
          fields: [
            {
              id: "fld_notice_title",
              key: "title",
              label: "Title",
              required: true,
              unique: false,
              filterable: true,
              sortable: true,
              search_priority: "first",
              personal_data: "none",
              public_display: "refused",
              type: "text",
              settings: { max_length: 120 },
            },
            {
              id: "fld_notice_body",
              key: "body",
              label: "Notice text",
              required: false,
              unique: false,
              filterable: false,
              sortable: false,
              personal_data: "none",
              public_display: "refused",
              type: "long_text",
              settings: { max_length: 2_000 },
            },
            {
              id: "fld_notice_state",
              key: "state",
              label: "State",
              required: true,
              unique: false,
              filterable: true,
              sortable: true,
              personal_data: "none",
              public_display: "refused",
              type: "choice",
              settings: {
                options: [
                  { value: "draft", label: "Draft" },
                  { value: "published", label: "Published" },
                  { value: "withdrawn", label: "Withdrawn" },
                ],
              },
              default: "draft",
            },
            {
              id: "fld_notice_published_at",
              key: "published_at",
              label: "Published at",
              required: false,
              unique: false,
              filterable: false,
              sortable: true,
              personal_data: "none",
              public_display: "refused",
              type: "date_time",
              settings: { display_time_zone: "organisation" },
            },
          ],
          relationships: [],
        },
        {
          id: "rt_privacy_request_case",
          key: "privacy_request_case",
          name: "Privacy request case",
          plural_name: "Privacy request cases",
          title_field: "subject",
          storage_contract_id: "srt_org_admin_privacy_case",
          storage_scope: "application_contained",
          ownership_mode: "none",
          standard_actions: ["create", "read", "update", "soft_delete", "restore", "export"],
          custom_actions: [
            "act_record_privacy_request",
            "act_complete_privacy_request",
            "act_refuse_privacy_request",
          ],
          fields: [
            {
              id: "fld_case_subject",
              key: "subject",
              label: "Subject",
              required: true,
              unique: false,
              filterable: true,
              sortable: true,
              search_priority: "first",
              personal_data: "none",
              public_display: "refused",
              type: "text",
              settings: { max_length: 120 },
            },
            {
              id: "fld_case_request_kind",
              key: "request_kind",
              label: "Request kind",
              required: false,
              unique: false,
              filterable: true,
              sortable: false,
              personal_data: "none",
              public_display: "refused",
              type: "choice",
              settings: {
                options: [
                  { value: "access", label: "Access to personal data" },
                  { value: "correction", label: "Correction of personal data" },
                  { value: "deletion", label: "Deletion request" },
                  { value: "objection", label: "Objection to processing" },
                ],
              },
            },
            {
              id: "fld_case_details",
              key: "details",
              label: "Request details",
              required: true,
              unique: false,
              filterable: false,
              sortable: false,
              search_priority: "normal",
              personal_data: "personal",
              public_display: "refused",
              type: "long_text",
              settings: { max_length: 2_000 },
            },
            {
              id: "fld_case_state",
              key: "state",
              label: "State",
              required: true,
              unique: false,
              filterable: true,
              sortable: true,
              personal_data: "none",
              public_display: "refused",
              type: "choice",
              settings: {
                options: [
                  { value: "received", label: "Received" },
                  { value: "completed", label: "Completed" },
                  { value: "refused", label: "Refused" },
                ],
              },
              default: "received",
            },
            {
              id: "fld_case_received_at",
              key: "received_at",
              label: "Received at",
              required: false,
              unique: false,
              filterable: false,
              sortable: true,
              personal_data: "none",
              public_display: "refused",
              type: "date_time",
              settings: { display_time_zone: "organisation" },
            },
            {
              id: "fld_case_closed_at",
              key: "closed_at",
              label: "Closed at",
              required: false,
              unique: false,
              filterable: false,
              sortable: true,
              personal_data: "none",
              public_display: "refused",
              type: "date_time",
              settings: { display_time_zone: "organisation" },
            },
          ],
          relationships: [],
        },
        {
          id: "rt_permission",
          key: "permission",
          name: "Permission",
          plural_name: "Permissions",
          title_field: "label",
          storage_contract_id: "srt_org_admin_permission",
          storage_scope: "organisation_shared",
          ownership_mode: "none",
          standard_actions: ["read"],
          custom_actions: [],
          system_projection: {
            protected_view: "permissions",
            organization_field: "organization_id",
            revision_field: "revision",
            filterable_fields: ["owner_kind", "action_kind", "administrative"],
            sortable_fields: ["key", "label", "administrative"],
          },
          fields: [
            {
              id: "fld_permission_organization_id",
              key: "organization_id",
              label: "Organisation",
              required: true,
              unique: false,
              filterable: false,
              sortable: false,
              personal_data: "none",
              public_display: "refused",
              type: "text",
              settings: { max_length: 36 },
            },
            {
              id: "fld_permission_revision",
              key: "revision",
              label: "Revision",
              required: true,
              unique: false,
              filterable: false,
              sortable: false,
              personal_data: "none",
              public_display: "refused",
              type: "whole_number",
              settings: {},
            },
            {
              id: "fld_permission_key",
              key: "key",
              label: "Key",
              required: false,
              unique: false,
              filterable: false,
              sortable: true,
              search_priority: "first",
              personal_data: "none",
              public_display: "refused",
              type: "text",
              settings: { max_length: 120 },
            },
            {
              id: "fld_permission_label",
              key: "label",
              label: "Label",
              required: false,
              unique: false,
              filterable: false,
              sortable: true,
              search_priority: "normal",
              personal_data: "none",
              public_display: "refused",
              type: "text",
              settings: { max_length: 60 },
            },
            {
              id: "fld_permission_description",
              key: "description",
              label: "Description",
              required: false,
              unique: false,
              filterable: false,
              sortable: false,
              personal_data: "none",
              public_display: "refused",
              type: "long_text",
              settings: { max_length: 1_000 },
            },
            {
              id: "fld_permission_owner_kind",
              key: "owner_kind",
              label: "Owner kind",
              required: false,
              unique: false,
              filterable: true,
              sortable: false,
              personal_data: "none",
              public_display: "refused",
              type: "choice",
              settings: {
                options: [
                  { value: "platform", label: "Platform" },
                  { value: "application", label: "Application" },
                  { value: "module", label: "Module" },
                ],
              },
            },
            {
              id: "fld_permission_action_kind",
              key: "action_kind",
              label: "Action kind",
              required: false,
              unique: false,
              filterable: true,
              sortable: false,
              personal_data: "none",
              public_display: "refused",
              type: "choice",
              settings: {
                options: [
                  { value: "create", label: "Create" },
                  { value: "read", label: "Read" },
                  { value: "update", label: "Update" },
                  { value: "delete", label: "Delete" },
                  { value: "restore", label: "Restore" },
                  { value: "export", label: "Export" },
                  { value: "share", label: "Share" },
                  { value: "manage", label: "Manage" },
                  { value: "transfer", label: "Transfer" },
                  { value: "named", label: "Named" },
                ],
              },
            },
            {
              id: "fld_permission_named_action",
              key: "named_action",
              label: "Named action",
              required: false,
              unique: false,
              filterable: false,
              sortable: false,
              personal_data: "none",
              public_display: "refused",
              type: "text",
              settings: { max_length: 40 },
            },
            {
              id: "fld_permission_administrative",
              key: "administrative",
              label: "Administrative",
              required: false,
              unique: false,
              filterable: true,
              sortable: true,
              personal_data: "none",
              public_display: "refused",
              type: "yes_no",
              settings: {},
            },
          ],
          relationships: [],
        },
        {
          id: "rt_organization_settings",
          key: "organization_settings",
          name: "Organisation settings",
          plural_name: "Organisation settings",
          title_field: "organization_id",
          storage_contract_id: "srt_org_admin_settings",
          storage_scope: "organisation_shared",
          ownership_mode: "none",
          standard_actions: ["read", "update"],
          custom_actions: [],
          system_projection: {
            protected_view: "organization_runtime_settings",
            organization_field: "organization_id",
            revision_field: "revision",
            filterable_fields: [],
            sortable_fields: ["language"],
          },
          fields: [
            {
              id: "fld_settings_organization_id",
              key: "organization_id",
              label: "Organisation",
              required: true,
              unique: false,
              filterable: false,
              sortable: false,
              personal_data: "none",
              public_display: "refused",
              type: "text",
              settings: { max_length: 36 },
            },
            {
              id: "fld_settings_revision",
              key: "revision",
              label: "Revision",
              required: true,
              unique: false,
              filterable: false,
              sortable: false,
              personal_data: "none",
              public_display: "refused",
              type: "whole_number",
              settings: {},
            },
            {
              id: "fld_settings_language",
              key: "language",
              label: "Language",
              required: false,
              unique: false,
              filterable: false,
              sortable: true,
              personal_data: "none",
              public_display: "refused",
              type: "text",
              settings: { max_length: 35 },
            },
            {
              id: "fld_settings_time_zone",
              key: "time_zone",
              label: "Time zone",
              required: false,
              unique: false,
              filterable: false,
              sortable: false,
              personal_data: "none",
              public_display: "refused",
              type: "text",
              settings: { max_length: 100 },
            },
            {
              id: "fld_settings_currency",
              key: "currency",
              label: "Currency",
              required: false,
              unique: false,
              filterable: false,
              sortable: false,
              personal_data: "none",
              public_display: "refused",
              type: "text",
              settings: { max_length: 3 },
            },
            {
              id: "fld_settings_date_format",
              key: "date_format",
              label: "Date format",
              required: false,
              unique: false,
              filterable: false,
              sortable: false,
              personal_data: "none",
              public_display: "refused",
              type: "choice",
              settings: {
                options: organizationRuntimeSettingsDateFormatOptions.map((option) => ({
                  ...option,
                })),
              },
            },
            {
              id: "fld_settings_number_format",
              key: "number_format",
              label: "Number format",
              required: false,
              unique: false,
              filterable: false,
              sortable: false,
              personal_data: "none",
              public_display: "refused",
              type: "choice",
              settings: {
                options: organizationRuntimeSettingsNumberFormatOptions.map((option) => ({
                  ...option,
                })),
              },
            },
            {
              id: "fld_settings_default_application_root_id",
              key: "default_application_root_id",
              label: "Default application",
              required: false,
              unique: false,
              filterable: false,
              sortable: false,
              personal_data: "none",
              public_display: "refused",
              type: "text",
              settings: { max_length: 36 },
            },
          ],
          relationships: [],
        },
        {
          id: "rt_installed_application",
          key: "installed_application",
          name: "Installed application",
          plural_name: "Installed applications",
          title_field: "key",
          storage_contract_id: "srt_org_admin_installed_application",
          storage_scope: "organisation_shared",
          ownership_mode: "none",
          standard_actions: ["read"],
          custom_actions: [],
          system_projection: {
            protected_view: "installed_applications",
            organization_field: "organization_id",
            revision_field: "revision",
            filterable_fields: ["is_default"],
            sortable_fields: ["key", "release_revision"],
          },
          fields: [
            {
              id: "fld_installed_application_organization_id",
              key: "organization_id",
              label: "Organisation",
              required: true,
              unique: false,
              filterable: false,
              sortable: false,
              personal_data: "none",
              public_display: "refused",
              type: "text",
              settings: { max_length: 36 },
            },
            {
              id: "fld_installed_application_revision",
              key: "revision",
              label: "Revision",
              required: true,
              unique: false,
              filterable: false,
              sortable: false,
              personal_data: "none",
              public_display: "refused",
              type: "whole_number",
              settings: {},
            },
            {
              id: "fld_installed_application_key",
              key: "key",
              label: "Key",
              required: false,
              unique: false,
              filterable: false,
              sortable: true,
              search_priority: "first",
              personal_data: "none",
              public_display: "refused",
              type: "text",
              settings: { max_length: 120 },
            },
            {
              id: "fld_installed_application_release_revision",
              key: "release_revision",
              label: "Installed release",
              required: false,
              unique: false,
              filterable: false,
              sortable: true,
              personal_data: "none",
              public_display: "refused",
              type: "whole_number",
              settings: {},
            },
            {
              id: "fld_installed_application_is_default",
              key: "is_default",
              label: "Default application",
              required: false,
              unique: false,
              filterable: true,
              sortable: false,
              personal_data: "none",
              public_display: "refused",
              type: "yes_no",
              settings: {},
            },
          ],
          relationships: [],
        },
        {
          id: "rt_application_role_template",
          key: "application_role_template",
          name: "Application role template",
          plural_name: "Application role templates",
          title_field: "label",
          storage_contract_id: "srt_org_admin_application_role_template",
          storage_scope: "organisation_shared",
          ownership_mode: "none",
          standard_actions: ["read"],
          custom_actions: [],
          system_projection: {
            protected_view: "application_role_templates",
            organization_field: "organization_id",
            revision_field: "revision",
            filterable_fields: ["application_root_id"],
            sortable_fields: ["key", "label"],
          },
          fields: [
            {
              id: "fld_application_role_template_organization_id",
              key: "organization_id",
              label: "Organisation",
              required: true,
              unique: false,
              filterable: false,
              sortable: false,
              personal_data: "none",
              public_display: "refused",
              type: "text",
              settings: { max_length: 36 },
            },
            {
              id: "fld_application_role_template_revision",
              key: "revision",
              label: "Registration revision",
              required: true,
              unique: false,
              filterable: false,
              sortable: false,
              personal_data: "none",
              public_display: "refused",
              type: "whole_number",
              settings: {},
            },
            {
              id: "fld_application_role_template_application_root_id",
              key: "application_root_id",
              label: "Application",
              required: true,
              unique: false,
              filterable: true,
              sortable: false,
              personal_data: "none",
              public_display: "refused",
              type: "text",
              settings: { max_length: 36 },
            },
            {
              id: "fld_application_role_template_source_role_id",
              key: "source_role_id",
              label: "Source role",
              required: true,
              unique: false,
              filterable: false,
              sortable: false,
              personal_data: "none",
              public_display: "refused",
              type: "text",
              settings: { max_length: 36 },
            },
            {
              id: "fld_application_role_template_key",
              key: "key",
              label: "Key",
              required: true,
              unique: false,
              filterable: false,
              sortable: true,
              personal_data: "none",
              public_display: "refused",
              type: "text",
              settings: { max_length: 120 },
            },
            {
              id: "fld_application_role_template_label",
              key: "label",
              label: "Label",
              required: true,
              unique: false,
              filterable: false,
              sortable: true,
              search_priority: "first",
              personal_data: "none",
              public_display: "refused",
              type: "text",
              settings: { max_length: 120 },
            },
            {
              id: "fld_application_role_template_continuity_revision",
              key: "continuity_revision",
              label: "Continuity revision",
              required: true,
              unique: false,
              filterable: false,
              sortable: false,
              personal_data: "none",
              public_display: "refused",
              type: "whole_number",
              settings: {},
            },
          ],
          relationships: [],
        },
      ],
      permissions: [
        {
          id: "perm_notice_create",
          key: "vortex.organisation_administration.organisation_notice.create",
          label: "Create organisation notice",
          description: "Allows the standard create operation for organisation notices.",
          record_type: "organisation_notice",
          action_kind: "create",
          administrative: false,
          record_scope: { routes: [{ kind: "all_records" }] },
          field_policy: {
            readable_fields: noticeAllFields,
            changeable_fields: [...noticeEditableFields],
          },
        },
        {
          id: "perm_notice_read",
          key: "vortex.organisation_administration.organisation_notice.read",
          label: "Read organisation notices",
          description: "Allows the standard read operation for organisation notices.",
          record_type: "organisation_notice",
          action_kind: "read",
          administrative: false,
          record_scope: { routes: [{ kind: "all_records" }] },
          field_policy: { readable_fields: noticeAllFields, changeable_fields: [] },
        },
        {
          id: "perm_notice_update",
          key: "vortex.organisation_administration.organisation_notice.update",
          label: "Update organisation notice",
          description: "Allows the standard update operation for organisation notices.",
          record_type: "organisation_notice",
          action_kind: "update",
          administrative: false,
          record_scope: { routes: [{ kind: "all_records" }] },
          field_policy: {
            readable_fields: noticeAllFields,
            changeable_fields: [...noticeEditableFields],
          },
        },
        {
          id: "perm_notice_soft_delete",
          key: "vortex.organisation_administration.organisation_notice.soft_delete",
          label: "Remove organisation notice",
          description: "Allows the standard soft-delete operation for organisation notices.",
          record_type: "organisation_notice",
          action_kind: "delete",
          administrative: false,
          record_scope: { routes: [{ kind: "all_records" }] },
          field_policy: { readable_fields: [], changeable_fields: [] },
        },
        {
          id: "perm_notice_restore",
          key: "vortex.organisation_administration.organisation_notice.restore",
          label: "Restore organisation notice",
          description: "Allows the standard restore operation for organisation notices.",
          record_type: "organisation_notice",
          action_kind: "restore",
          administrative: false,
          record_scope: { routes: [{ kind: "all_records" }] },
          field_policy: { readable_fields: [], changeable_fields: [] },
        },
        {
          id: "perm_notice_export",
          key: "vortex.organisation_administration.organisation_notice.export",
          label: "Export organisation notice",
          description: "Allows the standard export operation for organisation notices.",
          record_type: "organisation_notice",
          action_kind: "export",
          administrative: false,
          record_scope: { routes: [{ kind: "all_records" }] },
          field_policy: { readable_fields: noticeAllFields, changeable_fields: [] },
        },
        {
          id: "perm_notice_record",
          key: "vortex.organisation_administration.organisation_notice.record_notice",
          label: "Record organisation notice",
          description: "Allows recording a draft organisation notice's text and publishing it.",
          record_type: "organisation_notice",
          action_kind: "named",
          named_action: "record_notice",
          administrative: false,
          record_scope: { routes: [{ kind: "all_records" }] },
          field_policy: {
            readable_fields: noticeAllFields,
            changeable_fields: noticeAllFields,
          },
        },
        {
          id: "perm_notice_withdraw",
          key: "vortex.organisation_administration.organisation_notice.withdraw",
          label: "Withdraw organisation notice",
          description: "Allows withdrawing a published organisation notice.",
          record_type: "organisation_notice",
          action_kind: "named",
          named_action: "withdraw",
          administrative: false,
          record_scope: { routes: [{ kind: "all_records" }] },
          field_policy: { readable_fields: ["state"], changeable_fields: ["state"] },
        },
        {
          id: "perm_privacy_create",
          key: "vortex.organisation_administration.privacy_request_case.create",
          label: "Create privacy request case",
          description: "Allows the standard create operation for privacy request cases.",
          record_type: "privacy_request_case",
          action_kind: "create",
          administrative: false,
          record_scope: { routes: [{ kind: "all_records" }] },
          field_policy: {
            readable_fields: privacyAllFields,
            changeable_fields: [...privacyEditableFields],
          },
        },
        {
          id: "perm_privacy_read",
          key: "vortex.organisation_administration.privacy_request_case.read",
          label: "Read privacy request case",
          description: "Allows the standard read operation for privacy request cases.",
          record_type: "privacy_request_case",
          action_kind: "read",
          administrative: false,
          record_scope: { routes: [{ kind: "all_records" }] },
          field_policy: { readable_fields: privacyAllFields, changeable_fields: [] },
        },
        {
          id: "perm_privacy_update",
          key: "vortex.organisation_administration.privacy_request_case.update",
          label: "Update privacy request case",
          description: "Allows the standard update operation for privacy request cases.",
          record_type: "privacy_request_case",
          action_kind: "update",
          administrative: false,
          record_scope: { routes: [{ kind: "all_records" }] },
          field_policy: {
            readable_fields: privacyAllFields,
            changeable_fields: [...privacyEditableFields],
          },
        },
        {
          id: "perm_privacy_soft_delete",
          key: "vortex.organisation_administration.privacy_request_case.soft_delete",
          label: "Remove privacy request case",
          description: "Allows the standard soft-delete operation for privacy request cases.",
          record_type: "privacy_request_case",
          action_kind: "delete",
          administrative: false,
          record_scope: { routes: [{ kind: "all_records" }] },
          field_policy: { readable_fields: [], changeable_fields: [] },
        },
        {
          id: "perm_privacy_restore",
          key: "vortex.organisation_administration.privacy_request_case.restore",
          label: "Restore privacy request case",
          description: "Allows the standard restore operation for privacy request cases.",
          record_type: "privacy_request_case",
          action_kind: "restore",
          administrative: false,
          record_scope: { routes: [{ kind: "all_records" }] },
          field_policy: { readable_fields: [], changeable_fields: [] },
        },
        {
          id: "perm_privacy_export",
          key: "vortex.organisation_administration.privacy_request_case.export",
          label: "Export privacy request case",
          description: "Allows the standard export operation for privacy request cases.",
          record_type: "privacy_request_case",
          action_kind: "export",
          administrative: false,
          record_scope: { routes: [{ kind: "all_records" }] },
          field_policy: { readable_fields: privacyAllFields, changeable_fields: [] },
        },
        {
          id: "perm_privacy_record",
          key: "vortex.organisation_administration.privacy_request_case.record_privacy_request",
          label: "Record privacy request case",
          description: "Allows recording a privacy request case and opening it as received.",
          record_type: "privacy_request_case",
          action_kind: "named",
          named_action: "record_privacy_request",
          administrative: false,
          record_scope: { routes: [{ kind: "all_records" }] },
          field_policy: {
            readable_fields: ["subject", "details", "state", "received_at"],
            changeable_fields: ["subject", "details", "state", "received_at"],
          },
        },
        {
          id: "perm_privacy_complete",
          key: "vortex.organisation_administration.privacy_request_case.complete",
          label: "Complete privacy request case",
          description: "Allows closing a received privacy request case as completed.",
          record_type: "privacy_request_case",
          action_kind: "named",
          named_action: "complete",
          administrative: false,
          record_scope: { routes: [{ kind: "all_records" }] },
          field_policy: {
            readable_fields: ["state", "closed_at"],
            changeable_fields: ["state", "closed_at"],
          },
        },
        {
          id: "perm_privacy_refuse",
          key: "vortex.organisation_administration.privacy_request_case.refuse",
          label: "Refuse privacy request case",
          description: "Allows closing a received privacy request case as refused.",
          record_type: "privacy_request_case",
          action_kind: "named",
          named_action: "refuse",
          administrative: false,
          record_scope: { routes: [{ kind: "all_records" }] },
          field_policy: {
            readable_fields: ["state", "closed_at"],
            changeable_fields: ["state", "closed_at"],
          },
        },
        {
          id: "perm_permission_read",
          key: "vortex.organisation_administration.permission.read",
          label: "Read permissions",
          description:
            "Allows reading the protected permission projection as a system record.",
          record_type: "permission",
          action_kind: "read",
          administrative: false,
          record_scope: { routes: [{ kind: "all_records" }] },
          field_policy: { readable_fields: permissionAllFields, changeable_fields: [] },
        },
        {
          id: "perm_settings_read",
          key: "vortex.organisation_administration.organization_settings.read",
          label: "Read organisation settings",
          description:
            "Allows reading the protected organisation settings projection as a system record.",
          record_type: "organization_settings",
          action_kind: "read",
          administrative: false,
          record_scope: { routes: [{ kind: "all_records" }] },
          field_policy: { readable_fields: settingsAllFields, changeable_fields: [] },
        },
        {
          id: "perm_installed_application_read",
          key: "vortex.organisation_administration.installed_application.read",
          label: "Read installed applications",
          description:
            "Allows reading the protected installed-application projection as a system record.",
          record_type: "installed_application",
          action_kind: "read",
          administrative: false,
          record_scope: { routes: [{ kind: "all_records" }] },
          field_policy: {
            readable_fields: installedApplicationAllFields,
            changeable_fields: [],
          },
        },
        {
          id: "perm_application_role_template_read",
          key: "vortex.organisation_administration.application_role_template.read",
          label: "Read application role templates",
          description:
            "Allows reading the protected application-role-template projection as a system record.",
          record_type: "application_role_template",
          action_kind: "read",
          administrative: false,
          record_scope: { routes: [{ kind: "all_records" }] },
          field_policy: {
            readable_fields: applicationRoleTemplateAllFields,
            changeable_fields: [],
          },
        },
      ],
      actions: [
        {
          id: "act_record_notice",
          key: "vortex.organisation_administration.organisation_notice.record_notice",
          label: "Record organisation notice",
          record_type: "organisation_notice",
          permission: "vortex.organisation_administration.organisation_notice.record_notice",
          shareable: false,
          precondition: { field: "state", operator: "equals", value: "draft" },
          inputs: [
            {
              key: "title",
              label: "Title",
              required: true,
              type: "text",
              validation: { maximum_length: 120 },
            },
            {
              key: "body",
              label: "Notice text",
              required: true,
              type: "text",
              validation: { maximum_length: 2_000 },
            },
          ],
          tasks: [
            {
              id: "set_title",
              type: "record.set_fields",
              properties: { values: { title: "{{ inputs.title }}" } },
            },
            {
              id: "set_body",
              type: "record.set_fields",
              properties: { values: { body: "{{ inputs.body }}" } },
            },
            {
              id: "set_state",
              type: "record.set_fields",
              properties: { values: { state: { kind: "literal", literal: { type: "json", value: "published" } } } },
            },
            {
              id: "set_published_at",
              type: "record.set_fields",
              properties: { values: { published_at: "{{ execution.now }}" } },
            },
          ],
        },
        {
          id: "act_withdraw_notice",
          key: "vortex.organisation_administration.organisation_notice.withdraw",
          label: "Withdraw organisation notice",
          record_type: "organisation_notice",
          permission: "vortex.organisation_administration.organisation_notice.withdraw",
          shareable: false,
          precondition: { field: "state", operator: "equals", value: "published" },
          inputs: [],
          tasks: [
            {
              id: "set_state_withdrawn",
              type: "record.set_fields",
              properties: {
                values: { state: { kind: "literal", literal: { type: "json", value: "withdrawn" } } },
              },
            },
          ],
        },
        {
          id: "act_record_privacy_request",
          key: "vortex.organisation_administration.privacy_request_case.record_privacy_request",
          label: "Record privacy request case",
          record_type: "privacy_request_case",
          permission: "vortex.organisation_administration.privacy_request_case.record_privacy_request",
          shareable: false,
          precondition: { field: "received_at", operator: "is_empty" },
          inputs: [
            {
              key: "subject",
              label: "Subject",
              required: true,
              type: "text",
              validation: { maximum_length: 120 },
            },
            {
              key: "details",
              label: "Request details",
              required: true,
              type: "text",
              validation: { maximum_length: 2_000 },
            },
          ],
          tasks: [
            {
              id: "set_subject",
              type: "record.set_fields",
              properties: { values: { subject: "{{ inputs.subject }}" } },
            },
            {
              id: "set_details",
              type: "record.set_fields",
              properties: { values: { details: "{{ inputs.details }}" } },
            },
            {
              id: "set_state",
              type: "record.set_fields",
              properties: { values: { state: { kind: "literal", literal: { type: "json", value: "received" } } } },
            },
            {
              id: "set_received_at",
              type: "record.set_fields",
              properties: { values: { received_at: "{{ execution.now }}" } },
            },
          ],
        },
        {
          id: "act_complete_privacy_request",
          key: "vortex.organisation_administration.privacy_request_case.complete",
          label: "Complete privacy request case",
          record_type: "privacy_request_case",
          permission: "vortex.organisation_administration.privacy_request_case.complete",
          shareable: false,
          precondition: { field: "state", operator: "equals", value: "received" },
          inputs: [],
          tasks: [
            {
              id: "set_state",
              type: "record.set_fields",
              properties: { values: { state: { kind: "literal", literal: { type: "json", value: "completed" } } } },
            },
            {
              id: "set_closed_at",
              type: "record.set_fields",
              properties: { values: { closed_at: "{{ execution.now }}" } },
            },
          ],
        },
        {
          id: "act_refuse_privacy_request",
          key: "vortex.organisation_administration.privacy_request_case.refuse",
          label: "Refuse privacy request case",
          record_type: "privacy_request_case",
          permission: "vortex.organisation_administration.privacy_request_case.refuse",
          shareable: false,
          precondition: { field: "state", operator: "equals", value: "received" },
          inputs: [],
          tasks: [
            {
              id: "set_state",
              type: "record.set_fields",
              properties: { values: { state: { kind: "literal", literal: { type: "json", value: "refused" } } } },
            },
            {
              id: "set_closed_at",
              type: "record.set_fields",
              properties: { values: { closed_at: "{{ execution.now }}" } },
            },
          ],
        },
      ],
      events: [],
      flows: [],
      extension_points: [],
      sharing_conditions: [],
      queries: [
        {
          "id": "qry_organisation_notices",
          "key": "organisation_notices",
          "record_type": "organisation_notice",
          "inputs": [],
          "select": [
            "title",
            "body",
            "state",
            "published_at"
          ],
          "filter": null,
          "group_by": [],
          "aggregates": [],
          "sort": [
            {
              "field": "title",
              "direction": "ascending"
            }
          ],
          "page_size": 50,
          "relationship_hops": 0
        },
        {
          "id": "qry_privacy_request_cases",
          "key": "privacy_request_cases",
          "record_type": "privacy_request_case",
          "inputs": [],
          "select": [
            "subject",
            "request_kind",
            "state",
            "received_at",
            "closed_at"
          ],
          "filter": null,
          "group_by": [],
          "aggregates": [],
          "sort": [
            {
              "field": "received_at",
              "direction": "descending"
            }
          ],
          "page_size": 50,
          "relationship_hops": 0
        },
        {
          "id": "qry_organization_settings",
          "key": "organization_settings",
          "record_type": "organization_settings",
          "inputs": [],
          "select": [
            "language",
            "time_zone",
            "currency",
            "date_format",
            "number_format",
            "default_application_root_id"
          ],
          "filter": null,
          "group_by": [],
          "aggregates": [],
          "sort": [
            {
              "field": "language",
              "direction": "ascending"
            }
          ],
          "page_size": 50,
          "relationship_hops": 0
        },
        {
          "id": "qry_installed_applications",
          "key": "installed_applications",
          "record_type": "installed_application",
          "inputs": [],
          "select": [
            "key",
            "release_revision",
            "is_default"
          ],
          "filter": null,
          "group_by": [],
          "aggregates": [],
          "sort": [
            {
              "field": "key",
              "direction": "ascending"
            }
          ],
          "page_size": 50,
          "relationship_hops": 0
        },
        {
          id: "qry_application_role_templates",
          key: "application_role_templates",
          record_type: "application_role_template",
          inputs: [
            {
              key: "selected_application",
              label: "Selected application",
              required: true,
              type: "text",
              validation: { minimum_length: 36, maximum_length: 36 },
            },
          ],
          select: [
            "application_root_id",
            "source_role_id",
            "key",
            "label",
            "continuity_revision",
          ],
          filter: {
            field: "application_root_id",
            operator: "equals",
            parameter: "selected_application",
          },
          group_by: [],
          aggregates: [],
          sort: [{ field: "label", direction: "ascending" }],
          page_size: 50,
          relationship_hops: 0,
        },
      ],
    },
  });
