import { moduleSourceDocumentSchema, type ModuleSourceDocument } from "@vortex/contracts";

const noticeFields = ["title", "body", "state", "published_at"] as const;
const privacyFields = [
  "subject",
  "request_kind",
  "details",
  "state",
  "received_at",
  "closed_at",
] as const;

const noticeAllFields = [...noticeFields];
const privacyAllFields = [...privacyFields];

/**
 * Ordinary, application-contained records for the Organisation Administration
 * application. Notices and privacy request cases are ordinary administration
 * records in the owning organisation: they describe intent and published content
 * only. Organisation accounts, invitations and runtime settings are protected
 * Identity and Access facts; they are never copied into this module and their
 * displays bind to the protected read-model sources added by #908/#909. Role
 * grants stay in the IAM application; this module declares no grant control.
 */
export const organisationAdministrationModule: ModuleSourceDocument =
  moduleSourceDocumentSchema.parse({
    source_contract_version: "3.0.0",
    root_alias: "mod_organisation_administration",
    key: "vortex.organisation_administration",
    kind: "module",
    body: {
      name: "Organisation Administration",
      description:
        "Ordinary organisation notices and privacy request cases for an organisation administrator.",
      dependencies: [],
      record_types: [
        {
          id: "rt_organisation_notice",
          key: "organisation_notice",
          name: "Organisation notice",
          plural_name: "Organisation notices",
          title_field: "title",
          storage_contract_id: "srt_org_admin_notice",
          storage_scope: "application_contained",
          ownership_mode: "none",
          standard_actions: ["create", "read", "update", "soft_delete", "restore", "export"],
          custom_actions: ["act_record_notice"],
          fields: [
            {
              id: "fld_notice_title",
              key: "title",
              label: "Title",
              required: true,
              unique: false,
              filterable: true,
              sortable: true,
              search_priority: "first",
              personal_data: "none",
              public_display: "refused",
              type: "text",
              settings: { max_length: 120 },
            },
            {
              id: "fld_notice_body",
              key: "body",
              label: "Notice text",
              required: false,
              unique: false,
              filterable: false,
              sortable: false,
              personal_data: "none",
              public_display: "refused",
              type: "long_text",
              settings: { max_length: 2_000 },
            },
            {
              id: "fld_notice_state",
              key: "state",
              label: "State",
              required: true,
              unique: false,
              filterable: true,
              sortable: true,
              personal_data: "none",
              public_display: "refused",
              type: "choice",
              settings: {
                options: [
                  { value: "draft", label: "Draft" },
                  { value: "published", label: "Published" },
                  { value: "withdrawn", label: "Withdrawn" },
                ],
              },
              default: "draft",
            },
            {
              id: "fld_notice_published_at",
              key: "published_at",
              label: "Published at",
              required: false,
              unique: false,
              filterable: false,
              sortable: true,
              personal_data: "none",
              public_display: "refused",
              type: "date_time",
              settings: { display_time_zone: "organisation" },
            },
          ],
          relationships: [],
        },
        {
          id: "rt_privacy_request_case",
          key: "privacy_request_case",
          name: "Privacy request case",
          plural_name: "Privacy request cases",
          title_field: "subject",
          storage_contract_id: "srt_org_admin_privacy_case",
          storage_scope: "application_contained",
          ownership_mode: "none",
          standard_actions: ["create", "read", "update", "soft_delete", "restore", "export"],
          custom_actions: ["act_record_privacy_request", "act_close_privacy_request"],
          fields: [
            {
              id: "fld_case_subject",
              key: "subject",
              label: "Subject",
              required: true,
              unique: false,
              filterable: true,
              sortable: true,
              search_priority: "first",
              personal_data: "none",
              public_display: "refused",
              type: "text",
              settings: { max_length: 120 },
            },
            {
              id: "fld_case_request_kind",
              key: "request_kind",
              label: "Request kind",
              required: false,
              unique: false,
              filterable: true,
              sortable: false,
              personal_data: "none",
              public_display: "refused",
              type: "choice",
              settings: {
                options: [
                  { value: "access", label: "Access to personal data" },
                  { value: "correction", label: "Correction of personal data" },
                  { value: "deletion", label: "Deletion request" },
                  { value: "objection", label: "Objection to processing" },
                ],
              },
            },
            {
              id: "fld_case_details",
              key: "details",
              label: "Request details",
              required: true,
              unique: false,
              filterable: false,
              sortable: false,
              search_priority: "normal",
              personal_data: "personal",
              public_display: "refused",
              type: "long_text",
              settings: { max_length: 2_000 },
            },
            {
              id: "fld_case_state",
              key: "state",
              label: "State",
              required: true,
              unique: false,
              filterable: true,
              sortable: true,
              personal_data: "none",
              public_display: "refused",
              type: "choice",
              settings: {
                options: [
                  { value: "received", label: "Received" },
                  { value: "in_progress", label: "In progress" },
                  { value: "completed", label: "Completed" },
                  { value: "refused", label: "Refused" },
                ],
              },
              default: "received",
            },
            {
              id: "fld_case_received_at",
              key: "received_at",
              label: "Received at",
              required: false,
              unique: false,
              filterable: false,
              sortable: true,
              personal_data: "none",
              public_display: "refused",
              type: "date_time",
              settings: { display_time_zone: "organisation" },
            },
            {
              id: "fld_case_closed_at",
              key: "closed_at",
              label: "Closed at",
              required: false,
              unique: false,
              filterable: false,
              sortable: true,
              personal_data: "none",
              public_display: "refused",
              type: "date_time",
              settings: { display_time_zone: "organisation" },
            },
          ],
          relationships: [],
        },
      ],
      permissions: [
        {
          id: "perm_notice_create",
          key: "vortex.organisation_administration.organisation_notice.create",
          label: "Create organisation notice",
          description: "Allows the standard create operation for organisation notices.",
          record_type: "organisation_notice",
          action_kind: "create",
          administrative: false,
          record_scope: { routes: [{ kind: "all_records" }] },
          field_policy: {
            readable_fields: noticeAllFields,
            changeable_fields: noticeAllFields,
          },
        },
        {
          id: "perm_notice_read",
          key: "vortex.organisation_administration.organisation_notice.read",
          label: "Read organisation notices",
          description: "Allows the standard read operation for organisation notices.",
          record_type: "organisation_notice",
          action_kind: "read",
          administrative: false,
          record_scope: { routes: [{ kind: "all_records" }] },
          field_policy: { readable_fields: noticeAllFields, changeable_fields: [] },
        },
        {
          id: "perm_notice_update",
          key: "vortex.organisation_administration.organisation_notice.update",
          label: "Update organisation notice",
          description: "Allows the standard update operation for organisation notices.",
          record_type: "organisation_notice",
          action_kind: "update",
          administrative: false,
          record_scope: { routes: [{ kind: "all_records" }] },
          field_policy: {
            readable_fields: noticeAllFields,
            changeable_fields: noticeAllFields,
          },
        },
        {
          id: "perm_notice_soft_delete",
          key: "vortex.organisation_administration.organisation_notice.soft_delete",
          label: "Remove organisation notice",
          description: "Allows the standard soft-delete operation for organisation notices.",
          record_type: "organisation_notice",
          action_kind: "delete",
          administrative: false,
          record_scope: { routes: [{ kind: "all_records" }] },
          field_policy: { readable_fields: [], changeable_fields: [] },
        },
        {
          id: "perm_notice_restore",
          key: "vortex.organisation_administration.organisation_notice.restore",
          label: "Restore organisation notice",
          description: "Allows the standard restore operation for organisation notices.",
          record_type: "organisation_notice",
          action_kind: "restore",
          administrative: false,
          record_scope: { routes: [{ kind: "all_records" }] },
          field_policy: { readable_fields: [], changeable_fields: [] },
        },
        {
          id: "perm_notice_export",
          key: "vortex.organisation_administration.organisation_notice.export",
          label: "Export organisation notice",
          description: "Allows the standard export operation for organisation notices.",
          record_type: "organisation_notice",
          action_kind: "export",
          administrative: false,
          record_scope: { routes: [{ kind: "all_records" }] },
          field_policy: { readable_fields: noticeAllFields, changeable_fields: [] },
        },
        {
          id: "perm_notice_record",
          key: "vortex.organisation_administration.organisation_notice.record_notice",
          label: "Record organisation notice",
          description: "Allows recording a published organisation notice with its text.",
          record_type: "organisation_notice",
          action_kind: "named",
          named_action: "record_notice",
          administrative: false,
          record_scope: { routes: [{ kind: "all_records" }] },
          field_policy: {
            readable_fields: noticeAllFields,
            changeable_fields: noticeAllFields,
          },
        },
        {
          id: "perm_privacy_create",
          key: "vortex.organisation_administration.privacy_request_case.create",
          label: "Create privacy request case",
          description: "Allows the standard create operation for privacy request cases.",
          record_type: "privacy_request_case",
          action_kind: "create",
          administrative: false,
          record_scope: { routes: [{ kind: "all_records" }] },
          field_policy: {
            readable_fields: privacyAllFields,
            changeable_fields: privacyAllFields,
          },
        },
        {
          id: "perm_privacy_read",
          key: "vortex.organisation_administration.privacy_request_case.read",
          label: "Read privacy request case",
          description: "Allows the standard read operation for privacy request cases.",
          record_type: "privacy_request_case",
          action_kind: "read",
          administrative: false,
          record_scope: { routes: [{ kind: "all_records" }] },
          field_policy: { readable_fields: privacyAllFields, changeable_fields: [] },
        },
        {
          id: "perm_privacy_update",
          key: "vortex.organisation_administration.privacy_request_case.update",
          label: "Update privacy request case",
          description: "Allows the standard update operation for privacy request cases.",
          record_type: "privacy_request_case",
          action_kind: "update",
          administrative: false,
          record_scope: { routes: [{ kind: "all_records" }] },
          field_policy: {
            readable_fields: privacyAllFields,
            changeable_fields: privacyAllFields,
          },
        },
        {
          id: "perm_privacy_soft_delete",
          key: "vortex.organisation_administration.privacy_request_case.soft_delete",
          label: "Remove privacy request case",
          description: "Allows the standard soft-delete operation for privacy request cases.",
          record_type: "privacy_request_case",
          action_kind: "delete",
          administrative: false,
          record_scope: { routes: [{ kind: "all_records" }] },
          field_policy: { readable_fields: [], changeable_fields: [] },
        },
        {
          id: "perm_privacy_restore",
          key: "vortex.organisation_administration.privacy_request_case.restore",
          label: "Restore privacy request case",
          description: "Allows the standard restore operation for privacy request cases.",
          record_type: "privacy_request_case",
          action_kind: "restore",
          administrative: false,
          record_scope: { routes: [{ kind: "all_records" }] },
          field_policy: { readable_fields: [], changeable_fields: [] },
        },
        {
          id: "perm_privacy_export",
          key: "vortex.organisation_administration.privacy_request_case.export",
          label: "Export privacy request case",
          description: "Allows the standard export operation for privacy request cases.",
          record_type: "privacy_request_case",
          action_kind: "export",
          administrative: false,
          record_scope: { routes: [{ kind: "all_records" }] },
          field_policy: { readable_fields: privacyAllFields, changeable_fields: [] },
        },
        {
          id: "perm_privacy_record",
          key: "vortex.organisation_administration.privacy_request_case.record_privacy_request",
          label: "Record privacy request case",
          description: "Allows recording a privacy request case and opening it as received.",
          record_type: "privacy_request_case",
          action_kind: "named",
          named_action: "record_privacy_request",
          administrative: false,
          record_scope: { routes: [{ kind: "all_records" }] },
          field_policy: {
            readable_fields: ["subject", "details", "state", "received_at"],
            changeable_fields: ["subject", "details", "state", "received_at"],
          },
        },
        {
          id: "perm_privacy_close",
          key: "vortex.organisation_administration.privacy_request_case.close",
          label: "Close privacy request case",
          description: "Allows completing or refusing an open privacy request case.",
          record_type: "privacy_request_case",
          action_kind: "named",
          named_action: "close",
          administrative: false,
          record_scope: { routes: [{ kind: "all_records" }] },
          field_policy: {
            readable_fields: ["state", "closed_at"],
            changeable_fields: ["state", "closed_at"],
          },
        },
      ],
      actions: [
        {
          id: "act_record_notice",
          key: "vortex.organisation_administration.organisation_notice.record_notice",
          label: "Record organisation notice",
          record_type: "organisation_notice",
          permission: "vortex.organisation_administration.organisation_notice.record_notice",
          shareable: false,
          inputs: [
            {
              key: "title",
              label: "Title",
              required: true,
              type: "text",
              validation: { maximum_length: 120 },
            },
            {
              key: "body",
              label: "Notice text",
              required: true,
              type: "text",
              validation: { maximum_length: 2_000 },
            },
          ],
          effects: [
            { kind: "set_field", field: "title", value: { source: "input", input: "title" } },
            { kind: "set_field", field: "body", value: { source: "input", input: "body" } },
            { kind: "set_field", field: "state", value: { source: "literal", value: "published" } },
            {
              kind: "set_field",
              field: "published_at",
              value: { source: "current_time" },
            },
          ],
        },
        {
          id: "act_record_privacy_request",
          key: "vortex.organisation_administration.privacy_request_case.record_privacy_request",
          label: "Record privacy request case",
          record_type: "privacy_request_case",
          permission: "vortex.organisation_administration.privacy_request_case.record_privacy_request",
          shareable: false,
          inputs: [
            {
              key: "subject",
              label: "Subject",
              required: true,
              type: "text",
              validation: { maximum_length: 120 },
            },
            {
              key: "details",
              label: "Request details",
              required: true,
              type: "text",
              validation: { maximum_length: 2_000 },
            },
          ],
          effects: [
            { kind: "set_field", field: "subject", value: { source: "input", input: "subject" } },
            { kind: "set_field", field: "details", value: { source: "input", input: "details" } },
            { kind: "set_field", field: "state", value: { source: "literal", value: "received" } },
            {
              kind: "set_field",
              field: "received_at",
              value: { source: "current_time" },
            },
          ],
        },
        {
          id: "act_close_privacy_request",
          key: "vortex.organisation_administration.privacy_request_case.close",
          label: "Close privacy request case",
          record_type: "privacy_request_case",
          permission: "vortex.organisation_administration.privacy_request_case.close",
          shareable: false,
          inputs: [],
          effects: [
            { kind: "set_field", field: "state", value: { source: "literal", value: "completed" } },
            { kind: "set_field", field: "closed_at", value: { source: "current_time" } },
          ],
        },
      ],
      events: [],
      rules: [],
      extension_points: [],
      sharing_conditions: [],
      queries: [],
    },
  });
