import "server-only";

export {
  protectedQueryCommandSchema,
  protectedQueryRowSchema,
  protectedQueryRefusalReasonCodes,
  protectedQueryRefusalSchema,
  protectedQueryPageSchema,
  protectedQueryResultSchema,
  type ProtectedQueryCommand,
  type ProtectedQueryRow,
  type ProtectedQueryRefusalReasonCode,
  type ProtectedQueryRefusal,
  type ProtectedQueryPage,
  type ProtectedQueryResult,
} from "./protected-query-contracts";

export {
  createProtectedQueryService,
  type ProtectedQueryServiceDependencies,
} from "./protected-query-service";

export type { QueryContinuationKey } from "./continuation-token";

export {
  arrangementSourcePlanIdentitySchema,
  arrangementDatasetSchema,
  aggregateRefusalReasonCodes,
  aggregateRefusalSchema,
  aggregateValueSchema,
  aggregateSuccessSchema,
  aggregateComputationResultSchema,
  aggregateDescriptorSchema,
  arrangementRefusalReasonCodes,
  arrangementRefusalSchema,
  tableGroupSchema,
  flatTableArrangementResultSchema,
  groupedTableArrangementResultSchema,
  tableArrangementResultSchema,
  tableArrangementDescriptorSchema,
  choiceOptionSchema,
  boardColumnSchema,
  boardArrangementResultSchema,
  boardArrangementDescriptorSchema,
  calendarItemSchema,
  calendarArrangementResultSchema,
  calendarArrangementDescriptorSchema,
  summaryGroupSchema,
  flatSummaryArrangementResultSchema,
  groupedSummaryArrangementResultSchema,
  summaryArrangementResultSchema,
  summaryArrangementDescriptorSchema,
  arrangementDescriptorSchema,
  arrangementCompletedResultSchema,
  arrangementResultSchema,
  arrangementCommandSchema,
  type ArrangementSourcePlanIdentity,
  type ArrangementDataset,
  type AggregateRefusalReasonCode,
  type AggregateRefusal,
  type AggregateValue,
  type AggregateSuccess,
  type AggregateComputationResult,
  type AggregateDescriptor,
  type ArrangementRefusalReasonCode,
  type ArrangementRefusal,
  type TableGroup,
  type FlatTableArrangementResult,
  type GroupedTableArrangementResult,
  type TableArrangementResult,
  type TableArrangementDescriptor,
  type ChoiceOption,
  type BoardColumn,
  type BoardArrangementResult,
  type BoardArrangementDescriptor,
  type CalendarItem,
  type CalendarArrangementResult,
  type CalendarArrangementDescriptor,
  type SummaryGroup,
  type FlatSummaryArrangementResult,
  type GroupedSummaryArrangementResult,
  type SummaryArrangementResult,
  type SummaryArrangementDescriptor,
  type ArrangementDescriptor,
  type ArrangementCompletedResult,
  type ArrangementResult,
  type ArrangementCommand,
} from "./arrangement-contracts";

export {
  formatBigIntDecimal,
  addExactDecimals,
  sumExactDecimals,
  divideExactDecimal,
  computeFieldAggregate,
  computeAggregates,
} from "./exact-aggregation";

export {
  projectDeclaredFields,
  compareGroupValues,
  arrangeTable,
  arrangeBoard,
  arrangeCalendar,
  arrangeSummary,
  arrangeDataset,
} from "./arrangements";

export const QueryService = Object.freeze({
  key: "query",
  boundary: "@vortex/query",
});
