import "server-only";

export {
  createStoredApplicationPermissionSource,
  type StoredApplicationPermissionSourceDependencies,
  type StoredApplicationPermissionSourceEvidence,
} from "./stored-application-permission-source";
export {
  applicationRoleTemplatePreparationErrorCodes,
  ApplicationRoleTemplatePreparationError,
  createApplicationRoleTemplateAdapter,
  prepareApplicationRoleTemplatesForHumanRequest,
  verifyPreparedApplicationRoleTemplates,
  type ApplicationRoleTemplateAdapterDependencies,
  type ApplicationRoleTemplatePreparationErrorCode,
  type PrepareApplicationRoleRegistrationCandidateCommand,
  type PrepareCurrentApplicationRoleTemplatesCommand,
} from "./application-role-template-adapter";
export {
  acceptOrganizationInvitation,
  AccessVersionError,
  accessVersionErrorCodes,
  createAccessVersionStore,
  type AccessVersionErrorCode,
} from "./access-version";
export {
  createHumanOrganizationRequestService,
  type HumanOrganizationRequestDependencies,
  type HumanOrganizationRequestResult,
} from "./human-organization-request";
export {
  createVortexSuperAdministratorAdministrationService,
  type VortexSuperAdministratorAdministrationDependencies,
} from "./super-administrator-administration";
export {
  createOrganizationRuntimeSettingsAdministrationService,
  readCurrentOrganizationDefaultApplicationAfterAuthorization,
  readCurrentOrganizationRuntimeSettingsAfterAuthorization,
  type OrganizationDefaultApplication,
  type OrganizationRuntimeSettingsAdministrationDependencies,
  type SetOrganizationDefaultApplicationCommand,
  type UpdateOrganizationRuntimeSettingsCommand,
} from "./organization-runtime-settings-administration";
export {
  createOrganizationLocalAdministrationService,
  type OrganizationLocalAdministrationDependencies,
} from "./organization-local-administration";
export {
  runOrganizationAccessOperation,
  type OrganizationAccessOperationResult,
} from "./organization-access-decision";
export {
  runOrganizationRecordAccessOperation,
  type FixedOrganizationRecordAccessAdapter,
  type OrganizationRecordAccessOperationResult,
} from "./organization-record-access-operation";
export {
  createOrganizationDirectRecordShareService,
  type FixedOrganizationDirectRecordShareAdapter,
  type OrganizationDirectRecordShareDependencies,
} from "./organization-direct-record-share";
export {
  createRecordShareGrantService,
  type RecordShareGrantDependencies,
  type RecordShareGrantState,
} from "./record-share-grants";
export {
  createOrganizationAccessAdministrationService,
  type OrganizationAccessAdministrationDependencies,
} from "./organization-access-administration";
export { fingerprintPermissionMeaning } from "./permission-fingerprints";
export {
  organizationDelegationScopeEvidenceErrorCodes,
  OrganizationDelegationScopeEvidenceError,
  prepareOrganizationDelegationScope,
  verifyPreparedOrganizationDelegationScope,
  type OrganizationDelegationScopeEvidenceErrorCode,
} from "./organization-delegation-scope-evidence";
export {
  organizationRoleChangeEvidenceErrorCodes,
  OrganizationRoleChangeEvidenceError,
  prepareOrganizationRoleChangeEvidence,
  verifyPreparedOrganizationRoleChangeEvidence,
  type OrganizationRoleChangeEvidenceErrorCode,
} from "./organization-role-change-evidence";
export {
  createPermissionRegistryDefinitionAdapter,
  PermissionRegistryPreparationError,
  permissionRegistryPreparationErrorCodes,
  prepareApplicationPermissionRegistrationForHumanRequest,
  prepareApplicationPermissionRegistrationFromReleaseSet,
  verifyPreparedApplicationPermissionRegistration,
  type PermissionRegistryDefinitionSetReader,
  type PermissionRegistryPreparationErrorCode,
  type PrepareApplicationPermissionRegistrationCommand,
} from "./permission-registry-definition-adapter";
export {
  BuilderAuthorityError,
  requireBuilderAuthority,
  type BuilderAuthority,
  type BuilderConferredPermission,
  type BuilderOperation,
  type BuilderTargetFacts,
} from "@vortex/definition";
export {
  createBuilderAuthority,
  type BuilderAuthorityDependencies,
  type BuilderTargetFactsReader,
} from "./builder-authority";
export {
  createPermissionRegistryPrivateRepository,
  PermissionRegistryRepositoryError,
  permissionRegistryRepositoryErrorCodes,
  type PermissionRegistryPrivateRepository,
  type PermissionRegistryRepositoryErrorCode,
} from "./permission-registry-repository";
export {
  capabilityAllocationCommandSchema,
  capabilityAllocationResultSchema,
  capabilityAllocationRevocationCommandSchema,
  capabilityAllocationRevocationResultSchema,
  capabilityCeilingCommandSchema,
  capabilityCeilingResultSchema,
  capabilityCeilingRevocationCommandSchema,
  capabilityCeilingRevocationResultSchema,
  capabilityLimitSourceSchema,
  capabilityPolicyAppliedScopeSchema,
  capabilityPolicyDefinitionCommandSchema,
  capabilityPolicyDefinitionSchema,
  capabilityPolicyMutationResultSchema,
  capabilityPolicyQuantitySchema,
  capabilityPolicyRefusalCodes,
  capabilityPolicyScopeSchema,
  capabilityPolicySubjectSchema,
  createCapabilityPolicyPlatformOperatorService,
  effectiveCapabilityPolicyRequestSchema,
  effectiveCapabilityPolicySchema,
  resolveEffectiveCapabilityPolicy,
  resolveEffectiveCapabilityPolicyForEntitlement,
  revokeCapabilityLimitAllocation,
  setCapabilityLimitAllocation,
  type CapabilityAllocationCommand,
  type CapabilityAllocationResult,
  type CapabilityAllocationRevocationCommand,
  type CapabilityAllocationRevocationResult,
  type CapabilityCeilingCommand,
  type CapabilityCeilingResult,
  type CapabilityCeilingRevocationCommand,
  type CapabilityCeilingRevocationResult,
  type CapabilityLimitSource,
  type CapabilityPolicyAppliedScope,
  type CapabilityPolicyDefinition,
  type CapabilityPolicyDefinitionCommand,
  type CapabilityPolicyMutationResult,
  type CapabilityPolicyPlatformOperatorDependencies,
  type CapabilityPolicyPlatformOperatorService,
  type CapabilityPolicyRefusalCode,
  type CapabilityPolicySubject,
  type EffectiveCapabilityPolicy,
  type EffectiveCapabilityPolicyRequest,
} from "./capability-policy";
export {
  capabilityBalanceRecordSchema,
  capabilityBalanceSchema,
  capabilityConsumptionResultSchema,
  capabilityPolicyEvidenceSchema,
  capabilityReleaseResultSchema,
  capabilityReservationResultSchema,
  consumeCapabilityReservation,
  consumeCapabilityReservationCommandSchema,
  consumeReservation,
  expireStaleCapabilityReservations,
  expireStaleCapabilityReservationsCommandSchema,
  expireStaleCapabilityReservationsResultSchema,
  readCapabilityBalance,
  readCapabilityBalanceRequestSchema,
  releaseCapabilityReservation,
  releaseCapabilityReservationCommandSchema,
  releaseReservation,
  reserveCapabilityCommandSchema,
  reserveCapabilityQuantity,
  type CapabilityBalance,
  type CapabilityBalanceRecord,
  type CapabilityConsumptionResult,
  type CapabilityPolicyEvidence,
  type CapabilityReleaseResult,
  type CapabilityReservationResult,
  type ConsumeCapabilityReservationCommand,
  type ExpireStaleCapabilityReservationsCommand,
  type ExpireStaleCapabilityReservationsResult,
  type ReadCapabilityBalanceRequest,
  type ReleaseCapabilityReservationCommand,
  type ReserveCapabilityCommand,
} from "./capability-reservation";
export {
  flowExecutionBindingAdministratorAuthoritySchema,
  flowExecutionBindingErrorCodes,
  FlowExecutionBindingError,
  flowExecutionBindingMutationResultSchema,
  flowExecutionBindingReadResultSchema,
  readFlowExecutionBinding,
  readFlowExecutionBindingCommandSchema,
  registerFlowExecutionBinding,
  registerFlowExecutionBindingCommandSchema,
  revokeFlowExecutionBinding,
  revokeFlowExecutionBindingCommandSchema,
  type FlowExecutionBindingAdministratorAuthority,
  type FlowExecutionBindingErrorCode,
  type FlowExecutionBindingMutationResult,
  type FlowExecutionBindingReadResult,
  type ReadFlowExecutionBindingCommand,
  type RegisterFlowExecutionBindingCommand,
  type RevokeFlowExecutionBindingCommand,
} from "./flow-execution-bindings";
export {
  flowRunAsPrincipalAdministratorAuthoritySchema,
  flowRunAsPrincipalErrorCodes,
  FlowRunAsPrincipalError,
  flowRunAsPrincipalMutationResultSchema,
  flowRunAsPrincipalReadResultSchema,
  readFlowRunAsPrincipalForRun,
  readFlowRunAsPrincipalForRunCommandSchema,
  registerFlowRunAsPrincipal,
  registerFlowRunAsPrincipalCommandSchema,
  revokeFlowRunAsPrincipal,
  revokeFlowRunAsPrincipalCommandSchema,
  type FlowRunAsPrincipalAdministratorAuthority,
  type FlowRunAsPrincipalErrorCode,
  type FlowRunAsPrincipalMutationResult,
  type FlowRunAsPrincipalReadResult,
  type ReadFlowRunAsPrincipalForRunCommand,
  type RegisterFlowRunAsPrincipalCommand,
  type RevokeFlowRunAsPrincipalCommand,
} from "./flow-run-as-principals";
export {
  meteringEventErrorCodes,
  meteringEventRecordResultSchema,
  recordMeteringEvent,
  type MeteringEvent,
  type MeteringEventErrorCode,
  type MeteringEventRecordResult,
  type RecordMeteringEventCommand,
} from "./metering-events";
export {
  flowEffectiveActorDelegationUseSchema,
  flowEffectiveActorErrorCodes,
  FlowEffectiveActorError,
  flowEffectiveActorIdentitySchema,
  flowEffectiveActorNodeRequestSchema,
  flowEffectiveActorPurposeSchema,
  flowEffectiveActorRefusalReasonSchema,
  flowEffectiveActorRequestSchema,
  flowEffectiveActorResolutionSchema,
  flowEffectiveActorRunActorSchema,
  flowEffectiveActorStateSchema,
  openFlowEffectiveActorTransaction,
  readFlowEffectiveActorCurrentAuthority,
  resolveFlowEffectiveActor,
  type FlowEffectiveActorAuthorityReader,
  type FlowEffectiveActorCurrentAuthority,
  type FlowEffectiveActorDelegationUse,
  type FlowEffectiveActorDependencies,
  type FlowEffectiveActorEffectiveResolution,
  type FlowEffectiveActorErrorCode,
  type FlowEffectiveActorIdentity,
  type FlowEffectiveActorNodeRequest,
  type FlowEffectiveActorPurpose,
  type FlowEffectiveActorRefusalReason,
  type FlowEffectiveActorRequest,
  type FlowEffectiveActorResolution,
  type FlowEffectiveActorRunActor,
  type FlowEffectiveActorScopeResolver,
  type FlowEffectiveActorState,
  type FlowEffectiveActorTransactionAccess,
  type FlowEffectiveActorTransactionDependencies,
  type FlowEffectiveActorTransactionRunner,
} from "./flow-effective-actor";

export {
  createDurableActorRequestService,
  verifiedDurableActorContextSchema,
  type DurableActorRequestDependencies,
  type DurableActorRequestResult,
  type DurableActorRequestScope,
  type VerifiedDurableActorRequestContext,
} from "./durable-actor-request";

export const AccessService = Object.freeze({
  key: "access",
  boundary: "@vortex/access",
});
