import "server-only";

import {
  unavailableError,
  sameId,
  organizationRecordAccessDecisionSchema,
  organizationRecordAccessDeclarationSchema,
  recordIdSchema,
  safeOrganizationAccessRefusal,
  selectedOrganizationScopeSchema,
  type OrganizationRecordAccessDecision,
  type OrganizationRecordAccessDeclaration,
  type RecordId,
  type SafeOrganizationAccessRefusal,
  type SelectedOrganizationScope,
} from "@vortex/contracts";
import type { RequestDatabaseTransaction } from "@vortex/db";
import type { DatabaseRow } from "@vortex/db";

const unavailableCode = "ORGANIZATION_RECORD_ACCESS_DECISION_UNAVAILABLE";

type AllowedOrganizationRecordAccessDecision = Extract<
  OrganizationRecordAccessDecision,
  Readonly<{ outcome: "allowed" }>
>;

export type OrganizationRecordAccessOperationResult<Result> =
  Readonly<{ outcome: "completed"; value: Result }> | SafeOrganizationAccessRefusal;

/**
 * Server-owned, operation-specific binding. Implementations fix their SQL
 * function, declaration and physical record source in code generated by #45;
 * request data supplies only the normal command consumed by that operation.
 */
export interface FixedOrganizationRecordAccessAdapter<Command> {
  readonly declaration: OrganizationRecordAccessDeclaration;
  recordId(command: Command): RecordId;
  evaluate(
    transaction: RequestDatabaseTransaction,
    command: Command,
  ): Promise<OrganizationRecordAccessDecision>;
}

type CurrentEvidenceRow = DatabaseRow & {
  organization_id: unknown;
  organization_account_id: unknown;
  application_root_id: unknown;
  access_version: unknown;
  correlation_id: unknown;
  expires_at: unknown;
  observed_at: unknown;
};

const timestamp = (value: unknown): string | undefined => {
  const candidate = value instanceof Date ? value.toISOString() : value;
  return typeof candidate === "string" && Number.isFinite(Date.parse(candidate))
    ? candidate
    : undefined;
};

const revision = (value: unknown): number | undefined => {
  const candidate =
    typeof value === "bigint"
      ? Number(value)
      : typeof value === "string" && /^[1-9][0-9]*$/.test(value)
        ? Number(value)
        : value;
  return typeof candidate === "number" && Number.isSafeInteger(candidate) && candidate >= 1
    ? candidate
    : undefined;
};

const sameAction = (
  decision: OrganizationRecordAccessDecision["action"],
  declaration: OrganizationRecordAccessDeclaration["action"],
): boolean =>
  decision.actionKind === declaration.actionKind &&
  decision.namedAction === declaration.namedAction;

const sameRecordBinding = (
  decision: OrganizationRecordAccessDecision["recordBinding"],
  declaration: OrganizationRecordAccessDeclaration["recordBinding"],
): boolean =>
  sameId(decision.moduleRootId, declaration.moduleRootId) &&
  sameId(decision.recordTypeId, declaration.recordTypeId) &&
  sameId(decision.storageContractId, declaration.storageContractId) &&
  decision.storageScope === declaration.storageScope;

const samePermission = (
  left: OrganizationRecordAccessDeclaration["requiredPermissions"][number],
  right: OrganizationRecordAccessDeclaration["requiredPermissions"][number],
): boolean =>
  left.ownerKind === right.ownerKind &&
  sameId(left.ownerId, right.ownerId) &&
  sameId(left.permissionId, right.permissionId) &&
  left.applicationRootId !== undefined &&
  right.applicationRootId !== undefined &&
  sameId(left.applicationRootId, right.applicationRootId);

const contributionsBelongToDeclaration = (
  decision: OrganizationRecordAccessDecision,
  declaration: OrganizationRecordAccessDeclaration,
): boolean =>
  decision.outcome === "refused" ||
  decision.matchedContributions.every((contribution) =>
    declaration.requiredPermissions.some((permission) =>
      samePermission(contribution.permission, permission),
    ),
  );

const isBoundToRequest = (
  decision: OrganizationRecordAccessDecision,
  scope: SelectedOrganizationScope,
  declaration: OrganizationRecordAccessDeclaration,
  recordId: RecordId,
  current: CurrentEvidenceRow,
): boolean =>
  decision.operationKey === declaration.operationKey &&
  sameId(decision.target.applicationRootId, declaration.target.applicationRootId) &&
  sameId(decision.organizationId, scope.organizationId) &&
  sameId(decision.organizationAccountId, scope.organizationAccountId) &&
  decision.accessVersion === scope.accessVersion &&
  sameId(decision.recordId, recordId) &&
  sameRecordBinding(decision.recordBinding, declaration.recordBinding) &&
  sameAction(decision.action, declaration.action) &&
  contributionsBelongToDeclaration(decision, declaration) &&
  scope.applicationRootId !== undefined &&
  sameId(scope.applicationRootId, declaration.target.applicationRootId) &&
  typeof current.organization_id === "string" &&
  sameId(current.organization_id, decision.organizationId) &&
  typeof current.organization_account_id === "string" &&
  sameId(current.organization_account_id, decision.organizationAccountId) &&
  typeof current.application_root_id === "string" &&
  sameId(current.application_root_id, decision.target.applicationRootId) &&
  revision(current.access_version) === decision.accessVersion &&
  typeof current.correlation_id === "string" &&
  sameId(current.correlation_id, decision.correlationId) &&
  timestamp(current.expires_at) !== undefined &&
  timestamp(current.observed_at) !== undefined &&
  Date.parse(timestamp(current.expires_at)!) > Date.parse(timestamp(current.observed_at)!) &&
  Date.parse(decision.checkedAt) <= Date.parse(timestamp(current.observed_at)!) &&
  (decision.outcome === "refused" ||
    Date.parse(decision.validUntil) > Date.parse(timestamp(current.observed_at)!));

/**
 * Rebinds a fixed adapter's private database decision to the current protected
 * request before an operation consumes it. Unit tests cover this orchestration;
 * actual restricted-role neutral RLS enforcement remains the SQL430 proof.
 */
export const runOrganizationRecordAccessOperation = async <Command, Result>(
  transaction: RequestDatabaseTransaction,
  scopeCandidate: SelectedOrganizationScope,
  adapter: FixedOrganizationRecordAccessAdapter<Command>,
  command: Command,
  operation: (decision: AllowedOrganizationRecordAccessDecision) => Promise<Result>,
): Promise<OrganizationRecordAccessOperationResult<Result>> => {
  const scope = selectedOrganizationScopeSchema.safeParse(scopeCandidate);
  const declaration = organizationRecordAccessDeclarationSchema.safeParse(adapter.declaration);
  if (!scope.success || !declaration.success) throw unavailableError(unavailableCode);

  let targetRecordId: RecordId;
  let candidate: OrganizationRecordAccessDecision;
  try {
    targetRecordId = recordIdSchema.parse(adapter.recordId(command));
    candidate = await adapter.evaluate(transaction, command);
  } catch {
    throw unavailableError(unavailableCode);
  }
  const decision = organizationRecordAccessDecisionSchema.safeParse(candidate);
  let currentRows: readonly CurrentEvidenceRow[];
  try {
    currentRows = await transaction.query<CurrentEvidenceRow>`
      select checked ->> 'organizationId' as organization_id,
        checked ->> 'organizationAccountId' as organization_account_id,
        checked ->> 'applicationRootId' as application_root_id,
        checked ->> 'accessVersion' as access_version,
        checked ->> 'correlationId' as correlation_id,
        checked ->> 'expiresAt' as expires_at,
        pg_catalog.clock_timestamp() as observed_at
      from vortex_access.validated_human_request_context() as checked
    `;
  } catch {
    throw unavailableError(unavailableCode);
  }
  if (
    !decision.success ||
    currentRows.length !== 1 ||
    currentRows[0] === undefined ||
    !isBoundToRequest(decision.data, scope.data, declaration.data, targetRecordId, currentRows[0])
  )
    throw unavailableError(unavailableCode);
  if (decision.data.outcome === "refused") return safeOrganizationAccessRefusal(decision.data);

  return { outcome: "completed", value: await operation(decision.data) };
};
