-- #832: read, save and claim record types with more than 50 fields.
--
-- Every record reader builds a record's `fieldValues` (and the deadline paths
-- their `existingValues`) from a generated SQL expression: one element per
-- field, two arguments per element, inside a single
-- `pg_catalog.jsonb_build_object(...)` call. PostgreSQL refuses any function
-- call with more than 100 arguments (error 54023), so a record type with more
-- than 50 fields cannot be read, saved, changed or claimed for deadlines.
--
-- Each generator now emits the same pairs split into chunks of at most 50
-- pairs, joined with `||` between `pg_catalog.jsonb_build_object(...)` calls.
-- No argument list can then exceed 100 arguments. When a record type declares
-- 50 fields or fewer the text is unchanged: the chunk split is a single group,
-- so every generated expression is byte-identical to the previous one and the
-- produced values are the same as today. No field, token, type or ordering
-- changes; only the shape of the generated expression changes.
--
-- The same aggregation fragment is shared by the record facts loader
-- `load_record_access_facts_internal`, its named-action clone
-- `load_named_action_facts_internal` (generated by 20260915010000) and the
-- ownership-transfer twin `load_record_access_facts_for_transfer_installation_internal`.
-- `claim_record_deadline_refresh` (deadline refresh authority) and
-- `relationship_total_record_snapshot_internal` (the totals and deadline
-- closure snapshot) have their own copies. Each function's current definition
-- exists only as the result of earlier in-place patches, so they are patched
-- in place from their current definitions exactly as
-- `20260924001000_return_target_record_field_values.sql` does: each reviewed
-- source fragment must occur exactly once, or the migration aborts rather than
-- silently skipping a caller. Each is re-created under its own current owner,
-- so its OID, grants, comment, security and search_path stay put.

begin;

set local role vortex_record_owner;
grant create on schema vortex_record to vortex_record_adapter;
reset role;
set local role vortex_record_adapter;

do $migration$
declare
  -- Shared by the three facts loaders. `columns_value` is a jsonb map from
  -- lower-cased field id to its physical token, database value type and field
  -- type; the pairs are ordered by the lower-cased field id in the C collation.
  loader_pairs_old constant text := $q$      select pg_catalog.string_agg(
        pg_catalog.format(
          '%L, %s',
          column_entry.key,
          case column_entry.value ->> 'databaseValueType'
            when 'decimal' then
              pg_catalog.format('pg_catalog.to_jsonb(%I::text)', column_entry.value ->> 'token')
            when 'timestamp_with_time_zone' then
              pg_catalog.format(
                'pg_catalog.to_jsonb(pg_catalog.to_char(pg_catalog.timezone(''UTC'', %I), ''YYYY-MM-DD"T"HH24:MI:SS.US"Z"''))',
                column_entry.value ->> 'token'
              )
            when 'date' then
              pg_catalog.format(
                'pg_catalog.to_jsonb(pg_catalog.to_char(%I, ''YYYY-MM-DD''))',
                column_entry.value ->> 'token'
              )
            else pg_catalog.format('pg_catalog.to_jsonb(%I)', column_entry.value ->> 'token')
          end
        ),
        ', ' order by column_entry.key collate "C"
      )
      into value_expression
      from pg_catalog.jsonb_each(columns_value) as column_entry(key, value);$q$;
  loader_pairs_new constant text := $q$      select pg_catalog.string_agg(
        field_chunk.pairs_text,
        ') || pg_catalog.jsonb_build_object(' order by field_chunk.chunk_index
      )
      into value_expression
      from (
        select (ordered_fields.field_number - 1) / 50 as chunk_index,
          pg_catalog.string_agg(
            pg_catalog.format(
              '%L, %s',
              ordered_fields.key,
              case ordered_fields.value ->> 'databaseValueType'
                when 'decimal' then
                  pg_catalog.format('pg_catalog.to_jsonb(%I::text)', ordered_fields.value ->> 'token')
                when 'timestamp_with_time_zone' then
                  pg_catalog.format(
                    'pg_catalog.to_jsonb(pg_catalog.to_char(pg_catalog.timezone(''UTC'', %I), ''YYYY-MM-DD"T"HH24:MI:SS.US"Z"''))',
                    ordered_fields.value ->> 'token'
                  )
                when 'date' then
                  pg_catalog.format(
                    'pg_catalog.to_jsonb(pg_catalog.to_char(%I, ''YYYY-MM-DD''))',
                    ordered_fields.value ->> 'token'
                  )
                else pg_catalog.format('pg_catalog.to_jsonb(%I)', ordered_fields.value ->> 'token')
              end
            ),
            ', ' order by ordered_fields.key collate "C"
          ) as pairs_text
        from (
          select column_entry.key, column_entry.value,
            pg_catalog.row_number() over (
              order by column_entry.key collate "C"
            ) as field_number
          from pg_catalog.jsonb_each(columns_value) as column_entry(key, value)
        ) as ordered_fields
        group by (ordered_fields.field_number - 1) / 50
      ) as field_chunk;$q$;

  -- `claim_record_deadline_refresh` builds the same pairs with the same format
  -- but at the function body's own indentation.
  deadline_pairs_old constant text := $q$  select pg_catalog.string_agg(
    pg_catalog.format(
      '%L, %s', column_entry.key,
      case column_entry.value ->> 'databaseValueType'
        when 'decimal' then
          pg_catalog.format('pg_catalog.to_jsonb(%I::text)', column_entry.value ->> 'token')
        when 'timestamp_with_time_zone' then
          pg_catalog.format(
            'pg_catalog.to_jsonb(pg_catalog.to_char(pg_catalog.timezone(''UTC'', %I), ''YYYY-MM-DD"T"HH24:MI:SS.US"Z"''))',
            column_entry.value ->> 'token'
          )
        when 'date' then
          pg_catalog.format(
            'pg_catalog.to_jsonb(pg_catalog.to_char(%I, ''YYYY-MM-DD''))',
            column_entry.value ->> 'token'
          )
        else pg_catalog.format('pg_catalog.to_jsonb(%I)', column_entry.value ->> 'token')
      end
    ),
    ', ' order by column_entry.key collate "C"
  ) into value_expression
  from pg_catalog.jsonb_each(columns_value) as column_entry(key, value);$q$;
  deadline_pairs_new constant text := $q$  select pg_catalog.string_agg(
    field_chunk.pairs_text,
    ') || pg_catalog.jsonb_build_object(' order by field_chunk.chunk_index
  )
  into value_expression
  from (
    select (ordered_fields.field_number - 1) / 50 as chunk_index,
      pg_catalog.string_agg(
        pg_catalog.format(
          '%L, %s', ordered_fields.key,
          case ordered_fields.value ->> 'databaseValueType'
            when 'decimal' then
              pg_catalog.format('pg_catalog.to_jsonb(%I::text)', ordered_fields.value ->> 'token')
            when 'timestamp_with_time_zone' then
              pg_catalog.format(
                'pg_catalog.to_jsonb(pg_catalog.to_char(pg_catalog.timezone(''UTC'', %I), ''YYYY-MM-DD"T"HH24:MI:SS.US"Z"''))',
                ordered_fields.value ->> 'token'
              )
            when 'date' then
              pg_catalog.format(
                'pg_catalog.to_jsonb(pg_catalog.to_char(%I, ''YYYY-MM-DD''))',
                ordered_fields.value ->> 'token'
              )
            else pg_catalog.format('pg_catalog.to_jsonb(%I)', ordered_fields.value ->> 'token')
          end
        ),
        ', ' order by ordered_fields.key collate "C"
      ) as pairs_text
    from (
      select column_entry.key, column_entry.value,
        pg_catalog.row_number() over (
          order by column_entry.key collate "C"
        ) as field_number
      from pg_catalog.jsonb_each(columns_value) as column_entry(key, value)
    ) as ordered_fields
    group by (ordered_fields.field_number - 1) / 50
  ) as field_chunk;$q$;

  -- `relationship_total_record_snapshot_internal` reads its columns as
  -- `stored.%I` and names the jsonb_each alias `entry`.
  snapshot_pairs_old constant text := $q$  select pg_catalog.string_agg(
    pg_catalog.format(
      '%L, %s', entry.key,
      case entry.value ->> 'databaseValueType'
        when 'decimal' then pg_catalog.format('pg_catalog.to_jsonb(stored.%I::text)', entry.value ->> 'token')
        when 'timestamp_with_time_zone' then pg_catalog.format(
          'pg_catalog.to_jsonb(pg_catalog.to_char(pg_catalog.timezone(''UTC'', stored.%I), ''YYYY-MM-DD"T"HH24:MI:SS.US"Z"''))',
          entry.value ->> 'token'
        )
        when 'date' then pg_catalog.format(
          'pg_catalog.to_jsonb(pg_catalog.to_char(stored.%I, ''YYYY-MM-DD''))',
          entry.value ->> 'token'
        )
        else pg_catalog.format('pg_catalog.to_jsonb(stored.%I)', entry.value ->> 'token')
      end
    ), ', ' order by entry.key collate "C"
  ) into value_expression
  from pg_catalog.jsonb_each(columns_value) entry(key, value);$q$;
  snapshot_pairs_new constant text := $q$  select pg_catalog.string_agg(
    field_chunk.pairs_text,
    ') || pg_catalog.jsonb_build_object(' order by field_chunk.chunk_index
  )
  into value_expression
  from (
    select (ordered_fields.field_number - 1) / 50 as chunk_index,
      pg_catalog.string_agg(
        pg_catalog.format(
          '%L, %s', ordered_fields.key,
          case ordered_fields.value ->> 'databaseValueType'
            when 'decimal' then pg_catalog.format('pg_catalog.to_jsonb(stored.%I::text)', ordered_fields.value ->> 'token')
            when 'timestamp_with_time_zone' then pg_catalog.format(
              'pg_catalog.to_jsonb(pg_catalog.to_char(pg_catalog.timezone(''UTC'', stored.%I), ''YYYY-MM-DD"T"HH24:MI:SS.US"Z"''))',
              ordered_fields.value ->> 'token'
            )
            when 'date' then pg_catalog.format(
              'pg_catalog.to_jsonb(pg_catalog.to_char(stored.%I, ''YYYY-MM-DD''))',
              ordered_fields.value ->> 'token'
            )
            else pg_catalog.format('pg_catalog.to_jsonb(stored.%I)', ordered_fields.value ->> 'token')
          end
        ), ', ' order by ordered_fields.key collate "C"
      ) as pairs_text
    from (
      select entry.key, entry.value,
        pg_catalog.row_number() over (
          order by entry.key collate "C"
        ) as field_number
      from pg_catalog.jsonb_each(columns_value) entry(key, value)
    ) as ordered_fields
    group by (ordered_fields.field_number - 1) / 50
  ) as field_chunk;$q$;

  targets constant jsonb := pg_catalog.jsonb_build_array(
    pg_catalog.jsonb_build_array(
      'vortex_record.load_record_access_facts_internal(uuid,text,uuid,bigint)',
      loader_pairs_old, loader_pairs_new
    ),
    pg_catalog.jsonb_build_array(
      'vortex_record.load_named_action_facts_internal(text,uuid,bigint,uuid,uuid,uuid,bigint)',
      loader_pairs_old, loader_pairs_new
    ),
    pg_catalog.jsonb_build_array(
      'vortex_record.load_record_access_facts_for_transfer_installation_internal(uuid,uuid,bigint,jsonb)',
      loader_pairs_old, loader_pairs_new
    ),
    pg_catalog.jsonb_build_array(
      'vortex_record.claim_record_deadline_refresh(uuid,uuid,uuid,timestamptz)',
      deadline_pairs_old, deadline_pairs_new
    ),
    pg_catalog.jsonb_build_array(
      'vortex_record.relationship_total_record_snapshot_internal(jsonb,uuid,uuid,boolean)',
      snapshot_pairs_old, snapshot_pairs_new
    )
  );

  target jsonb;
  procedure_id pg_catalog.regprocedure;
  old_text text;
  new_text text;
  occurrences integer;
  definition text;
  owner_name name;
begin
  for target in
    select item.value
    from pg_catalog.jsonb_array_elements(targets) as item(value)
  loop
    procedure_id := (target ->> 0)::pg_catalog.regprocedure;
    old_text := target ->> 1;
    new_text := target ->> 2;

    definition := pg_catalog.pg_get_functiondef(procedure_id);
    if definition is null then
      raise exception using errcode = '55000',
        message = 'Wide record field-values target is unavailable',
        detail = procedure_id::text;
    end if;
    occurrences := (
      pg_catalog.length(definition)
      - pg_catalog.length(pg_catalog.replace(definition, old_text, ''))
    ) / pg_catalog.length(old_text);
    if occurrences <> 1 then
      raise exception using errcode = '55000',
        message = 'Wide record field-values patch does not match exactly once',
        detail = procedure_id::text;
    end if;
    definition := pg_catalog.replace(definition, old_text, new_text);

    -- Re-created under the function's own current owner so its grants,
    -- comment and OID stay put.
    select pg_catalog.pg_get_userbyid(procedure.proowner) into strict owner_name
    from pg_catalog.pg_proc as procedure
    where procedure.oid = procedure_id;
    execute pg_catalog.format('set local role %I', owner_name);
    execute definition;
    set local role vortex_record_adapter;
  end loop;
end
$migration$;

reset role;

set local role vortex_record_owner;
revoke create on schema vortex_record from vortex_record_adapter;
reset role;

commit;
