-- #562: a relationship may use any of its declared target record types.
--
-- A stored edge already names its concrete target: `to_storage_contract_id`
-- is the exact storage contract of the target record type the writer resolved
-- from the link value, and both edge writers refuse a type outside the
-- relationship's provisioned `target_record_type_ids`. What remained singular
-- was every reader and caller above the writers. They accepted only a
-- relationship declaring one `toRecordType` and refused, omitted or skipped a
-- `link_to_one_of_several` relationship declaring `toRecordTypes`:
--
-- * save: `save_base_record`, `save_named_action_set_fields_internal` and the
--   named-action creation plan refused the field outright;
-- * reads and permissions: the three facts loaders
--   (`load_record_access_facts_internal`, its named-action clone
--   `load_named_action_facts_internal` generated by 20260915010000, and the
--   ownership-transfer twin) omitted the relationship, so Access routes and
--   inherited ownership through it always refused;
-- * totals: total dependency resolution, the dependency-closure walk, the four
--   locked total preparations, the two save preflights and the named-action
--   link-target walk required or filtered on the single target;
-- * delete and restore: the lifecycle total-closure seed and the restore
--   invariant compared against the single target.
--
-- This migration gives every one of them the same rule. A relationship's
-- declared targets are its single `toRecordType` or its `toRecordTypes` list;
-- the concrete target is always the one the edge or link value actually
-- names, and it is accepted only when it is a member of that declared set.
-- `vortex_record.relationship_declares_target_internal` is that one
-- membership test for every Record caller. The private facts representation
-- carries one uniform `toRecordTypes` list on every relationship, and Access
-- proves the concrete stored target record's own type a member of it before
-- matching the edge witness against exactly that type.
--
-- The shared facts shape, its closed validator and every current producer and
-- consumer change together, so no singular compatibility path remains. The
-- edge table and its writers are unchanged; no stored data changes. #561's
-- relationship edge lock order is untouched: the link-target walk now includes
-- polymorphic links in the same canonical order, so their targets are locked
-- before edges exactly as single-target links are.
--
-- Every function below is patched in place from its current definition, as
-- `20260923220000_unify_relationship_edge_lock_order.sql` does: each reviewed
-- source fragment must occur exactly once, or the migration aborts rather than
-- silently skipping a caller.

begin;

set local role vortex_record_owner;
grant create on schema vortex_record to vortex_record_adapter;
reset role;
set local role vortex_record_adapter;

-- A relationship's declared targets are its single `toRecordType` (compiled
-- `link`) or its `toRecordTypes` list (compiled `link_to_one_of_several`, and
-- every private facts relationship). True only when the concrete record type
-- is one of them.
create function vortex_record.relationship_declares_target_internal(
  p_relationship jsonb,
  p_record_type_id uuid
)
returns boolean
language sql
immutable
security invoker
set search_path = ''
as $function$
  select p_record_type_id is not null and exists (
    select 1
    from pg_catalog.jsonb_array_elements(
      case
        when pg_catalog.jsonb_typeof(p_relationship -> 'toRecordType') = 'object'
          then pg_catalog.jsonb_build_array(p_relationship -> 'toRecordType')
        when pg_catalog.jsonb_typeof(p_relationship -> 'toRecordTypes') = 'array'
          then p_relationship -> 'toRecordTypes'
        else '[]'::jsonb
      end
    ) as target(value)
    where pg_catalog.lower(target.value ->> 'recordTypeId') =
      pg_catalog.lower(p_record_type_id::text)
  )
$function$;

-- Migration-time guard: returns the current definition with every
-- `[old, new]` pair substituted, each old fragment occurring exactly once.
create function vortex_record.apply_concrete_relationship_target_patch_internal(
  p_procedure pg_catalog.regprocedure,
  p_patches jsonb
)
returns text
language plpgsql
stable
security invoker
set search_path = ''
as $function$
declare
  definition text;
  patch jsonb;
  old_text text;
  occurrences integer;
begin
  definition := pg_catalog.pg_get_functiondef(p_procedure);
  if definition is null or pg_catalog.jsonb_typeof(p_patches) is distinct from 'array'
    or pg_catalog.jsonb_array_length(p_patches) = 0 then
    raise exception using errcode = '22023',
      message = 'Concrete relationship target patch is invalid';
  end if;
  for patch in select item.value from pg_catalog.jsonb_array_elements(p_patches) as item(value)
  loop
    old_text := patch ->> 0;
    if old_text is null or old_text = '' or patch ->> 1 is null then
      raise exception using errcode = '22023',
        message = 'Concrete relationship target patch is invalid';
    end if;
    occurrences := (
      pg_catalog.length(definition)
      - pg_catalog.length(pg_catalog.replace(definition, old_text, ''))
    ) / pg_catalog.length(old_text);
    if occurrences <> 1 then
      raise exception using errcode = '55000',
        message = 'Concrete relationship target patch does not match exactly once',
        detail = p_procedure::text;
    end if;
    definition := pg_catalog.replace(definition, old_text, patch ->> 1);
  end loop;
  return definition;
end
$function$;

do $migration$
declare
  -- Facts loaders: every relationship, single or polymorphic, carries one
  -- uniform `toRecordTypes` list.
  loader_old constant text := $q$      for relationship_item in
        select item.value
        from pg_catalog.jsonb_array_elements(record_type_item -> 'relationships') as item(value)
      loop
        -- One declared target only; see the header on polymorphic targets.
        if relationship_item ? 'toRecordType' then
          relationship_by_id := relationship_by_id || pg_catalog.jsonb_build_object(
            pg_catalog.lower(relationship_item ->> 'relationshipId'),
            pg_catalog.jsonb_build_object(
              'relationshipId', relationship_item -> 'relationshipId',
              'fromModuleRootId', module_root_value,
              'fromRecordTypeId', record_type_item -> 'recordTypeId',
              'toModuleRootId', relationship_item #> '{toRecordType,moduleRootId}',
              'toRecordTypeId', relationship_item #> '{toRecordType,recordTypeId}'
            )
          );
        end if;
      end loop;$q$;
  loader_new constant text := $q$      for relationship_item in
        select item.value
        from pg_catalog.jsonb_array_elements(record_type_item -> 'relationships') as item(value)
      loop
        -- Every declared target, single or polymorphic, as one uniform list;
        -- Access proves a concrete edge target a member of it.
        relationship_by_id := relationship_by_id || pg_catalog.jsonb_build_object(
          pg_catalog.lower(relationship_item ->> 'relationshipId'),
          pg_catalog.jsonb_build_object(
            'relationshipId', relationship_item -> 'relationshipId',
            'fromModuleRootId', module_root_value,
            'fromRecordTypeId', record_type_item -> 'recordTypeId',
            'toRecordTypes', coalesce((
              select pg_catalog.jsonb_agg(pg_catalog.jsonb_build_object(
                'moduleRootId', target.value -> 'moduleRootId',
                'recordTypeId', target.value -> 'recordTypeId'
              ) order by target.ordinality)
              from pg_catalog.jsonb_array_elements(
                case when relationship_item ? 'toRecordType'
                  then pg_catalog.jsonb_build_array(relationship_item -> 'toRecordType')
                  else relationship_item -> 'toRecordTypes'
                end
              ) with ordinality as target(value, ordinality)
            ), '[]'::jsonb)
          )
        );
      end loop;$q$;

  -- Access facts validator: the closed relationship shape.
  validator_old constant text := $q$  -- Relationships: unique identity, well-formed endpoints.
  for relationship_item in
    select value from pg_catalog.jsonb_array_elements(p_facts -> 'relationships') as item(value)
  loop
    if pg_catalog.jsonb_typeof(relationship_item) <> 'object'
      or not (relationship_item ?& array[
        'relationshipId', 'fromModuleRootId', 'fromRecordTypeId', 'toModuleRootId', 'toRecordTypeId'
      ])
      or exists (
        select 1 from pg_catalog.jsonb_object_keys(relationship_item) as supplied(key)
        where supplied.key <> all (array[
          'relationshipId', 'fromModuleRootId', 'fromRecordTypeId', 'toModuleRootId', 'toRecordTypeId'
        ])
      )
      or not vortex_context.is_non_nil_uuid(relationship_item ->> 'relationshipId')
      or not vortex_context.is_non_nil_uuid(relationship_item ->> 'fromModuleRootId')
      or not vortex_context.is_non_nil_uuid(relationship_item ->> 'fromRecordTypeId')
      or not vortex_context.is_non_nil_uuid(relationship_item ->> 'toModuleRootId')
      or not vortex_context.is_non_nil_uuid(relationship_item ->> 'toRecordTypeId') then
      raise exception using errcode = '22023', message = 'Record access facts are invalid';
    end if;$q$;
  validator_new constant text := $q$  -- Relationships: unique identity, well-formed endpoints. `toRecordTypes`
  -- is every declared target: one for a link, several for a link to one of
  -- several record types.
  for relationship_item in
    select value from pg_catalog.jsonb_array_elements(p_facts -> 'relationships') as item(value)
  loop
    if pg_catalog.jsonb_typeof(relationship_item) <> 'object'
      or not (relationship_item ?& array[
        'relationshipId', 'fromModuleRootId', 'fromRecordTypeId', 'toRecordTypes'
      ])
      or exists (
        select 1 from pg_catalog.jsonb_object_keys(relationship_item) as supplied(key)
        where supplied.key <> all (array[
          'relationshipId', 'fromModuleRootId', 'fromRecordTypeId', 'toRecordTypes'
        ])
      )
      or not vortex_context.is_non_nil_uuid(relationship_item ->> 'relationshipId')
      or not vortex_context.is_non_nil_uuid(relationship_item ->> 'fromModuleRootId')
      or not vortex_context.is_non_nil_uuid(relationship_item ->> 'fromRecordTypeId')
      or pg_catalog.jsonb_typeof(relationship_item -> 'toRecordTypes') is distinct from 'array'
      or pg_catalog.jsonb_array_length(relationship_item -> 'toRecordTypes') = 0
      or exists (
        select 1
        from pg_catalog.jsonb_array_elements(relationship_item -> 'toRecordTypes') as target(value)
        where pg_catalog.jsonb_typeof(target.value) <> 'object'
          or not (target.value ?& array['moduleRootId', 'recordTypeId'])
          or exists (
            select 1 from pg_catalog.jsonb_object_keys(target.value) as supplied(key)
            where supplied.key <> all (array['moduleRootId', 'recordTypeId'])
          )
          or not vortex_context.is_non_nil_uuid(target.value ->> 'moduleRootId')
          or not vortex_context.is_non_nil_uuid(target.value ->> 'recordTypeId')
      ) then
      raise exception using errcode = '22023', message = 'Record access facts are invalid';
    end if;$q$;

  -- Access row scope: the inherited-ownership chase proves the stored parent
  -- record's own type a declared target and witnesses the edge against it.
  chase_declare_old constant text := $q$  chase_edge_count integer;
  parent_record jsonb;$q$;
  chase_declare_new constant text := $q$  chase_edge_count integer;
  chase_target jsonb;
  parent_record jsonb;$q$;
  chase_witness_old constant text := $q$        exit when not vortex_access.record_relationship_witness_matches(
          (chase_relationship ->> 'relationshipId')::uuid,
          (chase_relationship ->> 'fromModuleRootId')::uuid,
          (chase_relationship ->> 'fromRecordTypeId')::uuid,
          (chase_relationship ->> 'toModuleRootId')::uuid,
          (chase_relationship ->> 'toRecordTypeId')::uuid,$q$;
  chase_witness_new constant text := $q$        select item.value into chase_target
        from pg_catalog.jsonb_array_elements(chase_relationship -> 'toRecordTypes') as item(value)
        where pg_catalog.lower(item.value ->> 'moduleRootId') =
            pg_catalog.lower(parent_scope ->> 'moduleRootId')
          and pg_catalog.lower(item.value ->> 'recordTypeId') =
            pg_catalog.lower(parent_scope ->> 'recordTypeId')
        limit 1;

        exit when chase_target is null;

        exit when not vortex_access.record_relationship_witness_matches(
          (chase_relationship ->> 'relationshipId')::uuid,
          (chase_relationship ->> 'fromModuleRootId')::uuid,
          (chase_relationship ->> 'fromRecordTypeId')::uuid,
          (chase_target ->> 'moduleRootId')::uuid,
          (chase_target ->> 'recordTypeId')::uuid,$q$;

  -- Access relationship routes: the evaluated record's own type must be a
  -- declared target, and the edge is witnessed against exactly that type.
  route_guard_old constant text := $q$    if relationship_decl is null
      or pg_catalog.lower(relationship_decl ->> 'toModuleRootId') <> pg_catalog.lower(target_type ->> 'moduleRootId')
      or pg_catalog.lower(relationship_decl ->> 'toRecordTypeId') <> pg_catalog.lower(target_type ->> 'recordTypeId') then$q$;
  route_guard_new constant text := $q$    if relationship_decl is null
      or not exists (
        select 1
        from pg_catalog.jsonb_array_elements(relationship_decl -> 'toRecordTypes') as declared(value)
        where pg_catalog.lower(declared.value ->> 'moduleRootId') = pg_catalog.lower(target_type ->> 'moduleRootId')
          and pg_catalog.lower(declared.value ->> 'recordTypeId') = pg_catalog.lower(target_type ->> 'recordTypeId')
      ) then$q$;
  route_witness_old constant text := $q$        (relationship_decl ->> 'fromRecordTypeId')::uuid,
        (relationship_decl ->> 'toModuleRootId')::uuid,
        (relationship_decl ->> 'toRecordTypeId')::uuid,$q$;
  route_witness_new constant text := $q$        (relationship_decl ->> 'fromRecordTypeId')::uuid,
        (target_type ->> 'moduleRootId')::uuid,
        (target_type ->> 'recordTypeId')::uuid,$q$;

  -- Save writers: a link names its single declared target and a link to one
  -- of several record types its declared list; the value's concrete target
  -- type must be a member.
  save_shape_old constant text := $q$        or field_value ->> 'type' <> 'link'
        or not (relationship_value ? 'toRecordType')
        or relationship_value ->> 'cardinality' not in ('one_to_one', 'many_to_one') then$q$;
  save_shape_new constant text := $q$        or not (relationship_value ? case field_value ->> 'type'
          when 'link' then 'toRecordType' else 'toRecordTypes' end)
        or relationship_value ->> 'cardinality' not in ('one_to_one', 'many_to_one') then$q$;
  save_change_old constant text := $q$          'targetRecordTypeId', relationship_value #> '{toRecordType,recordTypeId}',$q$;
  save_change_new constant text := $q$          'relationship', relationship_value,$q$;
  save_target_old constant text := $q$        if target_record_type_id <>
          (relationship_change ->> 'targetRecordTypeId')::uuid then$q$;
  save_target_new constant text := $q$        if not vortex_record.relationship_declares_target_internal(
          relationship_change -> 'relationship', target_record_type_id
        ) then$q$;

  -- Named-action creation plan: the same shape rule for a created record's
  -- link; the edge writer proves the concrete target a member.
  plan_shape_old constant text := $q$      -- Refusal 3: only the delivered #402 single-target to-one link semantics
      -- are implemented. Polymorphic targets remain #49 and must refuse, never
      -- be silently skipped.
      if field_value ->> 'type' in ('link', 'link_to_one_of_several') then
        select item.value into relationship_value
        from pg_catalog.jsonb_array_elements(target_type -> 'relationships') item(value)
        where pg_catalog.lower(item.value ->> 'fromFieldId') = field_key;
        if field_value ->> 'type' <> 'link'
          or relationship_value is null
          or not (relationship_value ? 'toRecordType')$q$;
  plan_shape_new constant text := $q$      -- Refusal 3: only to-one link semantics are implemented. A link names its
      -- single declared target and a link to one of several record types its
      -- declared list; the edge writer proves the concrete target a member.
      if field_value ->> 'type' in ('link', 'link_to_one_of_several') then
        select item.value into relationship_value
        from pg_catalog.jsonb_array_elements(target_type -> 'relationships') item(value)
        where pg_catalog.lower(item.value ->> 'fromFieldId') = field_key;
        if relationship_value is null
          or not (relationship_value ? case field_value ->> 'type'
            when 'link' then 'toRecordType' else 'toRecordTypes' end)$q$;

  -- Named-action link-target walk: every to-one link, single or polymorphic,
  -- is share-locked in the same canonical order before any edge is written.
  link_targets_old constant text := $q$      from pg_catalog.jsonb_array_elements(source_type -> 'relationships') item(value)
      where item.value ? 'toRecordType'
      order by pg_catalog.lower(item.value ->> 'fromFieldId') collate "C",$q$;
  link_targets_new constant text := $q$      from pg_catalog.jsonb_array_elements(source_type -> 'relationships') item(value)
      order by pg_catalog.lower(item.value ->> 'fromFieldId') collate "C",$q$;

  -- Total dependency closure: follow every to-one link whose concrete target
  -- is a declared target.
  closure_filter_old constant text := $q$      from pg_catalog.jsonb_array_elements(current_record -> 'recordType' -> 'relationships') item(value)
      where item.value ? 'toRecordType'
        and item.value ->> 'cardinality' in ('one_to_one', 'many_to_one')$q$;
  closure_filter_new constant text := $q$      from pg_catalog.jsonb_array_elements(current_record -> 'recordType' -> 'relationships') item(value)
      where item.value ->> 'cardinality' in ('one_to_one', 'many_to_one')$q$;
  closure_target_old constant text := $q$        if target_type_id <> (relationship #>> '{toRecordType,recordTypeId}')::uuid then$q$;
  closure_target_new constant text := $q$        if not vortex_record.relationship_declares_target_internal(relationship, target_type_id) then$q$;

  -- Locked total preparations: a total's relationship is the one declaring
  -- the prepared parent's concrete type among its targets.
  prepared_lookup_old constant text := $q$        and pg_catalog.lower(item.value #>> '{toRecordType,recordTypeId}') =
          pg_catalog.lower(prepared_record ->> 'recordTypeId');$q$;
  prepared_lookup_new constant text := $q$        and vortex_record.relationship_declares_target_internal(
          item.value, (prepared_record ->> 'recordTypeId')::uuid
        );$q$;

  -- Save preflights: one pass per declared concrete target type of each
  -- to-one relationship.
  preflight_loop_old constant text := $q$        for relationship_value in
          select item.value
          from pg_catalog.jsonb_array_elements(root_type -> 'relationships') item(value)
          where item.value ? 'toRecordType'
            and item.value ->> 'cardinality' in ('one_to_one', 'many_to_one')
        loop
          select item.value into target_type
          from pg_catalog.jsonb_array_elements(catalogue -> 'recordTypes') item(value)
          where pg_catalog.lower(item.value ->> 'recordTypeId') =
            pg_catalog.lower(relationship_value #>> '{toRecordType,recordTypeId}');$q$;
  preflight_loop_new constant text := $q$        for relationship_value, target_type in
          select item.value, target.value
          from pg_catalog.jsonb_array_elements(root_type -> 'relationships') item(value)
          join pg_catalog.jsonb_array_elements(catalogue -> 'recordTypes') target(value)
            on vortex_record.relationship_declares_target_internal(
              item.value, (target.value ->> 'recordTypeId')::uuid
            )
          where item.value ->> 'cardinality' in ('one_to_one', 'many_to_one')
          order by item.value ->> 'relationshipId', target.value ->> 'recordTypeId'
        loop$q$;
  preflight_contract_old constant text := $q$              pg_catalog.jsonb_build_array(relationship_value || pg_catalog.jsonb_build_object(
                'toRecordTypeId', relationship_value #> '{toRecordType,recordTypeId}'
              )),$q$;
  preflight_contract_new constant text := $q$              pg_catalog.jsonb_build_array(relationship_value),$q$;

  -- Total dependency contract: the same membership for compiled and facts
  -- relationships alike.
  contract_lookup_old constant text := $q$    and pg_catalog.lower(item.value ->> 'toRecordTypeId') =
      pg_catalog.lower(p_target_record_type_id::text);$q$;
  contract_lookup_new constant text := $q$    and vortex_record.relationship_declares_target_internal(
      item.value, p_target_record_type_id
    );$q$;

  -- Delete: a deleted source's parent is the edge's stored target contract,
  -- accepted only when its record type is a declared target.
  lifecycle_seed_old constant text := $q$      where pg_catalog.lower(item.value ->> 'recordTypeId') =
          pg_catalog.lower(relationship.value #>> '{toRecordType,recordTypeId}')
        and (item.value ->> 'storageContractId')::uuid = edge.to_storage_contract_id$q$;
  lifecycle_seed_new constant text := $q$      where (item.value ->> 'storageContractId')::uuid = edge.to_storage_contract_id
        and vortex_record.relationship_declares_target_internal(
          relationship.value, (item.value ->> 'recordTypeId')::uuid
        )$q$;

  -- Restore: a retained required link's concrete type must be declared and
  -- is then matched against the retained edge's stored target contract.
  restore_shape_old constant text := $q$      -- #402 supports the existing fixed-target to-one relationship contract.
      -- A polymorphic declaration is not inferred here.
      if relationship_value -> 'toRecordType' ->> 'state' <> 'resolved'
        or not (relationship_value -> 'toRecordType' ? 'recordTypeId')
        or pg_catalog.jsonb_typeof(retained_value) <> 'object'$q$;
  restore_shape_new constant text := $q$      -- The retained value names its concrete target type; it must be one of
      -- the relationship's declared targets and the retained edge's target.
      if pg_catalog.jsonb_typeof(retained_value) <> 'object'$q$;
  restore_target_old constant text := $q$      if retained_target_type_id <>
          (relationship_value -> 'toRecordType' ->> 'recordTypeId')::uuid then$q$;
  restore_target_new constant text := $q$      if not vortex_record.relationship_declares_target_internal(
        relationship_value, retained_target_type_id
      ) then$q$;

  target record;
  definition text;
  owner_name name;
begin
  for target in
    select candidate.procedure_id, candidate.patches
    from (values
      ('vortex_record.load_record_access_facts_internal(uuid,text,uuid,bigint)'::pg_catalog.regprocedure,
        pg_catalog.jsonb_build_array(pg_catalog.jsonb_build_array(loader_old, loader_new))),
      ('vortex_record.load_named_action_facts_internal(text,uuid,bigint,uuid,uuid,uuid,bigint)'::pg_catalog.regprocedure,
        pg_catalog.jsonb_build_array(pg_catalog.jsonb_build_array(loader_old, loader_new))),
      ('vortex_record.load_record_access_facts_for_transfer_installation_internal(uuid,uuid,bigint,jsonb)'::pg_catalog.regprocedure,
        pg_catalog.jsonb_build_array(pg_catalog.jsonb_build_array(loader_old, loader_new))),
      ('vortex_access.evaluate_organization_record_access_internal(jsonb,uuid,jsonb)'::pg_catalog.regprocedure,
        pg_catalog.jsonb_build_array(pg_catalog.jsonb_build_array(validator_old, validator_new))),
      ('vortex_access.evaluate_record_permission_row_scope_internal(jsonb,timestamptz,timestamptz,uuid,jsonb,jsonb,uuid,jsonb,uuid[])'::pg_catalog.regprocedure,
        pg_catalog.jsonb_build_array(
          pg_catalog.jsonb_build_array(chase_declare_old, chase_declare_new),
          pg_catalog.jsonb_build_array(chase_witness_old, chase_witness_new),
          pg_catalog.jsonb_build_array(route_guard_old, route_guard_new),
          pg_catalog.jsonb_build_array(route_witness_old, route_witness_new)
        )),
      ('vortex_record.save_base_record(uuid,text,uuid,uuid,bigint,jsonb,jsonb,uuid,uuid,uuid)'::pg_catalog.regprocedure,
        pg_catalog.jsonb_build_array(
          pg_catalog.jsonb_build_array(save_shape_old, save_shape_new),
          pg_catalog.jsonb_build_array(save_change_old, save_change_new),
          pg_catalog.jsonb_build_array(save_target_old, save_target_new)
        )),
      ('vortex_record.save_named_action_set_fields_internal(uuid,text,uuid,uuid,bigint,jsonb,jsonb,uuid,uuid,uuid,text,uuid,bigint,uuid,jsonb)'::pg_catalog.regprocedure,
        pg_catalog.jsonb_build_array(
          pg_catalog.jsonb_build_array(save_shape_old, save_shape_new),
          pg_catalog.jsonb_build_array(save_change_old, save_change_new),
          pg_catalog.jsonb_build_array(save_target_old, save_target_new)
        )),
      ('vortex_record.named_action_creation_plan_internal(text,uuid,bigint,uuid,uuid,jsonb)'::pg_catalog.regprocedure,
        pg_catalog.jsonb_build_array(pg_catalog.jsonb_build_array(plan_shape_old, plan_shape_new))),
      ('vortex_record.named_action_command_link_targets_internal(jsonb,uuid,jsonb,jsonb)'::pg_catalog.regprocedure,
        pg_catalog.jsonb_build_array(pg_catalog.jsonb_build_array(link_targets_old, link_targets_new))),
      ('vortex_record.discover_relationship_total_closure_internal(jsonb,text,uuid,uuid,jsonb)'::pg_catalog.regprocedure,
        pg_catalog.jsonb_build_array(
          pg_catalog.jsonb_build_array(closure_filter_old, closure_filter_new),
          pg_catalog.jsonb_build_array(closure_target_old, closure_target_new)
        )),
      ('vortex_record.prepare_relationship_total_save(uuid,text,uuid,uuid,bigint,jsonb,uuid,uuid)'::pg_catalog.regprocedure,
        pg_catalog.jsonb_build_array(pg_catalog.jsonb_build_array(prepared_lookup_old, prepared_lookup_new))),
      ('vortex_record.prepare_named_action_command_totals(uuid,uuid,uuid,bigint,jsonb,jsonb,uuid,text,uuid,bigint,uuid)'::pg_catalog.regprocedure,
        pg_catalog.jsonb_build_array(pg_catalog.jsonb_build_array(prepared_lookup_old, prepared_lookup_new))),
      ('vortex_record.prepare_record_deadline_closure(uuid,uuid,uuid,uuid,uuid,bigint,uuid,uuid,text,timestamptz)'::pg_catalog.regprocedure,
        pg_catalog.jsonb_build_array(pg_catalog.jsonb_build_array(prepared_lookup_old, prepared_lookup_new))),
      ('vortex_record.prepare_record_lifecycle_totals_internal(text,uuid,uuid,uuid,jsonb)'::pg_catalog.regprocedure,
        pg_catalog.jsonb_build_array(pg_catalog.jsonb_build_array(prepared_lookup_old, prepared_lookup_new))),
      ('vortex_record.save_base_record_with_relationship_totals(uuid,text,uuid,uuid,bigint,jsonb,jsonb,uuid,uuid,uuid,jsonb)'::pg_catalog.regprocedure,
        pg_catalog.jsonb_build_array(
          pg_catalog.jsonb_build_array(preflight_loop_old, preflight_loop_new),
          pg_catalog.jsonb_build_array(preflight_contract_old, preflight_contract_new)
        )),
      ('vortex_record.save_named_action_effects_with_relationship_totals(uuid,uuid,uuid,bigint,jsonb,jsonb,uuid,uuid,jsonb,jsonb,jsonb,jsonb,text,uuid,bigint,uuid,jsonb)'::pg_catalog.regprocedure,
        pg_catalog.jsonb_build_array(
          pg_catalog.jsonb_build_array(preflight_loop_old, preflight_loop_new),
          pg_catalog.jsonb_build_array(preflight_contract_old, preflight_contract_new)
        )),
      ('vortex_record.total_dependency_contract_internal(jsonb,jsonb,uuid,jsonb)'::pg_catalog.regprocedure,
        pg_catalog.jsonb_build_array(pg_catalog.jsonb_build_array(contract_lookup_old, contract_lookup_new))),
      ('vortex_record.record_lifecycle_total_closure_internal(jsonb,text,uuid,uuid,uuid)'::pg_catalog.regprocedure,
        pg_catalog.jsonb_build_array(pg_catalog.jsonb_build_array(lifecycle_seed_old, lifecycle_seed_new))),
      ('vortex_record.restore_record_internal(uuid,uuid,bigint)'::pg_catalog.regprocedure,
        pg_catalog.jsonb_build_array(
          pg_catalog.jsonb_build_array(restore_shape_old, restore_shape_new),
          pg_catalog.jsonb_build_array(restore_target_old, restore_target_new)
        ))
    ) as candidate(procedure_id, patches)
  loop
    -- Patched as this migration's adapter role, then re-created under the
    -- function's own current owner so its grants, comment and OID stay put.
    definition := vortex_record.apply_concrete_relationship_target_patch_internal(
      target.procedure_id, target.patches
    );
    select pg_catalog.pg_get_userbyid(procedure.proowner) into strict owner_name
    from pg_catalog.pg_proc as procedure
    where procedure.oid = target.procedure_id;
    execute pg_catalog.format('set local role %I', owner_name);
    execute definition;
    set local role vortex_record_adapter;
  end loop;
end
$migration$;

-- Migration-time patch guard; it has no runtime role once every caller above
-- has been rewritten.
drop function vortex_record.apply_concrete_relationship_target_patch_internal(
  pg_catalog.regprocedure, jsonb
);

revoke all on function vortex_record.relationship_declares_target_internal(jsonb, uuid)
from public, anon, authenticated, service_role, vortex_runtime, vortex_request,
  vortex_record_owner, vortex_module_owner;
grant execute on function vortex_record.relationship_declares_target_internal(jsonb, uuid)
to vortex_record_adapter;

comment on function vortex_record.relationship_declares_target_internal(jsonb, uuid) is
  'True only when a concrete record type is one of a relationship''s declared targets: its single toRecordType or a member of its toRecordTypes list.';

reset role;

set local role vortex_record_owner;
revoke create on schema vortex_record from vortex_record_adapter;
reset role;

commit;
