-- Document the persisted-state boundary for platform permission catalogue
-- version 1.2.0 (#550). Not executed by this task; source-only.
--
-- runtime/access/src/platform-permission-catalogue.ts now defines the
-- current catalogue at version 1.2.0: the historical `teams` key segment
-- (`platform.organization.teams.read` / `.manage`) is retired in favour of
-- `platform.organization.groups.read` / `.manage`. Every permission
-- identifier, action kind, administrative flag, label and description is
-- unchanged from the already-shipped 1.1.0 catalogue; only the two
-- permanent keys change, which under this schema's own definition of
-- authority-bearing meaning (see runtime/access/src/permission-fingerprints.ts,
-- which includes `key` in `fingerprintPermissionMeaning`) changes the
-- meaning fingerprint of those two entries and therefore requires a new
-- catalogue version rather than an in-place display-only edit.
--
-- vortex_access.adopt_shipped_platform_permission_catalogue and
-- vortex_access.platform_permission_catalogue_revision_is_exact, both
-- defined in an already-applied migration
-- (20260908124240_adopt_shipped_platform_permission_catalogue.sql), only
-- recognise a shipped target version of exactly '1.1.0'. They are not
-- rewritten here.
--
-- Organisations already adopted at '1.1.0' keep their persisted
-- `teams`-keyed rows unchanged by this task. Making '1.2.0' adoptable by a
-- real organisation requires a follow-up ordered migration that extends
-- those two functions (a new registration_revision = 4 branch, updated
-- catalogue_entries/permission_continuities bookkeeping and a matching
-- meaning-fingerprint recomputation for the two renamed keys) following the
-- same append-only, continuity-preserving pattern used for the 1.0.1 and
-- 1.1.0 steps. That migration is out of this bounded task's scope: no
-- database execution or review is part of this task, and this file
-- deliberately makes no schema or function change.
