-- #828: the facts loaders return only the target record's own field values.
--
-- `load_record_access_facts_internal`, its named-action clone
-- `load_named_action_facts_internal` (generated by 20260915010000) and the
-- ownership-transfer twin `load_record_access_facts_for_transfer_installation_internal`
-- load the target row into `record_fact`, then walk relationship and
-- inherited-ownership permission routes. That walk reuses `record_fact` for
-- every related record it loads or visits, and the loaders then returned
-- `record_fact -> 'fieldValues'`: the last record the walk touched, not the
-- target. Reads, saves, changes, named actions and transfers consume that
-- `fieldValues` as the target record's values, so a related record's values
-- could be shown or saved in the target's place.
--
-- Each loader now keeps the loaded target row in its own `target_fact`
-- variable, assigned once the target is known to exist and to match the
-- expected concurrency number, and returns `target_fact -> 'fieldValues'`.
-- Permission evaluation, the route walk and the returned facts are unchanged.
--
-- The three loaders' current definitions exist only as the result of earlier
-- in-place patches (20260913030000, 20260915010000, 20260923230000), so they
-- are patched in place from their current definitions exactly as
-- `20260923230000_concrete_relationship_edge_target_identity.sql` does: each
-- reviewed source fragment must occur exactly once, or the migration aborts
-- rather than silently skipping a loader. Each is re-created under its own
-- current owner, so its OID, grants, comment, security and search_path stay put.

begin;

set local role vortex_record_owner;
grant create on schema vortex_record to vortex_record_adapter;
reset role;
set local role vortex_record_adapter;

do $migration$
declare
  declare_old constant text := $q$  record_fact jsonb;
$q$;
  declare_new constant text := $q$  record_fact jsonb;
  target_fact jsonb;
$q$;

  -- The target row has been loaded, exists and matches the expected
  -- concurrency number; keep it apart from the route walk's `record_fact`.
  target_old constant text := $q$  records_by_id := pg_catalog.jsonb_build_object(
    pg_catalog.lower(p_record_id::text), record_fact
  );
$q$;
  target_new constant text := $q$  records_by_id := pg_catalog.jsonb_build_object(
    pg_catalog.lower(p_record_id::text), record_fact
  );
  target_fact := record_fact;
$q$;

  return_old constant text := $q$    'fieldValues', record_fact -> 'fieldValues'$q$;
  return_new constant text := $q$    'fieldValues', target_fact -> 'fieldValues'$q$;

  patches constant jsonb := pg_catalog.jsonb_build_array(
    pg_catalog.jsonb_build_array(declare_old, declare_new),
    pg_catalog.jsonb_build_array(target_old, target_new),
    pg_catalog.jsonb_build_array(return_old, return_new)
  );

  procedure_id pg_catalog.regprocedure;
  patch jsonb;
  old_text text;
  occurrences integer;
  definition text;
  owner_name name;
begin
  foreach procedure_id in array array[
    'vortex_record.load_record_access_facts_internal(uuid,text,uuid,bigint)'::pg_catalog.regprocedure,
    'vortex_record.load_named_action_facts_internal(text,uuid,bigint,uuid,uuid,uuid,bigint)'::pg_catalog.regprocedure,
    'vortex_record.load_record_access_facts_for_transfer_installation_internal(uuid,uuid,bigint,jsonb)'::pg_catalog.regprocedure
  ]
  loop
    definition := pg_catalog.pg_get_functiondef(procedure_id);
    if definition is null then
      raise exception using errcode = '55000',
        message = 'Record facts loader is unavailable',
        detail = procedure_id::text;
    end if;
    for patch in select item.value from pg_catalog.jsonb_array_elements(patches) as item(value)
    loop
      old_text := patch ->> 0;
      occurrences := (
        pg_catalog.length(definition)
        - pg_catalog.length(pg_catalog.replace(definition, old_text, ''))
      ) / pg_catalog.length(old_text);
      if occurrences <> 1 then
        raise exception using errcode = '55000',
          message = 'Record facts loader target patch does not match exactly once',
          detail = procedure_id::text;
      end if;
      definition := pg_catalog.replace(definition, old_text, patch ->> 1);
    end loop;

    -- Re-created under the function's own current owner so its grants,
    -- comment and OID stay put.
    select pg_catalog.pg_get_userbyid(procedure.proowner) into strict owner_name
    from pg_catalog.pg_proc as procedure
    where procedure.oid = procedure_id;
    execute pg_catalog.format('set local role %I', owner_name);
    execute definition;
    set local role vortex_record_adapter;
  end loop;
end
$migration$;

reset role;

set local role vortex_record_owner;
revoke create on schema vortex_record from vortex_record_adapter;
reset role;

commit;
