import {
  type PlatformBlockReleaseV2,
  platformBlockReleaseV2Schema,
  type ImmutablePlatformBlockCatalogueV2,
  immutablePlatformBlockCatalogueV2Schema,
} from "./application-composition-v2";

const deepFreeze = <Value>(value: Value): Value => {
  if (value === null || typeof value !== "object" || Object.isFrozen(value)) return value;
  for (const key of Reflect.ownKeys(value)) deepFreeze(Reflect.get(value, key));
  return Object.freeze(value);
};

/**
 * The registered platform block releases: the one source of block metadata for server
 * validation and for the renderer registrations that pair each release with its component. Each release is parsed through the release contract at module load and
 * deep-frozen. Fingerprints are the canonical-JSON SHA-256 values the publication catalogue
 * derives from the same content.
 */
const release = (definition: unknown): PlatformBlockReleaseV2 =>
  deepFreeze(platformBlockReleaseV2Schema.parse(definition));

/** Exact immutable metadata release for the plain text display block. */
export const TEXT_BLOCK_RELEASE: PlatformBlockReleaseV2 = release({
  blockId: "addfad00-1b11-4674-83fa-913667f87e79",
  key: "platform.display.text",
  releaseVersion: "1.0.0",
  contentFingerprint: "sha256:4a087e3647b1a5fc79a289f8ef40511c0bbd21ee89dce4b487f85066ba63e698",
  catalogueFingerprint: "sha256:13c5e23a1794a9da7c877404642eda7cd5c992a94d810a2fc4bb3c74a9df04bb",
  name: "Plain text",
  icon: "type",
  paletteGroup: "content",
  rendererKey: "platform.renderer.text",
  properties: [
    {
      kind: "text",
      key: "title",
      label: "Title",
      help: "Accessible name shown as the block heading",
      required: false,
      minLength: 1,
      maxLength: 120,
    },
    {
      kind: "text",
      key: "text",
      label: "Text",
      help: "Literal text shown when no projected value is supplied",
      required: false,
      minLength: 0,
      maxLength: 5000,
    },
    {
      kind: "text",
      key: "empty_message",
      label: "Empty message",
      help: "Text shown when there is no text to display",
      required: false,
      minLength: 0,
      maxLength: 200,
    },
  ],
  slots: [],
  capabilities: {
    responsiveVisibility: true,
    responsiveOrder: true,
    gridWidth: true,
    height: "content_or_bounded",
    publicSurface: "allowed",
    accessibleName: "optional",
    accessibleNamePropertyPath: ["title"],
  },
  supportedEvents: ["refresh"],
  supportedStateOperations: [],
});

/** Exact immutable metadata release for the structured rich text display block. */
export const RICH_TEXT_BLOCK_RELEASE: PlatformBlockReleaseV2 = release({
  blockId: "148f420f-f7db-4145-80f4-3d3fa036096b",
  key: "platform.display.rich_text",
  releaseVersion: "1.0.0",
  contentFingerprint: "sha256:467d05800b26b6030b0a6a85d4f66c467083773ec478e2bc5e827bbc84707ef1",
  catalogueFingerprint: "sha256:4d076a70f9f28e5b20735d212f4957c1eac3709f6dde80de3ae59794ca4e899e",
  name: "Rich text",
  icon: "file-text",
  paletteGroup: "content",
  rendererKey: "platform.renderer.rich_text",
  properties: [
    {
      kind: "text",
      key: "title",
      label: "Title",
      help: "Accessible name shown as the block heading",
      required: false,
      minLength: 1,
      maxLength: 120,
    },
    {
      kind: "rich_text",
      key: "document",
      label: "Content",
      help: "Structured content shown when no projected value is supplied",
      required: false,
      allowedElements: ["paragraph", "heading", "bulleted_list", "numbered_list", "emphasis", "link"],
    },
    {
      kind: "text",
      key: "empty_message",
      label: "Empty message",
      help: "Text shown when there is no content to display",
      required: false,
      minLength: 0,
      maxLength: 200,
    },
  ],
  slots: [],
  capabilities: {
    responsiveVisibility: true,
    responsiveOrder: true,
    gridWidth: true,
    height: "content_or_bounded",
    publicSurface: "allowed",
    accessibleName: "optional",
    accessibleNamePropertyPath: ["title"],
  },
  supportedEvents: ["refresh"],
  supportedStateOperations: [],
});

/** Exact immutable metadata release for the list display block. */
export const LIST_BLOCK_RELEASE: PlatformBlockReleaseV2 = release({
  blockId: "4881c816-e4ce-4c39-b0b7-20958b947748",
  key: "platform.display.list",
  releaseVersion: "1.0.0",
  contentFingerprint: "sha256:6e08c4d1dfb02a8c97656f63d6c63b5170be229bc327f0d2bb16b4fa97fb0bb1",
  catalogueFingerprint: "sha256:1003f628cd64c10e37762ba22d63f85988d503c5b40f485352a9fea0832fe913",
  name: "List",
  icon: "list",
  paletteGroup: "data",
  rendererKey: "platform.renderer.list",
  properties: [
    {
      kind: "text",
      key: "title",
      label: "Title",
      help: "Accessible name shown as the block heading",
      required: false,
      minLength: 1,
      maxLength: 120,
    },
    {
      kind: "text",
      key: "empty_message",
      label: "Empty message",
      help: "Text shown when there are no records to display",
      required: false,
      minLength: 0,
      maxLength: 200,
    },
  ],
  slots: [],
  capabilities: {
    responsiveVisibility: true,
    responsiveOrder: true,
    gridWidth: true,
    height: "content_or_bounded",
    publicSurface: "allowed",
    accessibleName: "optional",
    accessibleNamePropertyPath: ["title"],
  },
  supportedEvents: ["refresh", "row_action", "selection_changed", "page_changed"],
  supportedStateOperations: [],
});

/** Exact immutable metadata release for the table display block. */
export const TABLE_BLOCK_RELEASE: PlatformBlockReleaseV2 = release({
  blockId: "39ab6f28-c166-47cf-91a7-f0b864ded4ff",
  key: "platform.display.table",
  releaseVersion: "1.0.0",
  contentFingerprint: "sha256:f3834bd367a1e2fb8f1bacba947242055b26c92f475f769aa4821b53e6fa6ed8",
  catalogueFingerprint: "sha256:6d14243cbef91449ae6564a0fa8fb21eb854a5966920244392a32ce8d2874ab5",
  name: "Table",
  icon: "table",
  paletteGroup: "data",
  rendererKey: "platform.renderer.table",
  properties: [
    {
      kind: "text",
      key: "title",
      label: "Title",
      help: "Accessible name shown as the block heading",
      required: false,
      minLength: 1,
      maxLength: 120,
    },
    {
      kind: "text",
      key: "empty_message",
      label: "Empty message",
      help: "Text shown when there are no records to display",
      required: false,
      minLength: 0,
      maxLength: 200,
    },
  ],
  slots: [],
  capabilities: {
    responsiveVisibility: true,
    responsiveOrder: true,
    gridWidth: true,
    height: "content_or_bounded",
    publicSurface: "allowed",
    accessibleName: "optional",
    accessibleNamePropertyPath: ["title"],
  },
  supportedEvents: ["refresh", "row_action", "selection_changed", "sort_changed", "page_changed"],
  supportedStateOperations: [],
});

/** Exact immutable metadata release for the record detail display block. */
export const RECORD_DETAIL_BLOCK_RELEASE: PlatformBlockReleaseV2 = release({
  blockId: "e2569df0-2f10-4b20-b41d-177b66cd136c",
  key: "platform.display.record_detail",
  releaseVersion: "1.0.0",
  contentFingerprint: "sha256:4b2550cfe2935efc2e2e57d41e0376417baefdcd2a3539470fa08423792f5b98",
  catalogueFingerprint: "sha256:d0af4d9b65f61860a8e14ab9eda514d484e2308cfc8a2b35ec8e80dbebc195ca",
  name: "Record detail",
  icon: "file",
  paletteGroup: "record",
  rendererKey: "platform.renderer.record_detail",
  properties: [
    {
      kind: "text",
      key: "title",
      label: "Title",
      help: "Accessible name shown as the block heading",
      required: false,
      minLength: 1,
      maxLength: 120,
    },
    {
      kind: "text",
      key: "empty_message",
      label: "Empty message",
      help: "Text shown when there are no details to display",
      required: false,
      minLength: 0,
      maxLength: 200,
    },
  ],
  slots: [],
  capabilities: {
    responsiveVisibility: true,
    responsiveOrder: true,
    gridWidth: true,
    height: "content_or_bounded",
    publicSurface: "allowed",
    accessibleName: "optional",
    accessibleNamePropertyPath: ["title"],
  },
  supportedEvents: ["refresh", "row_action"],
  supportedStateOperations: [],
});

/** Exact immutable metadata release for the grouped data display block. */
export const GROUPED_DATA_BLOCK_RELEASE: PlatformBlockReleaseV2 = release({
  blockId: "6c27a0c2-ad91-4a5a-ab1d-54d337bebe36",
  key: "platform.display.grouped_data",
  releaseVersion: "1.0.0",
  contentFingerprint: "sha256:598d060d1de259928f19b9a573717162fa10568b194a0a12f81963a72bb7b0a3",
  catalogueFingerprint: "sha256:47666a6c2bea48a7307e3e7c52994336e736779ccc5079564747d9a863223b30",
  name: "Grouped data",
  icon: "layers",
  paletteGroup: "data",
  rendererKey: "platform.renderer.grouped_data",
  properties: [
    {
      kind: "text",
      key: "title",
      label: "Title",
      help: "Accessible name shown as the block heading",
      required: false,
      minLength: 1,
      maxLength: 120,
    },
    {
      kind: "text",
      key: "empty_message",
      label: "Empty message",
      help: "Text shown when there are no groups to display",
      required: false,
      minLength: 0,
      maxLength: 200,
    },
  ],
  slots: [],
  capabilities: {
    responsiveVisibility: true,
    responsiveOrder: true,
    gridWidth: true,
    height: "content_or_bounded",
    publicSurface: "allowed",
    accessibleName: "optional",
    accessibleNamePropertyPath: ["title"],
  },
  supportedEvents: ["refresh", "row_action", "selection_changed"],
  supportedStateOperations: [],
});

/** Exact immutable metadata release for the summary values display block. */
export const SUMMARY_VALUES_BLOCK_RELEASE: PlatformBlockReleaseV2 = release({
  blockId: "b00f7a0f-9094-4186-b8c4-066b1df6c395",
  key: "platform.display.summary_values",
  releaseVersion: "1.0.0",
  contentFingerprint: "sha256:8b8160d617dca754b1051f5690d577c4f1fdb3ac92677ce121e707d32341b74c",
  catalogueFingerprint: "sha256:d3f58f8c6eb95bf7022ac55df3edfda1e4f653d4a3a562281ef15d156ef42897",
  name: "Summary values",
  icon: "hash",
  paletteGroup: "figures",
  rendererKey: "platform.renderer.summary_values",
  properties: [
    {
      kind: "text",
      key: "title",
      label: "Title",
      help: "Accessible name shown as the block heading",
      required: false,
      minLength: 1,
      maxLength: 120,
    },
    {
      kind: "text",
      key: "empty_message",
      label: "Empty message",
      help: "Text shown when there are no values to display",
      required: false,
      minLength: 0,
      maxLength: 200,
    },
  ],
  slots: [],
  capabilities: {
    responsiveVisibility: true,
    responsiveOrder: true,
    gridWidth: true,
    height: "content_or_bounded",
    publicSurface: "allowed",
    accessibleName: "optional",
    accessibleNamePropertyPath: ["title"],
  },
  supportedEvents: ["refresh"],
  supportedStateOperations: [],
});

/** Exact immutable metadata release for the text input block. */
export const TEXT_INPUT_BLOCK_RELEASE: PlatformBlockReleaseV2 = release({
  blockId: "15b2d6f6-228d-4248-84be-1f8f45e204fc",
  key: "platform.form.text_input",
  releaseVersion: "1.0.0",
  contentFingerprint: "sha256:ac1633a389a0e63066584d60989292e71e95d091b951fb9c61b94290058aacb9",
  catalogueFingerprint: "sha256:089c881e4d7b1d39ef9282af7c9787afc09eb83f8fa87c55e3df14bf048ec065",
  name: "Text input",
  icon: "type",
  paletteGroup: "input",
  rendererKey: "platform.renderer.text_input",
  properties: [
    {
      kind: "text",
      key: "name",
      label: "Field name",
      help: "Key of this field in form values and events: lowercase words separated by underscores",
      required: true,
      minLength: 1,
      maxLength: 40,
    },
    {
      kind: "text",
      key: "label",
      label: "Label",
      help: "Accessible name and visual field label",
      required: true,
      minLength: 1,
      maxLength: 120,
    },
    {
      kind: "text",
      key: "placeholder",
      label: "Placeholder",
      help: "Placeholder hint text",
      required: false,
      minLength: 0,
      maxLength: 200,
    },
    {
      kind: "text",
      key: "help_text",
      label: "Help text",
      help: "Descriptive help text below the input",
      required: false,
      minLength: 0,
      maxLength: 500,
    },
    {
      kind: "boolean",
      key: "required",
      label: "Required",
      help: "Whether the field is required",
      required: false,
    },
    {
      kind: "boolean",
      key: "disabled",
      label: "Disabled",
      help: "Whether the field is disabled",
      required: false,
    },
    {
      kind: "boolean",
      key: "read_only",
      label: "Read-only",
      help: "Whether the field is read-only",
      required: false,
    },
    {
      kind: "boolean",
      key: "multiline",
      label: "Multiline",
      help: "Render as multi-line textarea",
      required: false,
    },
    {
      kind: "choice",
      key: "input_type",
      label: "Input type",
      help: "HTML input type",
      required: false,
      options: [
        {
          key: "text",
          label: "Text",
        },
        {
          key: "email",
          label: "Email",
        },
        {
          key: "password",
          label: "Password",
        },
        {
          key: "tel",
          label: "Telephone",
        },
        {
          key: "url",
          label: "URL",
        },
      ],
    },
  ],
  slots: [],
  capabilities: {
    responsiveVisibility: true,
    responsiveOrder: true,
    gridWidth: true,
    height: "content",
    publicSurface: "allowed",
    accessibleName: "required",
    accessibleNamePropertyPath: ["label"],
  },
  supportedEvents: ["field_changed"],
  supportedStateOperations: [],
});

/** Exact immutable metadata release for the number input block. */
export const NUMBER_INPUT_BLOCK_RELEASE: PlatformBlockReleaseV2 = release({
  blockId: "c8645b41-48b5-489c-bd2e-02283535a7c5",
  key: "platform.form.number_input",
  releaseVersion: "1.0.0",
  contentFingerprint: "sha256:7b4842382778e3c4fe82e0ec28c959218beed591182d75e68e5e205c87923e9b",
  catalogueFingerprint: "sha256:97dfe8ac6a7e44aa6fddf0df21237977b4bb44240a2a87f1ed9d17e304740fe1",
  name: "Number input",
  icon: "hash",
  paletteGroup: "input",
  rendererKey: "platform.renderer.number_input",
  properties: [
    {
      kind: "text",
      key: "name",
      label: "Field name",
      help: "Key of this field in form values and events: lowercase words separated by underscores",
      required: true,
      minLength: 1,
      maxLength: 40,
    },
    {
      kind: "text",
      key: "label",
      label: "Label",
      help: "Accessible name and visual field label",
      required: true,
      minLength: 1,
      maxLength: 120,
    },
    {
      kind: "text",
      key: "placeholder",
      label: "Placeholder",
      help: "Placeholder hint text",
      required: false,
      minLength: 0,
      maxLength: 200,
    },
    {
      kind: "text",
      key: "help_text",
      label: "Help text",
      help: "Descriptive help text below the input",
      required: false,
      minLength: 0,
      maxLength: 500,
    },
    {
      kind: "boolean",
      key: "required",
      label: "Required",
      help: "Whether the field is required",
      required: false,
    },
    {
      kind: "boolean",
      key: "disabled",
      label: "Disabled",
      help: "Whether the field is disabled",
      required: false,
    },
    {
      kind: "boolean",
      key: "read_only",
      label: "Read-only",
      help: "Whether the field is read-only",
      required: false,
    },
    {
      kind: "boolean",
      key: "integer",
      label: "Integer only",
      help: "Restrict input to whole numbers",
      required: false,
    },
    {
      kind: "number",
      key: "min_value",
      label: "Minimum value",
      help: "Minimum permitted numerical value",
      required: false,
      integer: false,
    },
    {
      kind: "number",
      key: "max_value",
      label: "Maximum value",
      help: "Maximum permitted numerical value",
      required: false,
      integer: false,
    },
    {
      kind: "number",
      key: "step_value",
      label: "Step interval",
      help: "Granularity of value changes",
      required: false,
      integer: false,
    },
  ],
  slots: [],
  capabilities: {
    responsiveVisibility: true,
    responsiveOrder: true,
    gridWidth: true,
    height: "content",
    publicSurface: "allowed",
    accessibleName: "required",
    accessibleNamePropertyPath: ["label"],
  },
  supportedEvents: ["field_changed"],
  supportedStateOperations: [],
});

/** Exact immutable metadata release for the boolean input block. */
export const BOOLEAN_INPUT_BLOCK_RELEASE: PlatformBlockReleaseV2 = release({
  blockId: "e9418c36-3234-4806-a05a-0f259482238d",
  key: "platform.form.boolean_input",
  releaseVersion: "1.0.0",
  contentFingerprint: "sha256:26cfa1e7aba67de07f8888b3bcc3e2e54e17d3231f820e1a120b4843d59b07f2",
  catalogueFingerprint: "sha256:e9ca9db5b9cd8b388ea604ca60e619ffd7f3d229923f6c3b053f941e5552c8e3",
  name: "Boolean input",
  icon: "check-square",
  paletteGroup: "input",
  rendererKey: "platform.renderer.boolean_input",
  properties: [
    {
      kind: "text",
      key: "name",
      label: "Field name",
      help: "Key of this field in form values and events: lowercase words separated by underscores",
      required: true,
      minLength: 1,
      maxLength: 40,
    },
    {
      kind: "text",
      key: "label",
      label: "Label",
      help: "Accessible name and visual field label",
      required: true,
      minLength: 1,
      maxLength: 120,
    },
    {
      kind: "text",
      key: "help_text",
      label: "Help text",
      help: "Descriptive help text",
      required: false,
      minLength: 0,
      maxLength: 500,
    },
    {
      kind: "boolean",
      key: "required",
      label: "Required",
      help: "Whether the field is required",
      required: false,
    },
    {
      kind: "boolean",
      key: "disabled",
      label: "Disabled",
      help: "Whether the field is disabled",
      required: false,
    },
    {
      kind: "choice",
      key: "variant",
      label: "Variant",
      help: "Visual representation as checkbox or switch",
      required: false,
      options: [
        {
          key: "checkbox",
          label: "Checkbox",
        },
        {
          key: "switch",
          label: "Switch",
        },
      ],
    },
  ],
  slots: [],
  capabilities: {
    responsiveVisibility: true,
    responsiveOrder: true,
    gridWidth: true,
    height: "content",
    publicSurface: "allowed",
    accessibleName: "required",
    accessibleNamePropertyPath: ["label"],
  },
  supportedEvents: ["field_changed"],
  supportedStateOperations: [],
});

/** Exact immutable metadata release for the date input block. */
export const DATE_INPUT_BLOCK_RELEASE: PlatformBlockReleaseV2 = release({
  blockId: "a5610880-05be-426b-a82b-7f3b645bf255",
  key: "platform.form.date_input",
  releaseVersion: "1.0.0",
  contentFingerprint: "sha256:9b809e15aeecf3f0fd67383d98a9c1fabac04c94db2e00368f74339965ed76de",
  catalogueFingerprint: "sha256:6abc82387c20258387aa69bd4735f19a3f3007a738735d5d598bc87cfddc5e39",
  name: "Date input",
  icon: "calendar",
  paletteGroup: "input",
  rendererKey: "platform.renderer.date_input",
  properties: [
    {
      kind: "text",
      key: "name",
      label: "Field name",
      help: "Key of this field in form values and events: lowercase words separated by underscores",
      required: true,
      minLength: 1,
      maxLength: 40,
    },
    {
      kind: "text",
      key: "label",
      label: "Label",
      help: "Accessible name and visual field label",
      required: true,
      minLength: 1,
      maxLength: 120,
    },
    {
      kind: "text",
      key: "help_text",
      label: "Help text",
      help: "Descriptive help text",
      required: false,
      minLength: 0,
      maxLength: 500,
    },
    {
      kind: "boolean",
      key: "required",
      label: "Required",
      help: "Whether the field is required",
      required: false,
    },
    {
      kind: "boolean",
      key: "disabled",
      label: "Disabled",
      help: "Whether the field is disabled",
      required: false,
    },
    {
      kind: "boolean",
      key: "read_only",
      label: "Read-only",
      help: "Whether the field is read-only",
      required: false,
    },
  ],
  slots: [],
  capabilities: {
    responsiveVisibility: true,
    responsiveOrder: true,
    gridWidth: true,
    height: "content",
    publicSurface: "allowed",
    accessibleName: "required",
    accessibleNamePropertyPath: ["label"],
  },
  supportedEvents: ["field_changed"],
  supportedStateOperations: [],
});

/** Exact immutable metadata release for the choice input block. */
export const CHOICE_INPUT_BLOCK_RELEASE: PlatformBlockReleaseV2 = release({
  blockId: "2bd013f9-48ad-43d3-a6eb-7fc3c130cf87",
  key: "platform.form.choice_input",
  releaseVersion: "1.0.0",
  contentFingerprint: "sha256:632b8133a29b6523c1388e4689884f798949271af0a00f6ec8fa114ebc5888f6",
  catalogueFingerprint: "sha256:3eb5a63257fb6fb47ed384573ae47938a86fbd99e65ed31bc62857b7170c2e1a",
  name: "Choice input",
  icon: "list",
  paletteGroup: "input",
  rendererKey: "platform.renderer.choice_input",
  properties: [
    {
      kind: "text",
      key: "name",
      label: "Field name",
      help: "Key of this field in form values and events: lowercase words separated by underscores",
      required: true,
      minLength: 1,
      maxLength: 40,
    },
    {
      kind: "text",
      key: "label",
      label: "Label",
      help: "Accessible name and visual field label",
      required: true,
      minLength: 1,
      maxLength: 120,
    },
    {
      kind: "text",
      key: "placeholder",
      label: "Placeholder",
      help: "Placeholder option label",
      required: false,
      minLength: 0,
      maxLength: 200,
    },
    {
      kind: "text",
      key: "help_text",
      label: "Help text",
      help: "Descriptive help text",
      required: false,
      minLength: 0,
      maxLength: 500,
    },
    {
      kind: "boolean",
      key: "required",
      label: "Required",
      help: "Whether the field is required",
      required: false,
    },
    {
      kind: "boolean",
      key: "disabled",
      label: "Disabled",
      help: "Whether the field is disabled",
      required: false,
    },
    {
      kind: "list",
      key: "options",
      label: "Options",
      help: "Choices offered when no projected options are supplied",
      required: false,
      minimumItems: 0,
      maximumItems: 100,
      item: {
        kind: "group",
        key: "option",
        label: "Option",
        required: true,
        properties: [
          {
            kind: "text",
            key: "key",
            label: "Key",
            help: "Stable option key: lowercase words separated by underscores",
            required: true,
            minLength: 1,
            maxLength: 40,
          },
          {
            kind: "text",
            key: "label",
            label: "Label",
            help: "Option text shown to people",
            required: true,
            minLength: 1,
            maxLength: 120,
          },
        ],
      },
    },
    {
      kind: "choice",
      key: "variant",
      label: "Variant",
      help: "Render as select dropdown or radio buttons",
      required: false,
      options: [
        {
          key: "select",
          label: "Select dropdown",
        },
        {
          key: "radio",
          label: "Radio buttons",
        },
      ],
    },
  ],
  slots: [],
  capabilities: {
    responsiveVisibility: true,
    responsiveOrder: true,
    gridWidth: true,
    height: "content",
    publicSurface: "allowed",
    accessibleName: "required",
    accessibleNamePropertyPath: ["label"],
  },
  supportedEvents: ["field_changed"],
  supportedStateOperations: [],
});

/** Exact immutable metadata release for the validation message block. */
export const VALIDATION_MESSAGE_BLOCK_RELEASE: PlatformBlockReleaseV2 = release({
  blockId: "78acc234-87bc-4e8f-986f-4857369b41f8",
  key: "platform.form.validation_message",
  releaseVersion: "1.0.0",
  contentFingerprint: "sha256:738bd011d18317f2b3e3901016357cdfce945c43e7482232be5006f51ee3d046",
  catalogueFingerprint: "sha256:876ca64b165ecda23f3e300561352f50c2c12d3a5a6b4eb4e1117060476232e2",
  name: "Validation message",
  icon: "alert-circle",
  paletteGroup: "input",
  rendererKey: "platform.renderer.validation_message",
  properties: [
    {
      kind: "text",
      key: "title",
      label: "Title",
      help: "Accessible title for validation message",
      required: false,
      minLength: 1,
      maxLength: 120,
    },
    {
      kind: "text",
      key: "for_field",
      label: "Target field",
      help: "Field name this message describes; absent for form-wide messages",
      required: false,
      minLength: 0,
      maxLength: 40,
    },
    {
      kind: "text",
      key: "message",
      label: "Message",
      help: "Static error message when no projected error is supplied",
      required: false,
      minLength: 0,
      maxLength: 1000,
    },
    {
      kind: "choice",
      key: "severity",
      label: "Severity",
      help: "Visual alert severity level",
      required: false,
      options: [
        {
          key: "error",
          label: "Error",
        },
        {
          key: "warning",
          label: "Warning",
        },
        {
          key: "info",
          label: "Info",
        },
      ],
    },
  ],
  slots: [],
  capabilities: {
    responsiveVisibility: true,
    responsiveOrder: true,
    gridWidth: true,
    height: "content",
    publicSurface: "allowed",
    accessibleName: "optional",
    accessibleNamePropertyPath: ["title"],
  },
  supportedEvents: [],
  supportedStateOperations: [],
});

/** Exact immutable metadata release for the button block. */
export const BUTTON_BLOCK_RELEASE: PlatformBlockReleaseV2 = release({
  blockId: "c6fb63eb-fdf4-4fdf-954d-7610aad7be1b",
  key: "platform.action.button",
  releaseVersion: "1.0.0",
  contentFingerprint: "sha256:e0c7038c22f41833299abde924616a4a35d3f3054491fa0629d765e641fc2a04",
  catalogueFingerprint: "sha256:f764f32aff25db3e0ec18d99d203f6c8b73371a17f79a379132790121a749573",
  name: "Button",
  icon: "play",
  paletteGroup: "actions",
  rendererKey: "platform.renderer.button",
  properties: [
    {
      kind: "text",
      key: "label",
      label: "Label",
      help: "Accessible name shown as the button text",
      required: true,
      minLength: 1,
      maxLength: 120,
    },
    {
      kind: "choice",
      key: "action_kind",
      label: "Action kind",
      help: "Action emits the action event; Submit and Reset use the enclosing form's one submit or reset event",
      required: false,
      options: [
        {
          key: "action",
          label: "Action",
        },
        {
          key: "submit",
          label: "Submit form",
        },
        {
          key: "reset",
          label: "Reset form",
        },
      ],
    },
    {
      kind: "choice",
      key: "variant",
      label: "Variant",
      help: "Visual appearance style",
      required: false,
      options: [
        {
          key: "primary",
          label: "Primary",
        },
        {
          key: "secondary",
          label: "Secondary",
        },
        {
          key: "danger",
          label: "Danger",
        },
        {
          key: "ghost",
          label: "Ghost",
        },
      ],
    },
    {
      kind: "boolean",
      key: "disabled",
      label: "Disabled",
      help: "Whether the button is disabled",
      required: false,
    },
  ],
  slots: [],
  capabilities: {
    responsiveVisibility: true,
    responsiveOrder: true,
    gridWidth: true,
    height: "content",
    publicSurface: "allowed",
    accessibleName: "required",
    accessibleNamePropertyPath: ["label"],
  },
  supportedEvents: ["action"],
  supportedStateOperations: [],
});

/** Exact immutable metadata release for the tabs block. */
export const TABS_BLOCK_RELEASE: PlatformBlockReleaseV2 = release({
  blockId: "a3b7065b-47ef-4c92-93d1-59300f8b059c",
  key: "platform.layout.tabs",
  releaseVersion: "1.0.0",
  contentFingerprint: "sha256:3dd3e78d528ff6b8c5addf7e3974b36d44f48222c919a5fd6e5b0f3cfcf39a5d",
  catalogueFingerprint: "sha256:f6392c7de7ede3c5ef39368b999c81fabcc1b26df1170a35dfbe894636f4d456",
  name: "Tabs",
  icon: "folder",
  paletteGroup: "layout",
  rendererKey: "platform.renderer.tabs",
  properties: [
    {
      kind: "text",
      key: "title",
      label: "Title",
      help: "Accessible name for the tabs container",
      required: true,
      minLength: 1,
      maxLength: 120,
    },
    {
      kind: "choice",
      key: "default_tab",
      label: "Default tab",
      help: "Tab selected first when no projected tab is supplied",
      required: false,
      options: [
        {
          key: "tab_one",
          label: "Tab 1",
        },
        {
          key: "tab_two",
          label: "Tab 2",
        },
        {
          key: "tab_three",
          label: "Tab 3",
        },
        {
          key: "tab_four",
          label: "Tab 4",
        },
      ],
    },
    {
      kind: "text",
      key: "tab_one_label",
      label: "Tab 1 label",
      help: "Label for the first tab button",
      required: false,
      minLength: 0,
      maxLength: 120,
    },
    {
      kind: "text",
      key: "tab_two_label",
      label: "Tab 2 label",
      help: "Label for the second tab button",
      required: false,
      minLength: 0,
      maxLength: 120,
    },
    {
      kind: "text",
      key: "tab_three_label",
      label: "Tab 3 label",
      help: "Label for the third tab button",
      required: false,
      minLength: 0,
      maxLength: 120,
    },
    {
      kind: "text",
      key: "tab_four_label",
      label: "Tab 4 label",
      help: "Label for the fourth tab button",
      required: false,
      minLength: 0,
      maxLength: 120,
    },
  ],
  slots: [
    {
      key: "tab_one",
      label: "First tab",
      required: true,
      allowedChildCategories: ["data", "figures", "record", "input", "actions", "layout", "content"],
    },
    {
      key: "tab_two",
      label: "Second tab",
      required: false,
      allowedChildCategories: ["data", "figures", "record", "input", "actions", "layout", "content"],
    },
    {
      key: "tab_three",
      label: "Third tab",
      required: false,
      allowedChildCategories: ["data", "figures", "record", "input", "actions", "layout", "content"],
    },
    {
      key: "tab_four",
      label: "Fourth tab",
      required: false,
      allowedChildCategories: ["data", "figures", "record", "input", "actions", "layout", "content"],
    },
  ],
  capabilities: {
    responsiveVisibility: true,
    responsiveOrder: true,
    gridWidth: true,
    height: "content_or_bounded",
    publicSurface: "allowed",
    accessibleName: "required",
    accessibleNamePropertyPath: ["title"],
  },
  supportedEvents: ["tab_changed"],
  supportedStateOperations: ["select_tab"],
});

/** Exact immutable metadata release for the dialog block. */
export const DIALOG_BLOCK_RELEASE: PlatformBlockReleaseV2 = release({
  blockId: "651460f1-5fce-4443-bc9d-4dd4b6ae8a8b",
  key: "platform.layout.dialog",
  releaseVersion: "1.0.0",
  contentFingerprint: "sha256:28152388001af9ae4b3c413758dccb9130037c2351779fc74e86ebccb2b0abf6",
  catalogueFingerprint: "sha256:c88813c84891dea27835598c2643be933498e43e4ca1c7636705707ffe8d7d73",
  name: "Dialog",
  icon: "message-square",
  paletteGroup: "layout",
  rendererKey: "platform.renderer.dialog",
  properties: [
    {
      kind: "text",
      key: "title",
      label: "Title",
      help: "Accessible name and modal heading",
      required: true,
      minLength: 1,
      maxLength: 120,
    },
    {
      kind: "boolean",
      key: "open",
      label: "Initially open",
      help: "Open when the page first renders, unless a projected open state is supplied",
      required: false,
    },
    {
      kind: "choice",
      key: "size",
      label: "Size",
      help: "Modal width size",
      required: false,
      options: [
        {
          key: "small",
          label: "Small",
        },
        {
          key: "medium",
          label: "Medium",
        },
        {
          key: "large",
          label: "Large",
        },
      ],
    },
  ],
  slots: [
    {
      key: "content",
      label: "Dialog content",
      required: true,
      allowedChildCategories: ["data", "figures", "record", "input", "actions", "layout", "content"],
    },
    {
      key: "actions",
      label: "Dialog actions",
      required: false,
      allowedChildCategories: ["actions"],
    },
  ],
  capabilities: {
    responsiveVisibility: true,
    responsiveOrder: true,
    gridWidth: true,
    height: "content_or_bounded",
    publicSurface: "allowed",
    accessibleName: "required",
    accessibleNamePropertyPath: ["title"],
  },
  supportedEvents: ["action"],
  supportedStateOperations: ["open", "close"],
});

/** Exact immutable metadata release for the drawer block. */
export const DRAWER_BLOCK_RELEASE: PlatformBlockReleaseV2 = release({
  blockId: "a399ff74-5716-4411-bca8-c5ab87ec2e7d",
  key: "platform.layout.drawer",
  releaseVersion: "1.0.0",
  contentFingerprint: "sha256:a879ded51d1b1e46506b497c9b837166123ddfa2d3728830469c1ed1b216cf31",
  catalogueFingerprint: "sha256:e0bf34948b8082fe307b3983bf0f4bb767f1c720bfe2fb9368df87044f12ae3a",
  name: "Drawer",
  icon: "sidebar",
  paletteGroup: "layout",
  rendererKey: "platform.renderer.drawer",
  properties: [
    {
      kind: "text",
      key: "title",
      label: "Title",
      help: "Accessible name and drawer heading",
      required: true,
      minLength: 1,
      maxLength: 120,
    },
    {
      kind: "boolean",
      key: "open",
      label: "Initially open",
      help: "Open when the page first renders, unless a projected open state is supplied",
      required: false,
    },
    {
      kind: "choice",
      key: "placement",
      label: "Placement",
      help: "Drawer slide-in direction",
      required: false,
      options: [
        {
          key: "left",
          label: "Left",
        },
        {
          key: "right",
          label: "Right",
        },
        {
          key: "top",
          label: "Top",
        },
        {
          key: "bottom",
          label: "Bottom",
        },
      ],
    },
    {
      kind: "choice",
      key: "size",
      label: "Size",
      help: "Drawer width or height size",
      required: false,
      options: [
        {
          key: "small",
          label: "Small",
        },
        {
          key: "medium",
          label: "Medium",
        },
        {
          key: "large",
          label: "Large",
        },
      ],
    },
  ],
  slots: [
    {
      key: "content",
      label: "Drawer content",
      required: true,
      allowedChildCategories: ["data", "figures", "record", "input", "actions", "layout", "content"],
    },
    {
      key: "actions",
      label: "Drawer actions",
      required: false,
      allowedChildCategories: ["actions"],
    },
  ],
  capabilities: {
    responsiveVisibility: true,
    responsiveOrder: true,
    gridWidth: true,
    height: "content_or_bounded",
    publicSurface: "allowed",
    accessibleName: "required",
    accessibleNamePropertyPath: ["title"],
  },
  supportedEvents: ["action"],
  supportedStateOperations: ["open", "close"],
});

/** Exact immutable metadata release for the general container block. */
export const CONTAINER_BLOCK_RELEASE: PlatformBlockReleaseV2 = release({
  blockId: "11d1a889-531f-4880-a1a4-5dda5289e5ff",
  key: "platform.layout.container",
  releaseVersion: "1.0.0",
  contentFingerprint: "sha256:87ad3a9f09aea303fea52278a2b15a2cd94f8fd778ef83ae53ec2b4c8a78fb57",
  catalogueFingerprint: "sha256:b2dfb51dca9296f53102a251a880a74d3b2c15797a19597b6ee16df5e7c88d0c",
  name: "Container",
  icon: "layout",
  paletteGroup: "layout",
  rendererKey: "platform.renderer.container",
  properties: [
    {
      kind: "choice",
      key: "direction",
      label: "Direction",
      help: "Arrange child slots stacked in a column or side by side in a row",
      required: false,
      options: [
        {
          key: "column",
          label: "Column",
        },
        {
          key: "row",
          label: "Row",
        },
      ],
    },
    {
      kind: "choice",
      key: "gap",
      label: "Gap",
      help: "Space between child slots",
      required: false,
      options: [
        {
          key: "none",
          label: "None",
        },
        {
          key: "small",
          label: "Small",
        },
        {
          key: "medium",
          label: "Medium",
        },
        {
          key: "large",
          label: "Large",
        },
      ],
    },
  ],
  slots: [
    {
      key: "header",
      label: "Header",
      required: false,
      allowedChildCategories: ["data", "figures", "record", "input", "actions", "layout", "content"],
    },
    {
      key: "menu",
      label: "Menu",
      required: false,
      allowedChildCategories: ["data", "figures", "record", "input", "actions", "layout", "content"],
    },
    {
      key: "content",
      label: "Content",
      required: false,
      allowedChildCategories: ["data", "figures", "record", "input", "actions", "layout", "content"],
    },
  ],
  capabilities: {
    responsiveVisibility: true,
    responsiveOrder: true,
    gridWidth: true,
    height: "content_or_bounded",
    publicSurface: "allowed",
    accessibleName: "not_applicable",
  },
  supportedEvents: [],
  supportedStateOperations: [],
});

/** Exact immutable metadata release for the heading block. */
export const HEADING_BLOCK_RELEASE: PlatformBlockReleaseV2 = release({
  blockId: "78bfeead-a38d-424a-81b9-7cd553b92bcc",
  key: "platform.layout.heading",
  releaseVersion: "1.0.0",
  contentFingerprint: "sha256:ba087207751d4f15f047d10187585dfaa41a6174b7d5c294a0ef94df3d02e790",
  catalogueFingerprint: "sha256:ddfccfe68cfce2fa54194a8a467cb2df67b8539554b291cdc37a7e463b50c0a5",
  name: "Heading",
  icon: "heading",
  paletteGroup: "layout",
  rendererKey: "platform.renderer.heading",
  properties: [
    {
      kind: "text",
      key: "text",
      label: "Text",
      help: "Heading text shown to people",
      required: true,
      minLength: 1,
      maxLength: 200,
    },
    {
      kind: "choice",
      key: "level",
      label: "Level",
      help: "Heading importance: one is the most important, four is the least",
      required: false,
      options: [
        {
          key: "one",
          label: "1",
        },
        {
          key: "two",
          label: "2",
        },
        {
          key: "three",
          label: "3",
        },
        {
          key: "four",
          label: "4",
        },
      ],
    },
  ],
  slots: [],
  capabilities: {
    responsiveVisibility: true,
    responsiveOrder: true,
    gridWidth: true,
    height: "content",
    publicSurface: "allowed",
    accessibleName: "required",
    accessibleNamePropertyPath: ["text"],
  },
  supportedEvents: [],
  supportedStateOperations: [],
});

/** Exact immutable metadata release for the form container block. */
export const FORM_CONTAINER_BLOCK_RELEASE: PlatformBlockReleaseV2 = release({
  blockId: "476e2c35-07d6-40cc-bf01-6ddb22ccca44",
  key: "platform.form.container",
  releaseVersion: "1.0.0",
  contentFingerprint: "sha256:4b2132dcc09accfe645ce90eaf9dc992a63759fc56e488b643438b4b5ade0045",
  catalogueFingerprint: "sha256:04a85b70a2d3348c97604d0f6dc3f6beec6857f1c203d1febaa5143ec03ba1f2",
  name: "Form container",
  icon: "edit-3",
  paletteGroup: "input",
  rendererKey: "platform.renderer.form_container",
  properties: [
    {
      kind: "text",
      key: "title",
      label: "Title",
      help: "Accessible name for the form",
      required: false,
      minLength: 1,
      maxLength: 120,
    },
  ],
  slots: [
    {
      key: "content",
      label: "Form content",
      required: true,
      allowedChildCategories: ["input", "actions", "content", "data", "figures", "record", "layout"],
    },
  ],
  capabilities: {
    responsiveVisibility: true,
    responsiveOrder: true,
    gridWidth: true,
    height: "content_or_bounded",
    publicSurface: "allowed",
    accessibleName: "optional",
    accessibleNamePropertyPath: ["title"],
  },
  supportedEvents: ["form_ready", "form_submit", "form_reset"],
  supportedStateOperations: ["set_value", "reset"],
});

/** Exact immutable metadata release for the link input block. */
export const LINK_INPUT_BLOCK_RELEASE: PlatformBlockReleaseV2 = release({
  blockId: "8d1b6a2f-4c3e-4f0a-9c2b-6f1d2e7a5b94",
  key: "platform.form.link_input",
  releaseVersion: "1.0.0",
  contentFingerprint: "sha256:b499216c1d2ec71075ac05cc66dc1d0a55fb66cafccd39a860625e8a2c45d563",
  catalogueFingerprint: "sha256:f74884790796039763c528e21b6d77d791e3b6c907ca838db9d137cd8aaed7fc",
  name: "Link input",
  icon: "link",
  paletteGroup: "input",
  rendererKey: "platform.renderer.link_input",
  properties: [
    {
      kind: "text",
      key: "name",
      label: "Field name",
      help: "Key of this field in form values and events: lowercase words separated by underscores",
      required: true,
      minLength: 1,
      maxLength: 40,
    },
    {
      kind: "text",
      key: "label",
      label: "Label",
      help: "Accessible name and visual field label",
      required: true,
      minLength: 1,
      maxLength: 120,
    },
    {
      kind: "text",
      key: "placeholder",
      label: "Placeholder",
      help: "Placeholder hint text",
      required: false,
      minLength: 0,
      maxLength: 200,
    },
    {
      kind: "text",
      key: "help_text",
      label: "Help text",
      help: "Descriptive help text below the input",
      required: false,
      minLength: 0,
      maxLength: 500,
    },
    {
      kind: "boolean",
      key: "required",
      label: "Required",
      help: "Whether the field is required",
      required: false,
    },
    {
      kind: "boolean",
      key: "disabled",
      label: "Disabled",
      help: "Whether the field is disabled",
      required: false,
    },
    {
      kind: "boolean",
      key: "read_only",
      label: "Read-only",
      help: "Whether the field is read-only",
      required: false,
    },
    {
      kind: "list",
      key: "record_types",
      label: "Allowed record types",
      help: "The record types this link input may reference",
      required: true,
      minimumItems: 1,
      maximumItems: 20,
      item: {
        kind: "record_type_reference",
        key: "record_type",
        label: "Record type",
        required: true,
      },
    },
  ],
  slots: [],
  capabilities: {
    responsiveVisibility: true,
    responsiveOrder: true,
    gridWidth: true,
    height: "content",
    publicSurface: "allowed",
    accessibleName: "required",
    accessibleNamePropertyPath: ["label"],
  },
  supportedEvents: ["field_changed"],
  supportedStateOperations: [],
});

/** Exact immutable metadata release for the structured rich text input block. */
export const RICH_TEXT_INPUT_BLOCK_RELEASE: PlatformBlockReleaseV2 = release({
  blockId: "6f2c8d94-1a7b-4e53-8d90-3c5e7b1a4f28",
  key: "platform.form.rich_text_input",
  releaseVersion: "1.0.0",
  contentFingerprint: "sha256:1fee85750dd6df78c38c42bac5197829e0d86dd1e33e6bbc6379ec2350d9e55f",
  catalogueFingerprint: "sha256:8dcdd848b984711b1cdc638c3a6174f3b388d02dbe692e7cd02d85377df593c4",
  name: "Rich text input",
  icon: "file-text",
  paletteGroup: "input",
  rendererKey: "platform.renderer.rich_text_input",
  properties: [
    {
      kind: "text",
      key: "name",
      label: "Field name",
      help: "Key of this field in form values and events: lowercase words separated by underscores",
      required: true,
      minLength: 1,
      maxLength: 40,
    },
    {
      kind: "text",
      key: "label",
      label: "Label",
      help: "Accessible name and visual field label",
      required: true,
      minLength: 1,
      maxLength: 120,
    },
    {
      kind: "text",
      key: "help_text",
      label: "Help text",
      help: "Descriptive help text below the input",
      required: false,
      minLength: 0,
      maxLength: 500,
    },
    {
      kind: "boolean",
      key: "required",
      label: "Required",
      help: "Whether the field is required",
      required: false,
    },
    {
      kind: "boolean",
      key: "disabled",
      label: "Disabled",
      help: "Whether the field is disabled",
      required: false,
    },
    {
      kind: "boolean",
      key: "read_only",
      label: "Read-only",
      help: "Whether the field is read-only",
      required: false,
    },
    {
      kind: "rich_text",
      key: "default_value",
      label: "Default value",
      help: "Structured content shown when the field has no value",
      required: false,
      allowedElements: [
        "paragraph",
        "heading",
        "bulleted_list",
        "numbered_list",
        "emphasis",
        "link",
      ],
    },
  ],
  slots: [],
  capabilities: {
    responsiveVisibility: true,
    responsiveOrder: true,
    gridWidth: true,
    height: "content_or_bounded",
    publicSurface: "allowed",
    accessibleName: "required",
    accessibleNamePropertyPath: ["label"],
  },
  supportedEvents: ["field_changed"],
  supportedStateOperations: [],
});

/** Exact immutable metadata release for the application launcher block. */
export const APPLICATION_LAUNCHER_BLOCK_RELEASE: PlatformBlockReleaseV2 = release({
  blockId: "b1a7c2e4-5d3f-4a91-8c26-0e7f4b9a1d33",
  key: "platform.launcher.application_launcher",
  releaseVersion: "1.0.0",
  contentFingerprint: "sha256:afa425183d7aa962b73435512e36c2d90ba8b542abecd81208cc50f64a63c526",
  catalogueFingerprint: "sha256:cd05a4e18beefa0140ba8b4435bb39070f326d5a6f697024bdcc4114356d896e",
  name: "Application launcher",
  icon: "grid",
  paletteGroup: "content",
  rendererKey: "platform.renderer.application_launcher",
  properties: [
    {
      kind: "text",
      key: "title",
      label: "Title",
      help: "Accessible name shown as the block heading",
      required: false,
      minLength: 1,
      maxLength: 120,
    },
    {
      kind: "text",
      key: "name_key",
      label: "Name cell key",
      help: "Projected cell key whose text names each application",
      required: false,
      minLength: 1,
      maxLength: 40,
    },
    {
      kind: "text",
      key: "icon_key",
      label: "Icon cell key",
      help: "Projected cell key whose text is the application icon key",
      required: false,
      minLength: 1,
      maxLength: 40,
    },
  ],
  slots: [
    {
      key: "side_panel",
      label: "Side panel",
      required: false,
      allowedChildCategories: ["data", "figures", "record", "input", "actions", "layout", "content"],
    },
  ],
  capabilities: {
    responsiveVisibility: true,
    responsiveOrder: true,
    gridWidth: true,
    height: "content_or_bounded",
    publicSurface: "allowed",
    accessibleName: "optional",
    accessibleNamePropertyPath: ["title"],
  },
  supportedEvents: ["refresh", "row_action"],
  supportedStateOperations: [],
});

/** Exact immutable metadata release for the link tiles block. */
export const LINK_TILES_BLOCK_RELEASE: PlatformBlockReleaseV2 = release({
  blockId: "c4d9e1f2-7a68-4c05-9b3d-5f2a8e6c0b47",
  key: "platform.launcher.link_tiles",
  releaseVersion: "1.0.0",
  contentFingerprint: "sha256:004acb0bfb792a33c51722b8da3d079f047bf6f1c7e098b5be326fabfacaf8b2",
  catalogueFingerprint: "sha256:6ca9f0b784b4345e3e5598e30ea2f23f6c16113a714c1ca4f8800f5785029a06",
  name: "Link tiles",
  icon: "link",
  paletteGroup: "content",
  rendererKey: "platform.renderer.link_tiles",
  properties: [
    {
      kind: "text",
      key: "title",
      label: "Title",
      help: "Accessible name shown as the block heading",
      required: false,
      minLength: 1,
      maxLength: 120,
    },
    {
      kind: "text",
      key: "label_key",
      label: "Label cell key",
      help: "Projected cell key whose text labels each tile",
      required: false,
      minLength: 1,
      maxLength: 40,
    },
    {
      kind: "text",
      key: "address_key",
      label: "Address cell key",
      help: "Projected cell key carrying each tile's safe HTTPS address",
      required: false,
      minLength: 1,
      maxLength: 40,
    },
    {
      kind: "text",
      key: "description_key",
      label: "Description cell key",
      help: "Projected cell key whose text describes each tile",
      required: false,
      minLength: 1,
      maxLength: 40,
    },
  ],
  slots: [
    {
      key: "actions",
      label: "Tile actions",
      required: false,
      allowedChildCategories: ["actions"],
    },
  ],
  capabilities: {
    responsiveVisibility: true,
    responsiveOrder: true,
    gridWidth: true,
    height: "content_or_bounded",
    publicSurface: "allowed",
    accessibleName: "optional",
    accessibleNamePropertyPath: ["title"],
  },
  supportedEvents: ["refresh", "row_action"],
  supportedStateOperations: [],
});

/** Exact immutable metadata release for the view filter block. */
export const VIEW_FILTER_BLOCK_RELEASE: PlatformBlockReleaseV2 = release({
  blockId: "d7e3b8a5-2f49-4e6c-a1d0-9c4b7f2e8a15",
  key: "platform.launcher.view_filter",
  releaseVersion: "1.0.0",
  contentFingerprint: "sha256:4c981d2438439ce394f676e7b1260673155c14cabd100d613f1ae0bd7c795251",
  catalogueFingerprint: "sha256:d1cc11fe2423bec93eeffd6b603065358374bbb4d9e4b6d6f6fe0d1eac4e59a8",
  name: "View filter",
  icon: "filter",
  paletteGroup: "input",
  rendererKey: "platform.renderer.view_filter",
  properties: [
    {
      kind: "text",
      key: "label",
      label: "Label",
      help: "Accessible name and visual label for the filter",
      required: true,
      minLength: 1,
      maxLength: 120,
    },
    {
      kind: "text",
      key: "placeholder",
      label: "Placeholder",
      help: "Placeholder hint text",
      required: false,
      minLength: 0,
      maxLength: 200,
    },
    {
      kind: "text",
      key: "help_text",
      label: "Help text",
      help: "Descriptive help text below the filter",
      required: false,
      minLength: 0,
      maxLength: 500,
    },
    {
      kind: "text",
      key: "match_key",
      label: "Match cell key",
      help: "Projected cell key of each filtered tile matched by the entered text; defaults to its name",
      required: false,
      minLength: 1,
      maxLength: 40,
    },
    {
      kind: "choice",
      key: "match_mode",
      label: "Match mode",
      help: "How entered text is matched against the projected cell",
      required: false,
      options: [
        {
          key: "contains",
          label: "Contains",
        },
        {
          key: "starts_with",
          label: "Starts with",
        },
        {
          key: "exact",
          label: "Exact",
        },
      ],
    },
    {
      kind: "boolean",
      key: "case_sensitive",
      label: "Case sensitive",
      help: "Match the entered text case-sensitively",
      required: false,
    },
    {
      kind: "text",
      key: "empty_message",
      label: "Empty message",
      help: "Text shown when no already-returned row matches the filter",
      required: false,
      minLength: 0,
      maxLength: 200,
    },
  ],
  slots: [
    {
      key: "content",
      label: "Filtered content",
      required: true,
      allowedChildCategories: ["content", "layout"],
    },
  ],
  capabilities: {
    responsiveVisibility: true,
    responsiveOrder: true,
    gridWidth: true,
    height: "content_or_bounded",
    publicSurface: "allowed",
    accessibleName: "required",
    accessibleNamePropertyPath: ["label"],
  },
  supportedEvents: [],
  supportedStateOperations: [],
});

/** All seven immutable display block releases. */
export const DISPLAY_BLOCK_RELEASES: readonly PlatformBlockReleaseV2[] = Object.freeze([
  TEXT_BLOCK_RELEASE,
  RICH_TEXT_BLOCK_RELEASE,
  LIST_BLOCK_RELEASE,
  TABLE_BLOCK_RELEASE,
  RECORD_DETAIL_BLOCK_RELEASE,
  GROUPED_DATA_BLOCK_RELEASE,
  SUMMARY_VALUES_BLOCK_RELEASE,
]);

/** All thirteen immutable form, layout and action block releases. */
export const CONTROL_BLOCK_RELEASES: readonly PlatformBlockReleaseV2[] = Object.freeze([
  TEXT_INPUT_BLOCK_RELEASE,
  LINK_INPUT_BLOCK_RELEASE,
  RICH_TEXT_INPUT_BLOCK_RELEASE,
  NUMBER_INPUT_BLOCK_RELEASE,
  BOOLEAN_INPUT_BLOCK_RELEASE,
  DATE_INPUT_BLOCK_RELEASE,
  CHOICE_INPUT_BLOCK_RELEASE,
  VALIDATION_MESSAGE_BLOCK_RELEASE,
  BUTTON_BLOCK_RELEASE,
  TABS_BLOCK_RELEASE,
  DIALOG_BLOCK_RELEASE,
  DRAWER_BLOCK_RELEASE,
  FORM_CONTAINER_BLOCK_RELEASE,
]);

/** All three immutable launcher, tile and view-filter block releases. */
export const LAUNCHER_BLOCK_RELEASES: readonly PlatformBlockReleaseV2[] = Object.freeze([
  APPLICATION_LAUNCHER_BLOCK_RELEASE,
  LINK_TILES_BLOCK_RELEASE,
  VIEW_FILTER_BLOCK_RELEASE,
]);

/** All two immutable general layout block releases. */
export const LAYOUT_BLOCK_RELEASES: readonly PlatformBlockReleaseV2[] = Object.freeze([
  CONTAINER_BLOCK_RELEASE,
  HEADING_BLOCK_RELEASE,
]);

/** All twenty-five immutable platform block releases registered for the page builder. */
export const PLATFORM_BLOCK_RELEASES: readonly PlatformBlockReleaseV2[] = Object.freeze([
  ...DISPLAY_BLOCK_RELEASES,
  ...CONTROL_BLOCK_RELEASES,
  ...LAUNCHER_BLOCK_RELEASES,
  ...LAYOUT_BLOCK_RELEASES,
]);

/**
 * Closed immutable platform block catalogue for pure V2 composition validation and materialisation.
 * Server-owned; client-side renderer changes cannot alter or expand this allowlist.
 */
export const IMMUTABLE_PLATFORM_BLOCK_CATALOGUE_V2: ImmutablePlatformBlockCatalogueV2 =
  deepFreeze(
    immutablePlatformBlockCatalogueV2Schema.parse({
      compositionPolicy: {
        maximumDepth: 32,
        maximumPlacements: 512,
      },
      releases: PLATFORM_BLOCK_RELEASES,
    }),
  );
